PATH_REPOSITORY=//volt/INOUT/I+D+i/jespada
PATH_WORK=`pwd`
DATE_BACKUP=`date +%Y%m%d`
TIME_BACKUP=`date +%H%M%S`
SRC_DIR="$1";

BACKUP_DIRECTORY=bck/$DATE_BACKUP

if [ $# -eq 0 ]; then
	echo "Put name of directory to make a backup."
	exit -1
fi

if ! [ -d "$SRC_DIR" ]; then
	echo "Directory " $SRC_DIR " doesn't exist!"
	exit -1
fi

if ! [ -d $PATH_WORK/$BACKUP_DIRECTORY ]; then
	mkdir 	$PATH_WORK/$BACKUP_DIRECTORY --parents
fi

if ! [ -d $PATH_REPOSITORY/$BACKUP_DIRECTORY ]; then
	mkdir 	$PATH_REPOSITORY/$BACKUP_DIRECTORY --parents
fi

FILES_TO_IGNORE=$2;

FILES_TO_IGNORE=$FILES_TO_IGNORE" *.svn* "
#FILES_TO_IGNORE=$FILES_TO_IGNORE" \*.svn\* "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.obj "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.sdf "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.dll "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.ilk "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.ipch "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.lib "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.exp "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.pdb "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.log "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.tlog "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.class "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.settings "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.manifest "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.pch "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.idb "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.lastbuildstate "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.db "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.res "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.sbr "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.suo "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.bpl "
FILES_TO_IGNORE=$FILES_TO_IGNORE" *.bsc "

NAME_ZIP=$(basename "$SRC_DIR")
NAME_ZIP=$(echo $NAME_ZIP|sed 's/\.\.*/_/')

#create local copy to backup dir
zip -r $PATH_WORK/$BACKUP_DIRECTORY/$NAME_ZIP"_"$DATE_BACKUP"_"$TIME_BACKUP".zip" "$SRC_DIR"/* -x $FILES_TO_IGNORE

#make copy to repository
cp $PATH_WORK/$BACKUP_DIRECTORY/$NAME_ZIP"_"$DATE_BACKUP"_"$TIME_BACKUP".zip" $PATH_REPOSITORY/$BACKUP_DIRECTORY/$NAME_ZIP"_"$DATE_BACKUP"_"$TIME_BACKUP".zip" 