#!/bin/bash


param=""

for var in "$@"
do
    param=$param" "$(echo "$var")
done


TARGET="Unix Makefiles"
if [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
   echo compile for mingw32 ...
   TARGET="MSYS Makefiles"
fi

# Setting up chaiscript base,engine, hardware, bgd ...
cd ../base
rm CMakeCache.txt
rm CMakeFiles -R
cmake CMakeLists.txt -G "$TARGET" $param


cd ../engine
rm CMakeCache.txt
rm CMakeFiles -R
cmake CMakeLists.txt -G "$TARGET" $param



cd ../gui
rm CMakeCache.txt
rm CMakeFiles -R
cmake CMakeLists.txt -G "$TARGET" $param


