=== Call ZetScript from C++

To make a ZetScript function callable from C&#43;&#43; is done through `ZetScript::bindScriptFunction`. `ZetScript::bindScriptFunction` it binds ZetScript function by the C&#43;&#43; function signature and the symbol name or ScriptFunction object.

*Syntax*

[source,c++]
----
 ZetScript::bindScriptFunction<ReturnType(ParamType1, ParamType2, ..., ParamType9)>(const zs_string & _script_function);
----

[.underline]#Parameters#

 - _ReturnType_: It can be void or some type defined in <<ZetScript built-in types>> or other registered type.
 - _ParamTypeX_: It can be one defined in <<ZetScript built-in types>> or other registered type.
 - __script_function_: `ZetScript::zs_string` or `ScriptFunction *` as the name or the script function reference to be binded.


[.underline]#Returns#

Returns a `std::function` with the signature provided

*Example*

The following example it binds a _sayHelloWorld_ function

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_out.txt[]
----

==== Return types

This section will explain how to bind script functions that return the following types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Instance of class type object
- Instance of registered type object

===== Return Boolean

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[Boolean]* it must specify *bool* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_bool.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_bool_out.txt[]
----

===== Return Integer

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_integer[Integer]* it must specify *zs_int* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_int.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_int_out.txt[]
----

===== Return Float

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_float[Float]* it must specify *zs_float* return type on its function signature.


*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_float.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_float_out.txt[]
----


===== Return String

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_string[String]* it can be done by specifying the following return types in its function signature,

 - const char *
 - zs_string
 - StringScriptObject *

====== Return String as const char *

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_string[String]* it can specify *const char &#42;* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_const_char.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_const_char_out.txt[]
----

====== Return String as zs_string

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_string[String]* it can specify *zs_string* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_string.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_string_out.txt[]
----


====== Return String as StringScriptObject *

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_string[String]* it can specify *StringScriptObject &#42;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_string_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_string_script_object_out.txt[]
----

===== Return Array

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_array[Array]* it must specify *ArrayScriptObject &#42;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.


*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_array_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_array_script_object_out.txt[]
----


===== Return Object

To bind a ZetScript function that returns a *xref:chapters/chapter_2_the_language_data_types.adoc#_object[Object]* it must specify *ObjectScriptObject &#42;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_object_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_object_script_object_out.txt[]
----

===== Return instance of class type object

To bind a ZetScript function that returns an *xref:chapters/chapter_2_the_language_data_types.adoc#_script_class[instance of class type object]* it can specify *ObjectScriptObject &#42;* or *ClassScriptObject &#42;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_class_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_class_script_object_out.txt[]
----

===== Return instance of registered type object

To bind a ZetScript function that returns an instance of *xref:chapters/chapter_3_the_api.adoc#_registerer_type[registered type]* object it must specify *ClassScriptObject &#42;* return type on its function signature. After returning  *ClassScriptObject &#42;*, it can fetch its C++ registered type by calling `ClassScriptObject::to<_T *>`, where _T is the C&#43;&#43; type.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

In this example, it registers _Point_ type, its constructor and its properties _x_ and _y_. After evaluate ZetScript code that defines a function that return a new object type _Point_, it is binded to be callable in C++.  When it calls _returnPoint_ in C&#43;&#43;, it returns a variable as type *ClassScriptObject &#42;* object that it prints its contents. Later it gets the registered class reference and also it prints its contents.

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_registered_type.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_registered_type_out.txt[]
----

==== Parameter types


This section will explain how to bind script functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered class 

===== Parameter Boolean

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[Boolean]* it must specify *bool &#42;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_bool.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_bool_out.txt[]
----

===== Parameter Integer

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[Integer]* it must specify *zs_int* or *zs_int &#42;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_int.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_int_out.txt[]
----

===== Parameter Float

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[Float]* it must specify or *zs_float &#42;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_float.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_float_out.txt[]
----

===== Parameter String

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify the following types as a parameter on its function signature,

 - const char *
 - zs_string *
 - StringScriptObject *

===== Parameter String as const char *

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *const char &#42;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_const_char.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_const_char_out.txt[]
----

===== Parameter String as zs_string *

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *zs_string &#42;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_string.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_string_out.txt[]
----


===== Parameter String as StringScriptObject *

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *StringScriptObject &#42;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_string_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_string_script_object_out.txt[]
----

===== Parameter Array

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[Array]* it must specify or *ArrayScriptObject &#42;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_array_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_array_script_object_out.txt[]
----

===== Parameter Object

To bind a ZetScript function that accepts a *xref:chapters/chapter_2_the_language_data_types.adoc#_boolean[Object]* it must specify *ObjectScriptObject &#42;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_object_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_object_script_object_out.txt[]
----


===== Parameter registered type

To bind a ZetScript function that accepts a <<registered type,Register type>> it must specify the C++ pointer type as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_registered_type.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_registered_type_out.txt[]
----

