=== Call ZetScript from c++

To make a ZetScript function callable from C&plus;&plus; is done through `ZetScript::bindScriptFunction`. `ZetScript::bindScriptFunction` it binds ZetScript function by setting function signature and the name of symbol or ScriptFunction to be binded of.

As a signature parameters, it can define untill 9 parameters as <<ZetScript built-in type>> or other registered type. 

As a signature return, the function it can return nothing, or a <<ZetScript built-in type>> or other registered type.

*Syntax*

[source,c++]
----
 ZetScript::bindScriptFunction<ReturnType(ParamType1, ParamType2, ..., ParamType9)>(_script_function);
----

+++<u>Parameters</u>+++

 - _ReturnType_: It can be void or some type defined in <<ZetScript built-in types>> or other registered type.
 - _ParamTypeX_: It can be one defined in <<ZetScript built-in types>> or other registered type.
 - __script_function_: `ZetScript::zs_string` or `ScriptFunction *` as the name or the script function reference to be binded.


+++<u>Returns</u>+++

Returns a `std::function` with the signature provided in its template signature

*Example*

The following example it binds hello world function without no parameters and no return

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_out.txt[]
----

==== Return types

This section will explain how to bind script functions that return the following types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- instantiated type

===== Return Boolean

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Boolean]* it must specify *bool* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_bool.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_bool_out.txt[]
----

===== Return Integer

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_integer[Integer]* it must specify *zs_int* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_int.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_int_out.txt[]
----

===== Return Float

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_float[Float]* it must specify *zs_float* return type on its function signature.


*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_float.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_float_out.txt[]
----


===== Return String

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_string[String]* it can be done by specifying the following return types in its function signature,

 - const char *
 - zs_string
 - StringScriptObject *

====== Return String as const char *

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_string[String]* it can specify *const char &ast;* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_const_char.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_const_char_out.txt[]
----

====== Return String as zs_string

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_string[String]* it can specify *zs_string* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_string.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_string_out.txt[]
----


====== Return String as StringScriptObject *

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_string[String]* it can specify *StringScriptObject &ast;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_string_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_string_script_object_out.txt[]
----

===== Return Array

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_array[Array]* it must specify *ArrayScriptObject &ast;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.


*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_array_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_array_script_object_out.txt[]
----


===== Return Object

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_object[Object]* it must specify *ObjectScriptObject &ast;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_object_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_object_script_object_out.txt[]
----

===== Return ZetScript class type

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_script_class[Class]* type it can specify *ObjectScriptObject &ast;* or *ClassScriptObject &ast;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_class_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_class_script_object_out.txt[]
----

===== Return registered type

To bind a ZetScript function that returns *xref:chapter_3_the_api.adoc#_registered_type[Registered Type]* type it must specify *ClassScriptObject &ast;* return type on its function signature. After returning ZetScript class script object, it can fetch its C++ registered type by calling "ClassScriptObject::to<_T *>", where _T is the C&plus;&plus; type.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

In this example, it registers `Point` type, its constructor and its properties `x` and `y`. After evaluate ZetScript code that defines a function that return a new object type `Point`, it is binded to be callable in C++.  When it calls `returnPoint`in C&plus;&plus;, it returns a variable as type ZetScript *ClassScriptObject &ast;* object that it prints its contents. Later it gets the registered class reference and also it prints its contents.

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_registered_class.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_registered_class_out.txt[]
----

==== Parameter types


This section will explain how to bind script functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered class 

===== Parameter Boolean

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Boolean]* it must specify *bool &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_bool.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_bool_out.txt[]
----

===== Parameter Integer

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Integer]* it must specify *zs_int* or *zs_int &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_int.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_int_out.txt[]
----

===== Parameter Float

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Float]* it must specify or *zs_float &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_float.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_float_out.txt[]
----

===== Parameter String

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify the following types as a parameter on its function signature,

 - const char *
 - zs_string *
 - StringScriptObject *

===== Parameter String as const char *

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *const char &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_const_char.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_const_char_out.txt[]
----

===== Parameter String as zs_string *

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *zs_string &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_string.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_string_out.txt[]
----


===== Parameter String as StringScriptObject *

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *StringScriptObject &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_string_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_string_script_object_out.txt[]
----

===== Parameter Array

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Array]* it must specify or *ArrayScriptObject &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_array_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_array_script_object_out.txt[]
----

===== Parameter Object

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Object]* it must specify *ObjectScriptObject &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_object_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_object_script_object_out.txt[]
----


===== Parameter registered type

To bind a ZetScript function that accepts a <<registered type,Register type>> it must specify the C++ pointer type as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_registered_type.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_registered_type_out.txt[]
----

