:source-highlighter: highlight.js
:highlightjs-languages: cpp, javascript
:sectnums:
:stylesheet: /home/jespada/zetdev/zetscript/doc/zetscript-manual-reference.css

== The language

=== Statments

ZetScript Language is based on a set of statements formed by values, operators, expressions, keywords, declarations, expressions, conditionals, integrators and functions. All statements are separated by semicolons at the end.

Example of four statements,

[source,javascript]
----
var op1,op2,res;
op1 = 5;
op2 = 6;
res = 5+6;
----

The last example can be executed within one line,

[source,javascript]
----
var op1,op2,res; op1=5; op2=6; res = 5+6;
----

=== Comments

ZetScript support block and line comments.

==== Block comment

[source,javascript]
----
/*
this is a block comment
*/
----

==== Line comment

[source,javascript]
----
// This is a line comment
----

=== Literals

ZetScript supports the following literals,

* Boolean
* Integer
* Float
* String

==== Boolean

Boolean literals is represented as true or false.

Example,

[source,javascript]
----
true // true value
false // false value
----

==== Integer

Integer literals are represented as integer with range from -(2b-1) to 2b-1-1 where b=32 or 64 it depending whether ZetScript is compiled for 32bits or 64bits. The integer value can be represented as decimal value, hexadecimal,binary or char format.

Example,

[source,javascript]
----
10; // decimal value
0x1a; // hexadecimal value
11010b; // 0x1a as binary value
'b'; // char value
----

Integer literlas supports the following pre operators,

[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Example

|Negate
|-integer 
|Negated value
|
[source,javascript]
 -10
 
|Bitwise complement
|~integer 
|Invert all bits
|
[source,javascript]
~011010b // (-27)
|====

==== Float

Float literals are represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits. Float can be represented in decimal form or scientific notation form.

Example,

[source,javascript]
----
1.2 // decimal form
2.0e-2 // cientific notation form
----

Float literals supports the following pre operators,

[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Example

|Negate
|-float
|Negated value
|
[source,javascript]
 -10.5

|====

==== String

String literal is represented as string within quotes (").

Example,

[source,javascript]
----
"this is a string"
----

=== Variables and constants

==== Variable

A variable is a kind of element that can hold a variable. Because ZetScript variables are _dynamically typed_, it can hold different type of values on its lifetime. A variable is declared as *var* and, by default, is initialized as *undefined* value (see 2.5.1). 

[source,javascript]
----
var i; // Declared variable 'i' with no inicialization (undefined value).
----

A variable can be initialized with a proper type value through '=' operator. The follow example initializes a variable with integer value
(see section 2.2),

[source,javascript]
----
var i=10; // Declared variable 'i' and initialized as integer value.
----

==== Constant

A constant is a kind of element where its value is immutable on its in lifetime. A constant is declared as *const* and is mandatory to be initialized.

[source,javascript]
----
const NUM_ITEMS=10; // constant 'NUM_ITEMS' with value 10.
----

==== Scope

In ZetScript we have two types of basic scopes.

* Global
* Local

A ZetScript makes easy the concept of global local scope. Basically, variables declared on the main script are global and the others declared within a [block footnote:[A block is a statement that starts with '{' and ends with '}']], are local.

Example,

[source,javascript]
----
// Declares *i* variable as global
var i;

// block starts here 
{	
	// Declare *j* variable as local (you can also access to i).
	var j;
}
// block ends here, so *j* variable doesn't exist anymore
----

=== Data types

ZetScript supports the following builtin data types,

* Undefined
* Null
* Integer
* Number
* Boolean
* String
* Vector
* Object
* Function

==== Undefined

Undefined data type it defines a non initialized variable. A variable is instanced as _Undefined_ once a its assings *undefined* value,

[source,javascript]
----
var a; // 'a' is undefined as default
var b=undefined; // assigns undefined value
----

==== Null

Null data type it defines an empty or not valid variable. A variable is instanced as _Null_ once a its assings *null* value,

[source,javascript]
----
var i=null;
----

==== Integer

Integer data type it defines a integer variable with range from -(2b-1) to 2b-1-1 where b=32 or 64 it depending whether ZetScript is compiled for 32bits or 64bits. A variable is initialized as _Integer_ once it assigns decimal, hexadecimal,binary or char value.

Example,

[source,javascript]
----
var a=10; // decimal value
var b=0x1a; // hexadecimal value
var c=01001b; // binary value
var d='b'; //  char value
----

===== Operators

Integer data operators are applied on integer variables before or after its read. Integer operators are the following,

[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Result

|Negate
|-variable 
|Negates its value
|
[source,javascript]
 var i=10;
 var j=-i; // j=-10
 
|Bitwise complement
|~variable 
|Invert all bits
|
[source,javascript]
 var i=00000011b;
 var j=~i; // j=11111100b or -4 decimal
|PreIncrement
|++variable 
|Increments FIRST and THEN evaluates
|
[source,javascript]
 var i=0;
 var j=++i; // j=1, i =1
 
|PostIncrement
|variable++ 
|Evaluates FIRST and THEN increments
| 
[source,javascript]
var i=0; 
var j=i++; // j=0; i=1

| Predecrement
| --variable 
|Decrements FIRST and THEN evaluates
| 
[source,javascript]
var i=0; 
var j=--i; // j=-1; i=-1

|Postdecrement
|variable--
|Evaluates FIRST and THEN decrements
|[source,javascript] 
var i=0; 
var j=i--;//j=0;i=-1;
|====

===== Static functions

====== Integer::parse

Converts Float or String to Integer value

[discrete]

[discrete]
====== Syntax

[source,javascript]
----
Integer::parse(_value)
----

*Parameters*

- __value_ : String or Float value

*Returns*

Integer parsed from the given value

[discrete]
====== Example

[source,javascript]
----
include::../examples/the_language/integer/integer_parse.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/integer/integer_parse_out.txt[]
----

==== Float

Float type it defines a float variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits. A variable is initialized as _float_ once it assigns a decimal or scientific value notation forms.

Example,

[source,javascript]
----
var a=1.2 // decimal form value
var b=2.0e-2 // cientific notation form value
----


===== Operators

Float operators are applied on float variables before or after its read. Float operators are the following,


[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Result
|Negate
|-variable 
|Evaluates negated variable
|
[source,javascript]
 var i=10.5;
 var j=-i; // j=-10.5

|PreIncrement 
|++variable 
|Increments FIRST and THEN evaluates
|
[source,javascript]
var i=0.5;
var j=++i; // j=1.5, i =1.5

|PostIncrement 
|variable++ 
|Evaluates FIRST and THEN increments
|
[source,javascript]
var i=0.5;
var j=i++; // j=0.5; i=1.5

|Predecrement 
|--variable 
|Decrements FIRST and THEN evaluates
|
[source,javascript]
var i=0.5;
var j=--i; // j=-0.5; i=-0.5

|Postdecrement 
|variable-- 
|Evaluates FIRST and THEN decrements
|
[source,javascript]
var i=0.5;
var j=i--;//j=0.5;i=-0.5;
|====

===== Static functions

====== Float::parse(_value)

Converts Integer or String to Float value

*Parameters*

- __value_ : String or Integer value

*Returns*

Float as parsed from given value

*Example*

[source,javascript]
----
include::../examples/the_language/float/float_parse.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/float/float_parse_out.txt[]
----

==== Boolean

Boolean type it defines a boolean variable represented as _true_ or _false_. A variable is initialized as _Boolean_ once it assigns a boolean value.

Example,

[source,javascript]
----
var b=false;
----

==== String

String type it defines a string type represented as a sequence of chars. A variable is initialized as _String_ once it assigns a string value.

*Example*

[source,javascript]
----
var s="this is a string";
----

===== Properties
 
====== String::length

Returns the length of the string

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_length.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_length_out.txt[]
----

===== Static functions
 
====== String::format(_string,..._args)

Formats a String from a String with a serie of args. The input String has curly brackets (i.e {} ) that specify the argument and/or its format. The description of possible formats are defined below,


[cols="1m,3d"]
|====
|Format |description
|{n}
|It replaces {_n_} by the argument _n_
|{n:dm}
|It replaces the argument _n_ padding _m_ 0s on its left
|{n,m}
|It replaces argument _n_ padding _m_ spaces on its left
|====

*Parameters*

- __string_ : String representation with specified arguments and/or its format

- __args_ : variable args to be replaced in the string representation

*Returns*

A formated string

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_format.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/string/string_format_out.txt[]
----

===== Member functions

====== String::insertAt(_position,_value)

Inserts string or integer value into String variable at defined position

*Parameters*

- __position_: Position where to insert. The position ranges within 0 to the length-1 of the String
- __value_: Integer or String value

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_insert_at.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_insert_at_out.txt[]
----

====== String::eraseAt(_position)

Removes the value at defined position

*Parameters*

- __position_:  The position where there's the value to remove. The position ranges within 0 to the length-1 of the String

*Return* 

None

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_erase_at.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_erase_at_out.txt[]
----

====== String::toUpperCase()

Returns the calling string value converted to uppercase

*Parameters*

None

*Returns*

An string value converted to uppercase

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_to_upper_case.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_to_upper_case_out.txt[]
----

====== String::toLowerCase()

Returns the calling string value converted to lowercase

*Parameters*

None

*Return* 

A string value converted to lowercase

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_to_lower_case.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_to_lower_case_out.txt[]
----

====== String::clear()

Erases the contents of the string

*Parameters*

None

*Return*

None 

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_clear.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/string/string_clear_out.txt[]
----


====== String::replace(_old_string, _new_string)

Returns a string replaced by a replacement 

*Parameters*

- __old_string_: The old string to be replaced 
- __new_string_: The new string to be replaced

*Return* 

A string where the specified values has been replaced

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_replace.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/string/string_replace_out.txt[]
----

====== String::split(_separator)

Splits the string into a vector of strings using a separator

*Parameters*

- __separator_ : separator value

*Return* 

A vector of strings 

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_split.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_split_out.txt[]
----

====== String::contains(_value)

Tells whether a value is contained in the string or not

*Parameters*

- __value_: a value to find

*Return*

A boolean value telling if the value exist or not in the string 

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_contains.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/string/string_contains_out.txt[]
----

====== String::indexOf(_search_value)

Returns the position of the first occurrence of a value in a string

*Parameters*

- __search_value_ : string to search for

*Returns* 

- A value >= 0 indicating the position of the first occurrence found
- -1 if the value is not present.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_index_of.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_index_of_out.txt[]
----

====== String::startsWith(_value)

Checks whether a string starts with the specified string passed by value

*Parameters*

- __value_ :  A string representing the value to check for

*Returns* 

A boolean value telling whether the string starts with the specified value or not

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_starts_with.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_starts_with_out.txt[]
----

====== String::endsWith(_value)

Checks whether a string ends with the specified string passed by value

*Parameters*

- __value_ :  A string representing the value to check for

*Returns* 

A Boolean value telling whether the string ends with the specified string or not

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_ends_with.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_ends_with_out.txt[]
----

====== String::substring(_start_index, _end_index)

Returns a substring of the string value from string within a the start and end indexes

*Parameters*

- __start_index_: The index of the first character to include in the returned substring.
- __end_index_ (optional): The index of the first character to exclude from the returned substring.

*Returns*

A string containing the specified part of the given string.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_substring.zs[]
----

Ouput:

[source,txt]
----
include::../examples/the_language/string/string_substring_out.txt[]
----

====== String::append(_value)

Extends the string by appending additional value at the end of its current string.

*Parameters*

- __value__ : value to be appended

*Returns* 

None

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_append.zs[]
----

Output

[source,text]
----
include::../examples/the_language/string/string_append_out.txt[]
----


==== Vector

Vector type it defines a container type that stores values in a unidimensional array. A variable is initialized as _Vector_ once it assings a open/closed square brackets (i.e '[]' ), 

Example,

[source,javascript]
----
[]; // a vector
----

Variable instanced as _Vector_ can also have initialized with a sequence of elements separated with coma (i.e ',') within square brackets,

Example,

[source,javascript]
----
[1,"string",true,2.0]; // A vector with elements
----

To access element vector is done through integer as a index.

Example,

[source,javascript]
----
var v=[1,"string",true,2.0]; // variable 'v' has 4 elements where its access exist in [0..3]
v[1]; // It access vector's second element (i.e "string")
----

===== Properties

====== Vector::length

Returns the number of elements in the vector

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_length.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_length_out.txt[]
----

===== Properties

====== Vector::concat(_v1, _v2)

Creates a new vector as a result of merge all elements from two vectors

*Parameters*

- __v1_ : First vector to concatenate into the new vector
- __v2_ : Second vector to concatenate into the new vector

*Returns* 

A new vector as a result of merge all elements from the vectors

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_concat.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_concat_out.txt[]
----


===== Member functions

====== Vector::push(_value)

Adds a new element at the end of the vector

*Parameters*

- __value__ : value to be added

*Returns* 

None

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_push.zs[]
----

Output

[source,text]
----
include::../examples/the_language/vector/vector_push_out.txt[]
----

====== Vector::pop()

Removes the last element in the vector

*Parameters*

None

*Returns* 

Last value of the vector before be removed

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_pop.zs[]
----

Output

[source,text]
----
include::../examples/the_language/vector/vector_pop_out.txt[]
----

====== Vector::insertAt(_pos,_value)

Inserts element in the vector at defined position

*Parameters*

- __position_: Position where to insert. The position ranges within 0 to the length-1 of the vector
- __value_: value to insert

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_insert_at.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_insert_at_out.txt[]
----

====== Vector::eraseAt(_pos)

Removes the value at defined position

*Parameters*

- __position_:  The position where there's the value to remove. The position ranges within 0 to the length-1 of the vector

*Return* 

None

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_erase_at.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_erase_at_out.txt[]
----

====== Vector::clear()

Clears all elements in the vector

*Parameters*

None

*Returns*

None 

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_clear.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/vector/vector_clear_out.txt[]
----

====== Vector::join(_separator)

Concatenates all elements of the vector into a string using a separator

*Parameters*

- __separator_ : separator value

*Return* 

A string of all concatenated vector's elements 

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_join.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_join_out.txt[]
----

====== Vector::contains(_value)

Tells whether a value is contained in the vector or not

*Parameters*

- __value_: a value to find

*Return*

A boolean value telling if the value exist or not in the vector 

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_contains.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/vector/vector_contains_out.txt[]
----

====== Vector::extend(_v)

Extends the calling vector by appending all elements from a vector

*Parameters*

- __v_ : Vector type which all elements will appended into the vector

*Returns* 

None

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_extend.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_extend_out.txt[]
----


===== Object

Object type is a anonymous container type to store values through attributes. A variable is initialized as _Object_ once it assings a open/closed of curly brackets (i.e '{}'),

[source,javascript]
----
{}; // Object
----

Optionally we can init with some values with its attributes,

[source,javascript]
----
{
  i:1
 ,s:"string"
 ,b:true
 ,f:2.0
};
----

To acces to its elements is done through the variable name followed by '.' and attribute name or attribute name as string within brackets (i.e ["attribute_name"] ),

[source,javascript]
----

var o={
  i:1
 ,s:"string"
 ,b:true
 ,f:2.0
};

o.i; // get contens of attribute 'i' by '.'
o["i"]; // gets the contents of attribute 'i' by '[]'
----

===== Static functions

====== Object::clear(_o)

Clears all elements of an object

*Parameters*

None

*Returns*

None 

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_clear.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/object/object_clear_out.txt[]
----

====== Object::erase(_key_id)

Removes an attribute of an object

*Parameters*

- __key_id_:  The key id of the attribute to remove

*Return* 

None

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_erase.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_erase_out.txt[]
----

====== Object::contains(_key_id)

Tells whether a key is contained in an object or not

*Parameters*

- __key_: a key to find

*Return*

A boolean value telling if the attribute with __key_id_ exist or not in the object 

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_contains.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/object/object_contains_out.txt[]
----

====== Object::extend(_o1,_o2)

Extends an object by the content of other object

*Parameters*

- __o1_ : Object where to be extended
- __o2_ : Object where to copy the extension

*Returns* 

None

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_extend.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_extend_out.txt[]
----

====== Object::concat(_o1, _o2)

Creates a new object as a result of merge all elements from two objects

*Parameters*

- __o1_ : First object to concatenate into the new object
- __o2_ : Second object to concatenate into the new object

*Returns* 

A new object as a result of merge all elements from the two objects

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_concat.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_concat_out.txt[]
----

====== Object::keys(_o)

Returns a vector of string representing its key names

Parameters

''''

The text [.overline]#overline me# is underlined.

Type the word [.userinput]#asciidoctor# into the search bar.

The __kernel qualifier can be used with the __attribute__ keyword...

#`CB###2`# and #`CB###3`#


- __o_ : Object

*Returns* 

Returns a vector of string representing its key names

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_keys.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_keys_out.txt[]
----


==== Function

Function type is a anonymous function object to be assigned. A variable is initialized as _Function_ once it assings an anonymous function (see section X.XX)

Example,

[source,javascript]
----
var f=function(){
	Console::outln("Call from function object")
};

f(); // it prints "Call from function object"
----


=== Operators

ZetScript has the following type of operators

* Arithmetic operators
* Relational operators
* Logical operators
* Bit operators

==== Arithmetic operators

Arithmetic operators performs arithmetic operations between two values. The arithmetic operators are the following,

[cols="2d,1m,3d,6a"]
|====
|Operator |Symbol |Description |Example
|Add 
|+
a|

It performs a these operations:

* Add operation between two integer or float values 
* Concatenates between two strings or other values
* Concatenates between two vectors 
* Concatenates between two objects 

|
[source,javascript]
----
 5+10; // = 15
 1.5+6;// = 7.5
 "string_"+"string";// ="string_string"
 "string_"+1;// ="string_1"
 [1]+[2,3];// [1,2,3]
 {a:1}+{b:2,c:3}; //{a:1,b:2,c:3}
----

|Subtract
|-
|Performs a substract operation between two integer/float values
|
[source,javascript]
10-5; // = 5
2.5-1;// = 1.5

|Multiply 
|* 
|Performs a multiplication between two integer/float values
|
[source,javascript]
10*5; //= 50
1.5*2;//= 3.0

|Divide 
|/ 
|Performs a division between two integer/float values
|
[source,javascript]
10/2; // = 5
3/2.0 // = 1.5

|Modulus 
|% 
|Performs a division between two integer/float values
|
[source,javascript]
3%2; //it results 1
10%2.5; // it results
|====

==== Relational operators

Relational operators evaluates relations through two values. The relational operators are the following,

[cols="2d,1m,3d,6a"]
|====
|Operator |symbol |Description |Example

|Equal 
|==
|Check whether two values are equal
|
[source,javascript]
 10==10;// = true
"hello"=="bye"; // = false

|Not equal 
|!= 
|Check whether two values are not equal
|
[source,javascript]
10!=10; // = false
"hello"!="bye"; // = true

|Less than 
|< 
|Checks whether first value is less than second value
|
[source,javascript]
10<20; // = true
20<10; // = false

|Greater than 
|> 
|Checks whether first value is greater than second value
|
[source,javascript]
10>20; // = false
20>10; // = true

|Less equal than 
| \<= 
|Checks whether first value is less equal than second value
|
[source,javascript]
10<=10; //= true
11<=10; // = false

|Greater equal than 
|>= 
|Checks whether first value is greater equal than second value
|
[source,javascript]
10>=11; // = false
11>=10; // = true

|Instance of 
|instanceof 
|Checks if a value is instance of a type. 
|
[source,javascript]
0 instanceof Integer; //= true
"hello" instanceof Integer;//= false

|in 
|in 
a|
Performs the following operations:

* Checks if a value exist in a string or vector
* Checks a key exist in object
|
[source,javascript]
'a' in "abc" // true
'd' in "abc" // false
"string" in [1,"string",false,10.5] // true
10       in [1,"string",false,10.5] // false
"a" in {a:1,b:2,c:3} // true
"d" in {a:1,b:2,c:3} // false


|====



==== Logic operators

Logic operators combines operations between two boolean values. The logic operators are the following,

[cols="2d,1m,3d,6a"]
|====
|Operator |symbol |Description |Example

|Logic And 
|&& 
|Performs an AND operation between two boolean values
|
[source,javascript]
true && true;// = true
true&& false;// = false

|Logic Or 
| \|\|
|Performs an OR operation between two Boolean values
|
[source,javascript]
true \|\| false;// = true
false \|\| false;// = false

|Logic Not 
|! 
|Negates boolean value
|
[source,javascript]
!true; // = false
!false; // = true
!(true || false) // = false 
!(true && false) // = true
|====

==== Binary operations

Binary operators combines operations between two integer values. The binary operators are the following,

[cols="2d,1m,3d,6a"]
|====
|Operator |symbol |Description |Example

|Binary And 
|& 
|Performs binary AND operation between two integers
|
[source,javascript]
0xa & 0x2; // = 0x2
0xff & 0xf0; // = 0xf0

|Binary Or
|\|
|Performs binary OR operation between two integers
|
[source,javascript]
0xa \| 0x5; // = 0xf
0x1 \| 0xe; // = 0xf

|Binary Xor 
|^ 
|Performs binary XOR between two integers
|
[source,javascript]
0xa ^ 0xa; // = 0x0
0xa ^ 0x5; // = 0xf

|Binary shift left
|<< 
|Performs binary shift left between two integers
|
[source,javascript]
0x1 << 2; // = 0x4

|Binary shift right
|>> 
|Performs binary shift right between two integers
|
[source,javascript]
0xff >> 1; // = 0x7f

|Bitwise complement
|~
|Performs bitwise complement operation from integer value
|
[source,javascript]
~0xa; // = 0x7f

|====

==== Priority operations
Each operator it has priority of evaluation. ZetScript it has the following operator order priority,

<<,>>,&,|,^,*,/,%,+,-,in,instanceof,==,!=,>=,\<=,>,<,&&,||

For example this expression,

[source,javascript]
----
2+4*5; // will result 22
----

You can change the evaluation priority usign parenthesis.

For example,

[source,javascript]
----
(2+4)*5; // will result 36
---- 

=== Conditionals

A conditional statement are used to perform different actions based on different conditions. In ZetScript we have the following conditional statement:

* Use if to specify a block of code to be executed, if a specified condition is true
* Use else to specify a block of code to be executed, if the same condition is false.
* Use ternary condition to have a short if/else statement into single statement.
* Use switch to specify manu alternative blocks of code to be executed

==== if-else statement

_If_ statement is used to specify a block of code to be executed if a condition is 'true'.

Syntax,

[source,javascript]
----
if(condition){
	//Block of code to be executed if the condition is true
}
----

*Example*


Output:

''''

It can use _else_ statement  is used to specify a block of code to be executed if the condition is 'false'.

Syntax,

[source,javascript]
----
if(condition) {
	// do something if condition is true
}else{
	// do something if condition is false
} 
----

*Example*

Output:

''''


Is also possible to concatenate a series of if-else statement to evaluate a serie of conditions.

Syntax,

[source,javascript]
----
if(condition 1) {
 	// do something if condition 1is true
}else if(condition 2){
	// do something if condition 2 is true
	
	...
	
}else if(condition n)
	// do something if condition n is true
}else{
	// do something if none of above conditions are true
}
----

*Example*


Output:

==== Ternary condition

Use ternary condition to have a short if/else statement into single statement. It performs expression if the condition is true or the second expression if the condition is 'false'.

Syntax,

[source,javascript]
----
result = (condition)?first expression:2nd expression;
----

Example,

[source,javascript]
----
var j = 0>1? 0:1; // j = 1
----

==== switch

Switch statement is used to select one of many blocks of code to be executed.

Syntax,

[source,javascript]
----
switch(expression) {
	case value_0:
		code block
		break;
	case value_1:
		code block
		break;
	 	...
		case value_n
		default:
		code block
		break;
}
----

Example,

[source,javascript]
----
----

Output:

Switch can have common code blocks in different conditions

Example,

[source,javascript]
----
----

Output:

[source,text]
----
----

=== Loops

ZetScript supports the following loop types,

* While Loop
* For Loop

==== while

The while loop loops through a block of code as long as a specified condition is true.

Syntax,

[source,javascript]
----
while(condition){
	// code block to be executed
}
----

*Example*

[source,javascript]
----
----

Output:

[source,text]
----
----

==== do-while

do-while loop is always be executed at least once, even if the condition is false, because the code block is executed before the condition is tested:

Syntax,

[source,javascript]
----
do{
	// do-while body
} while (condition);
----

Example,

[source,javascript]
----
----

Output:

[source,text]
----
----

==== for

The for loop performs an iteration with 3 optional statements:

Syntax,

[source,javascript]
----
for(stament1;statment2;statment3){
	// code block to be executed
}
----

* Statement 1 is executed before the loop (the code block) starts. Normally you will use statement 1 to initialize the variable used in the loop (for example var i = 0).
* Statement 2 defines the condition for running the loop.
* Statement 3 is executed each time after the code block has been executed.

Example,

[source,javascript]
----
for(var i=0; i < 5; i++) {
	print("The number is "+i);
} 
----


==== for-in

The loop for-in works as for loop but simplifies the iteration over containers like string, object or vectors. Per each iteration it can  evaluate a value or a pair key-value,

Example,

Syntax using value as iteration result value,

[source,javascript]
----
for(var v in vector){
	// code block to be executed
}
----

*Example*

Output:


Using a pair key-value as iteration result value,

[source,javascript]
----

for(var v in vector){
	// code block to be executed
}
----

*Example*

Output:



=== Functions

Function is a block of code to perform a particular task and is executed when in some part of the code it calls it.

==== Function syntax

A JavaScript function is defined with the function keyword, followed by a name, followed by parentheses ().

Syntax,

[source,javascript]
----
function fun_name(arg1, arg2, ..., argn){
	// code to be executed
}
----

Example,

[source,javascript]
----
function add(op1, op2){
	return op1+op2;
}
----

==== Call a function

The call of a function is done when in some part of the code it calls it as follow,

Syntax

[source,javascript]
----
fun_name(arg1, arg2, arg3,..., argN);
----

Note: If a function is called with less than N args the rest of arguments will remain undefined.

Example,

[source,javascript]
----

function add(op1,op2){
	return op1+op2;
}

var j=add(2,3); // calls add function. j=5
----

==== Function object

A function can be stored in variables through its reference,

[source,javascript]
----
function add(op1, op2){
	return op1+op2;
}

var fun_obj = add; // stored function add reference to fun_obj
var j=fun_obj(2,3);// calls fun_obj (aka add) function. J=5
----

Also is possible to create function objects,

Syntax

[source,javascript]
----
function(arg1, arg2, ..., argN){
	// code to be executed.
};
----

Example,

[source,javascript]
----
var add=function(op1, op2){
	return op1+op2;
};

var j=add(2,5); // j=5
----

==== Default parameters

Default function parameters allow named parameters to be initialized with default values if no value or undefined is passed.

[source,javascript]
----
function fun(arg1, arg2,arg2=default_arg){
	// ...
};
----

*Example*

Output:

==== Variable parameters

The rest parameter (...) allows a function to treat an indefinite number of arguments as an array

Syntax,

[source,javascript]
----
function var_args(...args) {
}
----

you can combine with other arguments but the array as variable parameter must be defined on the last one  

Syntax,

[source,javascript]
----
function var_args(op1, op2, ...args){
}

----


*Example*

[source,javascript]
----
include::../examples/the_language/function/function_variable_parameter.zs[]
----

Ouput:

[source,text]
----
include::../examples/the_language/function/function_variable_parameter_out.txt[]
----

==== Parameters by reference

In Pass by Reference, a function is called by directly passing the reference of the variable as the argument

*Example*

[source,javascript]
----
include::../examples/the_language/function/function_parameter_by_reference.zs[]
----

Ouput:

[source,text]
----
include::../examples/the_language/function/function_parameter_by_reference_out.txt[]
----


=== Class

A class is a custom type that contains variables and functions that operates with its variables. 

Example,

[source,javascript]
----
class Test{

};
----

A class is defined using keyword _class_ followed by the name. To access member variables and functions it uses _this_ keyword. 

Example,

[source,javascript]
----
class Test{

   member_function(){
        this.a=0; // member variable
        
        this.member_function


};
----

In a class we can find member functions (functions that affects to class variable) or static functions (helper function of generic purposes about the class type).



==== Members

Functions and variable members

bla bla bla

==== Instance class

To instance a class is done through the keyword new

Example,

[source,javascript]
var t = new Test(); // Instantiate t as Test type.

==== Accessing to class functions

To access class variables/functions is done through "." operator.

Example,

[source,javascript]
----
var i=t.function1(2); // initializes data1 as 2 and return the value
----

==== Constructor

Each time class is instanced, their member variables are undefined. var t = new Test(); // The a class Test is instanced but data1 and data2 are undefined.

[source,javascript]
print("data1:"+t.data1); //  prints: data1:undefined"

The constructor is a function that is invoked automatically and with aim to initialize all member variables. To the define a constructor we have to define a function member with same name as the Class.

Example,

[source,javascript]
----
class Test{
 	// Constructor function
	constructor(){
 		this.data1 =10; // instantiate data1 as integer
 	}
}
----

==== Post declare function member

Is possible to add more class member through "::" punctuator.

Example,

[source,javascript]
----
	
	// post declaration of function member
	function Test::function2(){
 		this.data2="a string";
	}
----

==== Inheritance

A class can inherit another class through "extends". The new extended class will inheritance all variable/functions members from base class.

Example,

[source,javascript]
----
class TestExtended extends Test{
	function3(){
		this.data3=this.data1+this.function1(10);
	}
};
----
===== Call parent functions

The extended class can call parent functions through _super_ keyword.

Example,

[source,javascript]
----
class TestExtended extends Test{
	function1(a){
 		var t=super(a); // it calls Test::function1(2)
 		this.data1+=t; // Now data1=5+2 = 7
 		return this.data1+a;
 	}
 	
 	function3(){
 		this.data3=this.data1+this.function1(5);
 	}
}; 
----

==== Metamethods
Metamethods are special functions members that links with operators seen on section section 3.6. ZetScript metamethods can be static or member function footnote:[ On script side, static function is defined as member function, but user should not access on variable/function members as well it happens on c++ static function.] depending whether the operation affects or not the object itself. 

===== _string()

Returns custom when string operation operation is invoved

*Parameters*
None

*Returns*
Custom string defined by user

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_to_string.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_to_string_out.txt[]
----



===== _set(_value)

Performs a set operation

*Parameters

- __value_ : value to set.

*Returns*
None.

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_set.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_set_out.txt[]
----

===== _equ(_op1,_op2)

Implements _equal_ operator (aka == ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- True if op1 and op2 are EQUAL
- False if op1 and op2 are NOT EQUAL

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_equ.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_equ_out.txt[]
----

===== _nequ(_op1,_op2)

Implements _not equal_ operator (aka != ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- True if op1 and op2 are NOT EQUAL
- False if op1 and op2 are EQUAL

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_nequ.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_nequ_out.txt[]
----

===== _lt(_op1,_op2)

Implements _less than_ operator (aka < ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- True if op1 is LESS THAN op2
- False if op1 is GRATHER EQUAL THAN op2

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_lt.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_lt_out.txt[]
----

===== _lte(_op1,_op2)

Implements _less than or equal_ operator (aka <= ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- True if op1 is LESS THAN OR EQUAL op2
- False if op1 is GRATHER THAN op2

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_lte.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_lte_out.txt[]
----

===== _gt(_op1,_op2) (aka >)

Implements _greather than_ operator (aka > ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- True if op1 is GREATHER THAN op2
- False if op1 is LESS OR EQUAL THAN op2

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_gt.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_gt_out.txt[]
----

===== _gte(_op1,_op2) (aka >=)

Implements _greather than or equal_ operator (aka >= ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- True if op1 is GREATHER THAN OR EQUAL op2
- False if op1 is LESS THAN op2

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_gte.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_gte_out.txt[]
----


===== _not()

Implements _not_ pre operator (aka !)  

*Parameters*

None

*Returns*

- Boolean value as a result of not operation

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_not.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_not_out.txt[]
----

===== _neg()

Implements _negate_ pre operator (aka - ) 

*Parameters*

None

*Returns*

- A new object as result of negate operation

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_negt.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_not_neg.txt[]
----
 

===== _add(_op1,_op2)

Implements _add_ operator (aka + ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of add operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_add.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_add_out.txt[]
----

===== _div(_op1,_op2)

Implements _division_ operator (aka / ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of division operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_div.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_div_out.txt[]
----


===== _mul(_op1,_op2)

Implements _multiplication_ operator (aka * ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of multiplication operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_mul.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_mul_out.txt[]
----

===== _mod(_op1,_op2)

Implements _modulus_ operator (aka * ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of modulus operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_mod.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_mul_out.txt[]
----

===== _and(_op1,_op2)

Implements _bitwise and_ operator (aka & ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of bitwise and operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_and.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_and_out.txt[]
----

===== _or(_op1,_op2)


Implements _bitwise or_ operator (aka | ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of bitwise or operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_or.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_or_out.txt[]
----

===== _xor(_op1,_op2)


Implements _bitwise xor_ operator (aka ^ ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of bitwise xor operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_xor.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_xor_out.txt[]
----
===== _shl(_op1,_op2)

Implements _bitwise shift left_ operator (aka << ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of bitwise shift left operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_shl.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_shl_out.txt[]
----


===== _shr (aka >>)


Implements _bitwise shift right_ operator (aka << ) between first operand and second operand 

*Parameters*

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

*Returns*

- A new object as a result of bitwise shift right operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_shr.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_shr_out.txt[]
----


==== Custom properties

A custom property is a member that defines a set of metamethods that to operate with.

_get
_set
_neg
_not
_post_inc
_post_dec
_pre_inc
_pre_dec


=== Modules

Zetscript implements the following modules,

* Console
* System
* Math
* Json
* DateTime


==== Console

Console module exposes the following set of functions,

* outln
* errorln
* readChar

===== Console::outln

Console::outln prints message to the console.

Syntax,

[source,zetscript]
Console::outln(object,...args)

If _object_ is constant string it can be formated (see in table X.X)

Example,

[source,zetscript]
----
 // prints 'Hello world'
 Console::outln("Hello world");
 
 // prints 'Score:0001'
 Console::outln("Score:{0:d4}",1);  
  
----

===== Console::errorln

Console::errorln prints an error message to the console.

Syntax,

[source,zetscript]
Console::errorln(object,...args)

If _object_ is constant string it can be formated (see in table X.X)

Example,

[source,zetscript]
----
 // prints 'Error'
 Console::errorln("Error");
 
 // prints 'Error:02'
 Console::outln("Error:{0:d2}",2);  
  
----

===== Console::readChar

Console::readChar it waits untill reads a character from console

Syntax,

[source,zetscript]
Console::readChar()

Example,

[source,zetscript]
----
 // waits until reads a char
 var c=Console::readChar();
 
 // prints readed char
 Console::outln("Key pressed: {0}",c) 
  
----


==== System

System module exposes the following set of functions,

* clock
* eval
* assert
* error


===== Clock

Returns the amount of time in milliseconds

Syntax,

[source,zetscript]
System::clock()

Example,

[source,zetscript]
----
 var start=System::clock()

 // waste some time...
 for(var i=0;i<1000; i++){
 }

 // print elapsed time in milliseconds
 Console::outln("Elapsed time: {0} ms",System::clock()-start_time)
----

===== Eval


===== Assert


===== Error




==== Math

Math module exposes the following set of static members,

* PI: PI number (i.e 3.14159265359)

Math module exposes the following set of static functions,

* sin
* cos
* abs
* pow
* degToRad
* random
* max
* min
* sqrt
* floor
* ceil
* round


===== Math::sin

===== Math::cos

===== Math::abs

===== Math::pow

===== Math::degToRad

===== Math::random

===== Math::max

===== Math::min

===== Math::sqrt

===== Math::floor

===== Math::ceil

===== Math::round


==== Json

Json exposes the following set of static members,

* serialize
* deserialize

===== Json::serialize

===== Json::serialize

==== DateTime

Json exposes the following set of member variables,

//-> maybe a table

* week_day (zs_int): The week's day
* month_day (zs_int): The month's day
* year_day (zs_int): The year's day

* second (zs_int): seconds
* minute (zs_int): minutes
* hour (zs_int): hours

* day (zs_int): day
* month (zs_int):month
* year (zs_int): year


Json exposes the following set of member functions,

* addSeconds
* addMinutes
* addHours
* addDays
* addMonths
* addYears

Json exposes the following set of member metamethods,

* _add
* _sub
* _toString

===== DateTime::addSeconds

===== DateTime::addMinutes

===== DateTime::addHours

===== DateTime::addDays

===== DateTime::addMonths

===== DateTime::addYears

===== DateTime::_add

===== DateTime::_sub

===== DateTime::_toString


