=== Call ZetScript from c++

To make a ZetScript function previosly evaluated callable from C&plus;&plus is done through `ZetScript::bindScriptFunction`. `ZetScript::bindScriptFunction` it binds ZetScript function by setting expected signature and the name of symbol or ScriptFunction to be binded of.

As a signature parameters, it can define untill 9 parameters as <<ZetScript built-in type>> or other registered type. 

As a signature return, the function it can return nothing, or a <<ZetScript built-in type>> or other registered type.

*Syntax*

[source,c++]
----
 ZetScript::bindScriptFunction<ReturnType(ParamType _arg1, ParamType _arg2, ..., ParamType _arg9 )>(_script_function);
----

+++<u>Parameters</u>+++

 - __script_function_: `ZetScript::zs_string` or `ScriptFunction *` as the name or the script function reference to be binded.

+++<u>Template signature</u>+++

 - _ReturnType_: It can be void or some type defined in <<ZetScript built-in types>> or other registered type.
 - _ParamType_: It can be one defined in <<ZetScript built-in types>> or other registered type.

+++<u>Returns</u>+++

Returns a `std::function` with the signature provided in its template signature

*Example*

The following example it binds hello world function without no parameters and no return

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_out.txt[]
----

==== Return types

This section will explain how to bind script functions that return the following types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Registered class 

===== Return Boolean

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Boolean]* it must specify *bool* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_bool.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_bool_out.txt[]
----

===== Return Integer

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Integer]* it must specify *zs_int* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_int.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_int_out.txt[]
----

===== Return Float

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Float]* it must specify *zs_float* return type on its function signature.


*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_float.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_float_out.txt[]
----


===== Return String

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can be done by specifying the following return types in its function signature,

 - const char *
 - zs_string
 - StringScriptObject *

====== Return String as const char *

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *const char &ast;* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_const_char.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_const_char_out.txt[]
----

====== Return String as zs_string

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *zs_string* return type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_string.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_string_out.txt[]
----


====== Return String as StringScriptObject *

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *StringScriptObject &ast;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_string_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_string_script_object_out.txt[]
----

===== Return Array

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Array]* it must specify *ArrayScriptObject &ast;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.


*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_array_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_array_script_object_out.txt[]
----


===== Return Object

To bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_object[Object]* it must specify *ObjectScriptObject &ast;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_object_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_object_script_object_out.txt[]
----

===== Return instanced class

In similar manner, to bind a ZetScript function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Object]* it must specify *ObjectScriptObject &ast;* return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling `ZetScript::unrefLifeTimeObject`.

To bind the ZetScript function that returns a <<ScriptClass>>, you must specify a registered class pointer as return type in the function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_class_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_class_script_object_out.txt[]
----

==== Parameter types


This section will explain how to bind script functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered class 

===== Parameter Boolean

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Boolean]* it must specify *bool &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_function/bind_function_param_bool.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_function/bind_function_param_bool_out.txt[]
----

===== Parameter Integer

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Integer]* it must specify *zs_int* or *zs_int &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_function/bind_function_param_zs_int.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_function/bind_function_param_zs_int_out.txt[]
----

===== Parameter Float

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Float]* it must specify or *zs_float &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_function/bind_function_param_zs_float.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_function/bind_function_param_zs_float_out.txt[]
----

===== Parameter String

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify the following types as a parameter on its function signature,

 - const char *
 - zs_string *
 - StringScriptObject *

===== Parameter String as const char *

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *const char &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_function/bind_function_param_const_char.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_function/bind_function_param_const_char_out.txt[]
----

===== Parameter String as zs_string *

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *zs_string &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_function/bind_function_param_zs_string.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_function/bind_function_param_zs_string_out.txt[]
----


===== Parameter String as StringScriptObject *

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify *StringScriptObject &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_function/bind_function_param_string_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_function/bind_function_param_string_script_object_out.txt[]
----

===== Parameter Array

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Array]* it must specify or *ArrayScriptObject &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_function/bind_function_param_array_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_function/bind_function_param_array_script_object_out.txt[]
----

===== Parameter Object

To bind a ZetScript function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Object]* it must specify or *ObjectScriptObject &ast;* as parameter type on its function signature.

*Example*

[source,c++]
----
include::../examples/the_api/bind_function/bind_function_param_object_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind_function/bind_function_param_object_script_object_out.txt[]
----

==== bind member function from instanced global object

It can also call from instanced object

[source,c++]
----
include::../examples/the_api/bind/bin_object_script_function.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/bind/bin_object_script_function_out.txt[]
----

==== Life time objects returned
//      zs_int,zs_float,bool
//      other times should bee freed. Show error if not freed

=== Bind function

To bind a function first it has to declare a function with a signature compatible to ZetScript. All signatures in a function binding interface have ZetScript pointer as first parameter, and the others are <<built-in types>> or types binded by the user. 

Example,

Parameters

ZetScript supports builtin *zs_int, zs_int *, zs_float *, bool *, char * and zs_string ** as arguments types or other types. 

Example,

Return

For return values it supports the same basic types as arguments plus *bool, zs_float and zs_string (no pointer)*. Is also possible to pass custom registered types (see section 4.3).

Example,

Is important to say that ZetScript has a constraint *maximum of 8 parameters* for any C function to be bind in the script engine. If a function more than 8 parameters is tried to be registered, ZetScript will throw an error. To bind C function is done through macro registerFunction. You have to provide the name that will be referenced in script side.

Syntax,

[source,cpp]
zs.registerFunction("function_name", c_function);

Example,

[source,cpp]
----
#include "ZetScript.h"

zetscript::zs_int add(zetscript::zs_int  op1, zetscript::zs_int op2)
{
	return op1+op2;
}

int main(int argc, char *argv[])
{
	zetscript::ZetScript zs;
	
	// binds native function "add"
	zs.registerFunction("add",add);
	
 	zs.eval(
 		"Console::outln(\"result:\"+add(5,4));" // prints "result: 9"
 	);
	 
 	return 0;
} 
---- 