=== Exposing C++ types to ZetScript

In this chapter will see how to to register C&plus;&plus; types, function members, metamethods and properties in order to be exposed in ZetScript.


==== Register a type

There's two ways to register a type,

- Register a non instantiable type 
- Register an instantiable type



==== Register a non instantiable type

To register a non instantiable type it means that it CANNOT create or instantiate new objects of that _type_ in ZetScript using the _new_ operator, so the object only can be acceded by reference returned by some registered function. This kind of register is usueful when it wants to have a control of instantiated objects in the native application.

To register a non instantible type it's done by simple calling `ZetScript::registerType` with type as template and the class name that will be referenced in the script.

*Syntax*
[source,cpp]
----
ScriptType * registerType<_Type>(const zs_string & _class_name);
----

+++<u>Template</u>+++ 

- _Type: C&plus;&plus; struct/class type

+++<u>Parameters</u>+++ 

- _class_name: Class name that will be referenced in ZetScript

+++<u>Returns</u>+++ 

A `ScriptType` object

*Example*

Let's define a 'Number' type in the file 'Number.h',

[source,cpp]
----
include::../examples/the_api/register_type/Number.h[]
----

Next, it register `Number` type as non instantiable,

[source,cpp]
----

#include "Number.h"
#include "zetscript.h"

using zetscript::ZetScript;

int main()
{
	zetscript::ZetScript zs;

	zs.registerType<Number>("Number");
	 	
 	// ...
 }
}
----

Now, let's suppose we want to instantiate a `Number` type by evaluating the following script code,

[source,cpp]
----
	// It throws an error that 'Number' is not instantiable
 	zs.eval(
 		"var number= new Number();"
 	);
----

The evaluation will fail with the following output,

 'Number' type is not object instanceable


The only way to operate with a 'Number' object non intanciable is by a reference returned by a registered function as it shows the following example,


[source,cpp]
----
include::../examples/the_api/register_type/register_non_instantiable_type.cpp[]
----
  
==== Register an instantiable type


To register an instantiable type it means that it CAN create new objects of that 'type' in ZetScript code using operator new.

To register instantiable type it's done also with registerType but, furthermore, it has to pass two additional parameters : A constructor function and destructor function.

*Syntax*
[source,cpp]
----
ScriptType * registerType<RegisteredType>(const zs_string & _class_name, RegisteredType * (*_new_native_instance)(ZetScript *_zs), void (*_delete_native_instance)(ZetScript *_zs, RegisteredType * _this));
----

+++<u>Template</u>+++ 

- __RegisteredType_: The registered type

+++<u>Parameters</u>+++ 

- __symbol_name_: Symbol name that will be referenced in ZetScript
- __new_native_instance_: A C function that creates an returns a new instance. This function has the following signature,

[source,cpp]
----
RegsiteredType * RegisteredType_new(ZetScript *_zs);
----

- __delete_native_instance_: A C function that deletes native instance. The function has the following signature,

[source,cpp]
----
void RegisteredType_delete(ZetScript *_zs, RegisteredType *_this);
----

+++<u>Returns</u>+++ 

A `ScriptType` object

*Example*

Following the example of registering the `Number` type and in order to compact the linees of code for the next examples of this section, it has been proposed to register and declare all functions in a file called `NumberZs.h`. So, inside `NumberZs.h` will be all the functions to be registered and the function `NumberZs_register` that will have the registering of those functions.

Let's start by defining _new_ and _delete_ functions,

[source,cpp]
----
Number *NumberZs_new(ZetScript *_zs){
	ZS_UNUSUED_PARAM(_zs);
	return new Number();
}

void NumberZs_delete(ZetScript *_zs,Number *_this){
	ZS_UNUSUED_PARAM(_zs);
	delete _this;
}
----

Then, in the `NumberZs_register` it registers `Number` type as instantiable passing  _new_ and _delete_ functions,


[source,cpp]
----
void NumberZs_register(ZetScript *_zs){

	_zs->registerType<Number>("Number",NumberZs_new,NumberZs_delete);
}
----

Finally, it defines the main file that it includes 'NumberZs.h', calls 'NumberZs_register',


[source,cpp]
----
include::../examples/the_api/register_type/register_instantiable_type.cpp[]
----

===== Register a constructor


To register a constructor function it has to create and register a C&plus;&plus; function with a particular prototype. In ZetScript, that function it acts as it seen in *xref:chapter_2_the_language_class.adoc#_constructor[ZetScript class constructor]*.

As parameters, the function must always include `zetscript::ZetScript *` as the FIRST parameter,the pointer of the registered type as SECOND parameter and a maximum of 8 parameters as <<ZetScript built-in type>> or other registered type. 

*Syntax*

[source,c++]
----
void RegisteredType_constructor(ZetScript *_zs, _RegisteredType *_this, ParamType *_arg1, ..., ParamType *_arg8 ){
	....
}
----

Where,

- _RegisteredType_: The C&plus;&plus; registered type
- _ParamType_: It can be one of defined in  <<ZetScript built-in types>> or other registered type.


After the constructor function is defined it has to be registered with `ZetScript::registerConstructor`. `registerConstructor` it has the following signature,


*Syntax*
[source,cpp]
----
void registerConstructor<RegisteredType>( Function _function);
----

+++<u>Template</u>+++ 

- _RegisteredType_: The registered type
- _Function_ : Function signature

+++<u>Parameters</u>+++ 

- __function_: C function reference to be registered


*Example*

In this example it defines two functions that accepts a Float value or Number type respectively in ZetScript,

[source,cpp]
----

//...

void NumberZs_constructor(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_constructor(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}
----

Next, each  ´NumberZs_constructor´ function is registered by `registerConstructor`,

[source,cpp]
----


void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_constructor));

	_zs->registerConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_constructor));
	//...

}
----

Finally, it shows an example of a script that instantiates object type "Number" passing a number to its constructor


[source,cpp]
----
include::../examples/the_api/register_type/register_instantiable_type_with_constructor.cpp[]
----


==== Register members

===== Register member function

To register a member function it has to create and register a C function with a particular prototype.

As parameters, the function must always include `zetscript::ZetScript *` as the FIRST parameter,the pointer of the registered type as SECOND parameter and a maximum of 8 parameters as <<ZetScript built-in type>> or other registered type. 

As a return, the function it can return nothing, or a <<ZetScript built-in type>> or other registered type.

*Syntax*

[source,c++]
----
ReturnType RegisteredType_memberFunction(ZetScript *_zs, _RegisteredType *_this, ParamType *_arg1, ..., ParamType *_arg8 ){
	....
}
----

Where,

- _RegisteredType_: The C&plus;&plus; registered type
- _ReturnType_: It can be `void` or some type defined in <<ZetScript built-in types>> or other registered 
- _ParamType_: It can be one of defined in  <<ZetScript built-in types>> or other registered type.


After the member function is defined it has to be registered with `ZetScript::registerMemberFunction`. `registerMemberFunction` it has the following signature,


*Syntax*
[source,c++]
----
void registerMemberFunction<RegisteredType>(const zs_string & _name, Function _function);
----

+++<u>Template</u>+++ 

- _RegisteredType_: The registered C&plus;&plus;type
- _Function_ : Function signature


+++<u>Parameters</u>+++ 

- __name_	: Member function name
- __function_: C function reference to be registered

*Example*

[source,cpp]
----

//...

void NumberZs_pow(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----


[source,c++]
----
include::../examples/the_api/register_type/register_member_function.cpp[]
----


===== Register static member function

To register a static member function it has to create and register a C function with a particular prototype.

As parameters, the function must always include `zetscript::ZetScript *` as the FIRST parameter and a maximum of 9 parameters as <<ZetScript built-in type>> or other registered type. 

As a return, the function it can return nothing, or a <<ZetScript built-in type>> or other registered type.

*Syntax*

[source,c++]
----
ReturnType RegisteredType_staticMemberFunction(ZetScript *_zs, ParamType *_arg1, ..., ParamType *_arg9 ){
	....
}
----

Where,

- _ReturnType_: It can be `void` or some type defined in <<ZetScript built-in types>> or other registered 
- _ParamType_: It can be one of defined in  <<ZetScript built-in types>> or other registered type.


After the constructor function is defined it has to be registered with `ZetScript::registerStaticMemberFunction`. `registerStaticMemberFunction` it has the following signature,


*Syntax*
[source,c++]
----
void registerStaticMemberFunction<RegisteredType>(const zs_string & _name, Function _function);
----

+++<u>Template</u>+++ 

- _RegisteredType_: The registered C&plus;&plus;type
- _Function_ : Function signature


+++<u>Parameters</u>+++ 

- __name_	: Member function name
- __function_: Member function C reference

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,cpp]
----
include::../examples/the_api/register_type/register_static_member_function.cpp[]
----


==== Register metamethods

===== Register member metamethods

====== _tostring()

Returns custom string when string operation operation is invoved

*Syntax*

[source,cpp]
----
zs_string RegisteredType_tostring(ZetScript * _zs, RegisteredType *_this);
----

+++<u>Parameters</u>+++

- __zs_ : ZetScript context
- __this_ : intance registered object


+++<u>Returns</u>+++

A string as a result when string operation operation is invoved

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,cpp]
----
include::../examples/the_api/register_type/register_member_metamethod_tostring.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_tostring_out.txt[]
----

===== _set()

Implements _assignment_ operator (aka = ) with a value entered by parameter as right operand.

*Syntax*

[source,c++]
----
void RegisteredType_set(ZetScript * _zs, RegisteredType *_this, ParamType * _value);
----

+++<u>Parameters</u>+++

- __zs_ : ZetScript context
- __this_ : The pointer instance of registered type
- __value_ : A value to be set from _ParamType_ pointer. _ParamType_ it can be one of defined in  <<ZetScript built-in types>> or other registered type.

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,c++]
----
include::../examples/the_api/register_type/register_member_metamethod_set.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_set_out.txt[]
----

===== _addset()

Implements _addition assignment_ operator (aka += ) with a value entered by parameter as right operand.

*Syntax*

[source,cpp]
----
void RegisteredType_addset(ZetScript *_zs, RegisteredType *_this,ParamType *_value);
----

+++<u>Parameters</u>+++

- __zs_ : ZetScript context
- __this_ : The pointer instance of registered type
- __value_ : A value to be added from _ParamType_ pointer. _ParamType_ it can be one of defined in  <<ZetScript built-in types>> or other registered type.

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_addset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_addset_out.txt[]
----

===== _subset()

Implements _substraction assignment_ operator (aka -= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_subset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_subset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_subset_out.txt[]
----

===== _mulset()

Implements _multiplication assignment_ operator (aka *= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_mulset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_mulset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_mulset_out.txt[]
----

===== _divset()

Implements _division assignment_ operator (aka /= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_divset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_divset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_divset_out.txt[]
----

===== _modset()

Implements _modulus assignment_ operator (aka %= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_modset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_modset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_modset_out.txt[]
----

===== _andset()

Implements _bitwise AND assignment_ operator (aka &= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_andset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_andset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_andset_out.txt[]
----

===== _orset()

Implements _bitwise OR assignment_ operator (aka |= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_andset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_orset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_orset_out.txt[]
----


===== _xorset()

Implements _bitwise XOR assignment_ operator (aka ^= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_xorset(_value)
----

+++<u>Parameters</u>+++

- __op1_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_xorset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_xorset_out.txt[]
----

===== _shrset()

Implements _bitwise SHIFT RIGHT assignment_ operator (aka >>= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_shrset(_value)
----

+++<u>Parameters</u>+++

- __op1_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_shrset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_shrset_out.txt[]
----

===== _shlset()

Implements _bitwise SHIFT LEFT assignment_ operator (aka <<= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_shrset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_shlset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_shlset_out.txt[]
----

===== _not()

Implements _not_ pre operator (aka !)  

*Syntax*

[source,javascript]
----
_not()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- Boolean value as a result of not operation

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_not.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_not_out.txt[]
----

===== _neg()

Implements _negate_ pre operator (aka -a ) 

*Syntax*

[source,javascript]
----
_neg()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- A new object as result of negate operation

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_neg.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_neg_out.txt[]
----

===== _postinc()


Implements _post increment_ operator (aka a++ ) 

*Syntax*

[source,javascript]
----
_postinc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_postinc.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_postinc_out.txt[]
----

===== _postdec()

Implements _post decrement_ operator (aka a-- ) 

*Syntax*

[source,javascript]
----
_postdec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_postdec.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_postdec_out.txt[]
----

===== _preinc()

Implements _pre increment_ operator (aka ++a ) 

*Syntax*

[source,javascript]
----
_preinc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_preinc.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_preinc_out.txt[]
----

===== _predec()

Implements _pre decrement_ operator (aka --a ) 

*Syntax*

[source,javascript]
----
_predec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_predec.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_predec_out.txt[]
----

===== _in()

Implements _in_ operator 

*Syntax*

[source,javascript]
----
_in(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as value to check whether exist or not in the containing class

+++<u>Returns</u>+++

Boolean telling whether the _value exist in or not

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_in.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_in_out.txt[]
----

===== Static functions

====== _equ()

Implements _equal_ operator (aka == ) between first operand and second operand

*Syntax*

[source,javascript]
----
_equ(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 and op2 are EQUAL
- False if op1 and op2 are NOT EQUAL

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,cpp]
----
include::../examples/the_api/register_type/register_member_metamethod_equ.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_equ_out.txt[]
----

===== _nequ()

Implements _not equal_ operator (aka != ) between first operand and second operand

*Syntax*

[source,javascript]
----
_nequ(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 and op2 are NOT EQUAL
- False if op1 and op2 are EQUAL

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_nequ.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_nequ_out.txt[]
----

===== _lt()

Implements _less than_ operator (aka < ) between first operand and second operand

*Syntax*

[source,javascript]
----
_lt(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is LESS THAN op2
- False if op1 is GRATHER EQUAL THAN op2

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_lt.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_lt_out.txt[]
----

===== _lte()

Implements _less than or equal_ operator (aka \<= ) between first operand and second operand

*Syntax*

[source,javascript]
----
_lte(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is LESS THAN OR EQUAL op2
- False if op1 is GRATHER THAN op2

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_lte.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_lte_out.txt[]
----

===== _gt()

Implements _greather than_ operator (aka > ) between first operand and second operand

*Syntax*

[source,javascript]
----
_gt(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is GREATHER THAN op2
- False if op1 is LESS OR EQUAL THAN op2

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_gt.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_gt_out.txt[]
----

===== _gte(_op1,_op2)

Implements _greather than or equal_ operator (aka &gt;= ) between first operand and second operand

*Syntax*

[source,javascript]
----
_gte(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is GREATHER THAN OR EQUAL op2
- False if op1 is LESS THAN op2

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_gte.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_gte_out.txt[]
----

===== _add()

Implements _add_ operator (aka + ) between first operand and second operand

*Syntax*

[source,javascript]
----
_add(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of add operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_add.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_add_out.txt[]
----

===== _div()

Implements _division_ operator (aka / ) between first operand and second operand

*Syntax*

[source,javascript]
----
_div(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of division operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_div.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_div_out.txt[]
----


===== _mul()

Implements _multiplication_ operator (aka * ) between first operand and second operand

*Syntax*

[source,javascript]
----
_mul(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of multiplication operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_mul.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_mul_out.txt[]
----

===== _mod()

Implements _modulus_ operator (aka * ) between first operand and second operand

*Syntax*

[source,javascript]
----
_mod(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of modulus operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_mod.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_mod_out.txt[]
----

===== _and()

Implements _bitwise and_ operator (aka & ) between first operand and second operand

*Syntax*

[source,javascript]
----
_and(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise and operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_and.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_and_out.txt[]
----

===== _or()

Implements _bitwise or_ operator (aka | ) between first operand and second operand

*Syntax*

[source,javascript]
----
_or(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise or operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_or.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_or_out.txt[]
----

===== _xor()

Implements _bitwise xor_ operator (aka ^ ) between first operand and second operand

*Syntax*

[source,javascript]
----
_xor(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise xor operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_xor.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_xor_out.txt[]
----
===== _shl()

Implements _bitwise shift left_ operator (aka << ) between first operand and second operand

*Syntax*

[source,javascript]
----
_shl(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise shift left operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_shl.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_shl_out.txt[]
----

===== _shr()

Implements _bitwise shift right_ operator (aka << ) between first operand and second operand

*Syntax*

[source,javascript]
----
_shr(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise shift right operation 

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_metamethod_shr.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_metamethod_shr_out.txt[]
----

 
==== Properties

explaing that to register properties you have to use

registerMemberProperty

*Syntax*

[source,javascript]
----
class Test{

	// property
	property{
			...
	}

}
----

==== Register property functions

===== _get()

__get_ returns the value of the property

*Syntax*

[source,javascript]
----
_get()
----

*Parameters

None

+++<u>Returns</u>+++

Returns the value of the property

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_get.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_get_out.txt[]
----

===== _set()

Implements _assignment_ operator (aka = ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ :Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_set.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_set_out.txt[]
----

===== _addset()

Implements _addition assignment_ operator (aka += ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_addset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_addset_out.txt[]
----


===== _subset()

Implements _substraction assignment_ operator (aka -= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

The following code declares and registers two functions that accepts ZetScript Float or Number,

[source,cpp]
----

//...

void NumberZs_value_subset(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value-=*_value;
}

void NumberZs_value_subset(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value-=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberPropertyMetamethod<Number>("value","_subset",static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_value_subset));

	_zs->registerMemberPropertyMetamethod<Number>("value","_subset",static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_value_subset));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_subset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_subset_out.txt[]
----

===== _mulset()

Implements _multiplication assignment_ operator (aka *= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_mulset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_mulset_out.txt[]
----

===== _divset()

Implements _division assignment_ operator (aka /= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_divset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_divset_out.txt[]
----

===== _modset()

Implements _modulus assignment_ operator (aka %= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_modset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_modset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_modset_out.txt[]
----

===== _andset()

Implements _bitwise AND assignment_ operator (aka &= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_andset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_andset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_andset_out.txt[]
----

===== _orset()

Implements _bitwise OR assignment_ operator (aka |= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_andset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_orset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_orset_out.txt[]
----


===== _xorset()

Implements _bitwise XOR assignment_ operator (aka ^= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_xorset(_value)
----

+++<u>Parameters</u>+++

- __op1_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_xorset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_xorset_out.txt[]
----

===== _shrset()

Implements _bitwise SHIFT RIGHT assignment_ operator (aka >>= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_shrset(_value)
----

+++<u>Parameters</u>+++

- __op1_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_shrset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_shrset_out.txt[]
----

===== _shlset()

Implements _bitwise SHIFT LEFT assignment_ operator (aka <<= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_shrset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_shlset.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_shlset_out.txt[]
----

===== _neg()

Implements _negate_ pre operator (aka -a ) 

*Syntax*

[source,javascript]
----
_neg()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- A the value as result of negate operation

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_neg.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_neg_out.txt[]
----

===== _postinc()


Implements _post_increment_ operator (aka a++ ) 

*Syntax*

[source,javascript]
----
_postinc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_postinc.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_postinc_out.txt[]
----

===== _postdec()

Implements _post_decrement_ operator (aka a-- ) 

*Syntax*

[source,javascript]
----
_postdec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_postdec.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_postdec_out.txt[]
----

===== _preinc()

Implements _pre_increment_ operator (aka ++a ) 

*Syntax*

[source,javascript]
----
_preinc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_preinc.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_preinc_out.txt[]
----

===== _predec()

Implements _pre_decrement_ operator (aka --a ) 

*Syntax*

[source,javascript]
----
_predec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,cpp]
----

//...

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,zetscript::zs_float *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=*_value;
}

void NumberZs_set(zetscript::ZetScript *_zs,Number *_this,Number *_value){
	ZS_UNUSUED_PARAM(_zs);
	_this->value=_value->value;
}

//...

void NumberZs_register(zetscript::ZetScript *_zs){

	//...
	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, zetscript::zs_float *_value)>(&NumberZs_set));

	_zs->registerMemberConstructor<Number>(static_cast<void (*)(zetscript::ZetScript *_zs,Number *_this, Number *_value)>(&NumberZs_set));
	//...

}
----

[source,javascript]
----
include::../examples/the_api/register_type/register_member_property_metamethod_predec.cpp[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_member_property_metamethod_predec_out.txt[]
----






