
=== Call C++ from ZetScript

To call &#43;&#43; code from _ZetScript_ it has to create and register a C function with a particular prototype. That C function acts as interface between ZetScript and &#43;&#43;. 

As parameters, the function must always include `zetscript::ZetScript *` as the first parameter and a maximum of 9 parameters as <<ZetScript built-in type>> or other registered type. 

As a return, the function it can return nothing, or a <<ZetScript built-in type>> or other registered type.

*Syntax*

[source,c++]
----
ReturnType zetscriptCppInterface(ZetScript *_zs, ParamType _arg1, ParamType _arg2, ..., ParamType _arg9 ){
	....
}
----

Where,

- _ReturnType_: It can be `void` or some type defined in <<ZetScript built-in types>> or other registered type.
- _ParamType_: It can be one defined in  <<ZetScript built-in types>> or other registered type.


After the function is created it has be registered with ZetScript::registerFunction in order to be exposed in ZetScript. As a parameters, it passes a string value that will be the symbol name to be refered later in ZetScript and the C function reference.

*Syntax*

[source,c++]
----
template <typename F>
void registerFunction( const zs_string & _name_script_function,F _ptr_function);
----

Example, 

 ZetScript zs;
 zs.registerFunction("zetscriptCppInterface",zetscriptCppInterface)


*Example*

The following example registers a C function and calls it within an evaluated script.

[source,c++]
----
include::../examples/the_api/register_function/register_function.cpp[]
----


Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_out.txt[]
----

==== Return types

This section will explain how to register C functions that return the following types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Registered class 

===== Return Boolean

To register a C function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Boolean]* it must specify *bool* return type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_bool.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_bool_out.txt[]
----


===== Return Integer

To register a C function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Integer]* it must specify *zs_int* return type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_int.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_int_out.txt[]
----

===== Return Float

To register a C function that returns a *xref:chapter_2_the_language_data_types.adoc#_boolean[Float]* it must specify *zs_float* return type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_float.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_float_out.txt[]
----

===== Return a String

To register a C function that returns a *xref:chapter_2_the_language_data_types.adoc#&lowbar;string[String]* it can be done by specifying the following return types in its prototype,

- _zs_string_
- _StringScriptObject *_


====== Return String as zs_string

To register a C function that returns a *xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]* it can specify *zs_string* return type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_string.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_string_out.txt[]
----

====== Return String as StringScriptObject &#42;

To register a C function that returns a *xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]* it can specify *StringScriptObject &#42;* return type on its function prototype. The instantiation of *StringScriptObject &#42;* it&#39;s done throught _ZetScript::newStringScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_string_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_string_script_object_out.txt[]
----

===== Return Array

To register a C function that returns a *xref:chapter_2_the_language_data_types.adoc#lowbar;array[Array]* it must specify *ArrayScriptObject &#42;* return type on its function prototype. The instantiation of *ArrayScriptObject &#42;* it's done through _ZetScript::newArrayScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_array_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_array_script_object_out.txt[]
----

===== Return Object

To register a C function that returns a *xref:chapter_2_the_language_data_types.adoc#lowbar;object[Object]* it must specify *ObjectScriptObject &#42;* return type on its function prototype. The instantiation of *ObjectScriptObject &#42;* it's done through _ZetScript::newObjectScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_object_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_object_script_object_out.txt[]
----


===== Return registered class


To register a C function that returns a *<<Registered Class>>* it can be done by specifying the following return types in its prototype,

- Its native pointer type
- ClassScriptObject

 
===== Return registered class as its native pointer type

To register a C function that returns a *<<Registered Class>>* it can specify its native pointer type as return in the function prototype.

ZetScript *never* destroy native pointers returned from C function. This is why it cannot allocate and return a type from the function itself because this would become a memory leak . Instead, the pointer should be take from a location that is active during the execution of the script that involves the operation of the returned pointer.

*Example*

In the following example it registers type `Point` and its properties `x` and `y` and it registers native function `returnPoint` that returns a `Point` a type pointer. In the main program it creates a `Point` type and that is acceded globally, so the registered native function can access and return this instanced `Point` type.


[source,c++]
----
include::../examples/the_api/register_function/register_function_return_registered_type.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_registered_type_out.txt[]
----

===== Return registered class as ClassScriptObject

To register a C function that returns a *<<Registered Class>>* it can specify *ClassScriptObject &#42;* return type on its function prototype. To instantiate *ClassScriptObject &#42;*  is done through _<<ZetScript::newClassScriptObject>>_ using ZetScript context and the registered class instantiated.

A difference from returning a pointer type of a registered class, when the C function returns a *ClassScriptObject &#42;* object ZetScript is in charge to deallocate automatically when there's no more references. 

To be have the class wrappable inside *ClassScriptObject &#42;*, it must be registered as instancialbe (see <<Register class as instanciable>>)

*Example*

In the following example it registers a native type `Point` and its properties `x` and `y` and it registers native function `returnPoint` that instances and returns a `ClassScriptObject` as `Point` type. 

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_class_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_class_script_object_out.txt[]
----

==== Parameter types


This section will explain how to register C functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered class 

===== Parameter Boolean

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[Boolean]* it must specify *bool* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_bool.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_bool_out.txt[]
----

===== Parameter Integer

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#lowbar;integer[Integer]* it must specify *zs_int* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_int.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_int_out.txt[]
----

===== Parameter Float

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#lowbar;float[Float]* it must specify *zs_float* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_float.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_float_out.txt[]
----

===== Parameter String

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#_boolean[String]* it can specify the following types as a parameter on its function prototype,

- const char *
- zs_string *
- StringScriptObject *

===== Parameter String as const char *

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]* it can specify *const char &#42;* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_const_char.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_const_char_out.txt[]
----

===== Parameter String as zs_string *

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]* it can specify *zs_string &#42;* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_string.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_string_out.txt[]
----

===== Parameter String as StringScriptObject *

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]* it can specify *StringScriptObject &#42;* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_string_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_string_script_object_out.txt[]
----

===== Parameter Array

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#lowbar;array[Array]* it must specify *ArrayScriptObject &#42;* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_array_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_array_script_object_out.txt[]
----

===== Parameter Object

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#lowbar;object[Object]* it must specify *ObjectScriptObject &#42;* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_object_script_object.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_object_script_object_out.txt[]
----

===== Parameter Function

To register a C function that accepts a *xref:chapter_2_the_language_data_types.adoc#lowbar;function[Function]* it must specify *ScriptFunction &#42;* as parameter type on its function prototype. To make  _ScriptFunction_ callable from C++ it must to bind that using <<bindScriptFunction>>.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_script_function.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_script_function_out.txt[]
----

===== Parameter Registered Type

To register a C function that accepts a <<Registered type>> as a parameter, it must specify the *Registered type pointer* as parameter type on its function prototype.

*Example*

In the following example it registers the Point type and its properties `x` and `y`  (see <<Register type>> section to know about how to register class and properties) and it registers function `mul10Point` that accepts a Point type pointer as parameter. In the script execution it instances a Point type and is passed as argument to `mul10Point` that multiply its properties by 10.

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_registered_type.cpp[]
----

Out:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_registered_type_out.txt[]
----