:source-highlighter: highlight.js
:highlightjs-languages: cpp, javascript
:sectnums:
:stylesheet: /home/jespada/zetdev/zetscript/doc/zetscript-manual-reference.css

== The language

=== Statments

ZetScript Language is based on a set of statements formed by values, operators, expressions, keywords, declarations, expressions, conditionals, integrators and functions. All statements are separated by semicolons at the end.

Example of four statements,

[source,javascript]
----
var op1,op2,res;
op1 = 5;
op2 = 6;
res = 5+6;
----

The last example can be executed within one line,

[source,javascript]
----
var op1,op2,res; op1=5; op2=6; res = 5+6;
----

=== Comments

ZetScript support block and line comments.

==== Block comment

[source,javascript]
----
/*
this is a block comment
*/
----

==== Line comment

[source,javascript]
----
// This is a line comment
----

=== Literals

ZetScript supports the following literals,

* Boolean
* Integer
* Float
* String

==== Boolean

Boolean literals is represented as true or false.

Example,

[source,javascript]
----
true // true value
false // false value
----

==== Integer

Integer literals are represented as integer with range from -(2b-1) to 2b-1-1 where b=32 or 64 it depending whether ZetScript is compiled for 32bits or 64bits. The integer value can be represented as decimal value, hexadecimal,binary or char format.

Example,

[source,javascript]
----
10; // decimal value
0x1a; // hexadecimal value
11010b; // 0x1a as binary value
'b'; // char value
----

Integer literlas supports the following pre operators,

[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Example

|Negate
|-integer 
|Negated value
|
[source,javascript]
 -10
 
|Bitwise complement
|~integer 
|Invert all bits
|
[source,javascript]
~011010b // (-27)
|====

==== Float

Float literals are represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits. Float can be represented in decimal form or scientific notation form.

Example,

[source,javascript]
----
1.2 // decimal form
2.0e-2 // cientific notation form
----

Float literals supports the following pre operators,

[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Example

|Negate
|-float
|Negated value
|
[source,javascript]
 -10.5

|====

==== String

String literal is represented as string within quotes (").

Example,

[source,javascript]
----
"this is a string"
----

=== Variables and constants

==== Variable

A variable is a kind of element that can hold a variable. Because ZetScript variables are _dynamically typed_, it can hold different type of values on its lifetime. A variable is declared as *var* and, by default, is initialized as *undefined* value (see 2.5.1). 

[source,javascript]
----
var i; // Declared variable 'i' with no inicialization (undefined value).
----

A variable can be initialized with a proper type value through '=' operator. The follow example initializes a variable with integer value
(see section 2.2),

[source,javascript]
----
var i=10; // Declared variable 'i' and initialized as integer value.
----

==== Constant

A constant is a kind of element where its value is immutable on its in lifetime. A constant is declared as *const* and is mandatory to be initialized.

[source,javascript]
----
const NUM_ITEMS=10; // constant 'NUM_ITEMS' with value 10.
----

==== Scope

In ZetScript we have two types of basic scopes.

* Global
* Local

A ZetScript makes easy the concept of global local scope. Basically, variables declared on the main script are global and the others declared within a [block footnote:[A block is a statement that starts with '{' and ends with '}']], are local.

Example,

[source,javascript]
----
// Declares *i* variable as global
var i;

// block starts here 
{	
	// Declare *j* variable as local (you can also access to i).
	var j;
}
// block ends here, so *j* variable doesn't exist anymore
----

=== Data types

ZetScript supports the following builtin data types,

* Undefined
* Null
* Integer
* Number
* Boolean
* String
* Vector
* Object
* Function

==== Undefined

Undefined data type it defines a non initialized variable. A variable is instanced as _Undefined_ once a its assings *undefined* value,

[source,javascript]
----
var a; // 'a' is undefined as default
var b=undefined; // assigns undefined value
----

==== Null

Null data type it defines an empty or not valid variable. A variable is instanced as _Null_ once a its assings *null* value,

[source,javascript]
----
var i=null;
----

==== Integer

Integer data type it defines a integer variable with range from -(2b-1) to 2b-1-1 where b=32 or 64 it depending whether ZetScript is compiled for 32bits or 64bits. A variable is initialized as _Integer_ once it assigns decimal, hexadecimal,binary or char value.

Example,

[source,javascript]
----
var a=10; // decimal value
var b=0x1a; // hexadecimal value
var c=01001b; // binary value
var d='b'; //  char value
----

===== Operators

Integer data operators are applied on integer variables before or after its read. Integer operators are the following,

[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Result

|Negate
|-variable 
|Negates its value
|
[source,javascript]
 var i=10;
 var j=-i; // j=-10
 
|Bitwise complement
|~variable 
|Invert all bits
|
[source,javascript]
 var i=00000011b;
 var j=~i; // j=11111100b or -4 decimal
|PreIncrement
|++variable 
|Increments FIRST and THEN evaluates
|
[source,javascript]
 var i=0;
 var j=++i; // j=1, i =1
 
|PostIncrement
|variable++ 
|Evaluates FIRST and THEN increments
| 
[source,javascript]
var i=0; 
var j=i++; // j=0; i=1

| Predecrement
| --variable 
|Decrements FIRST and THEN evaluates
| 
[source,javascript]
var i=0; 
var j=--i; // j=-1; i=-1

|Postdecrement
|variable--
|Evaluates FIRST and THEN decrements
|[source,javascript] 
var i=0; 
var j=i--;//j=0;i=-1;
|====

===== Static functions

====== Integer::parse()

Converts Float or String to Integer value


*Syntax*

[source,javascript]
----
parse(_value)
----

+++<u>Parameters</u>+++

- __value_ : String or Float value

+++<u>Returns</u>+++

Integer parsed from the given value

*Example*

[source,javascript]
----
include::../examples/the_language/integer/integer_parse.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/integer/integer_parse_out.txt[]
----

==== Float

Float type it defines a float variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits. A variable is initialized as _float_ once it assigns a decimal or scientific value notation forms.

Example,

[source,javascript]
----
var a=1.2 // decimal form value
var b=2.0e-2 // cientific notation form value
----


===== Operators

Float operators are applied on float variables before or after its read. Float operators are the following,


[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Result
|Negate
|-variable 
|Evaluates negated variable
|
[source,javascript]
 var i=10.5;
 var j=-i; // j=-10.5

|PreIncrement 
|++variable 
|Increments FIRST and THEN evaluates
|
[source,javascript]
var i=0.5;
var j=++i; // j=1.5, i =1.5

|PostIncrement 
|variable++ 
|Evaluates FIRST and THEN increments
|
[source,javascript]
var i=0.5;
var j=i++; // j=0.5; i=1.5

|Predecrement 
|--variable 
|Decrements FIRST and THEN evaluates
|
[source,javascript]
var i=0.5;
var j=--i; // j=-0.5; i=-0.5

|Postdecrement 
|variable-- 
|Evaluates FIRST and THEN decrements
|
[source,javascript]
var i=0.5;
var j=i--;//j=0.5;i=-0.5;
|====

===== Static functions

====== Float::parse()

Converts Integer or String to Float value

*Syntax*

[source,javascript]
----
Float::parse(_value)
----

+++<u>Parameters</u>+++

- __value_ : String or Integer value

+++<u>Returns</u>+++

Float as parsed from given value

*Example*

[source,javascript]
----
include::../examples/the_language/float/float_parse.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/float/float_parse_out.txt[]
----

==== Boolean

Boolean type it defines a boolean variable represented as _true_ or _false_. A variable is initialized as _Boolean_ once it assigns a boolean value.

Example,

[source,javascript]
----
var b=false;
----

==== String

String type it defines a string type represented as a sequence of chars. A variable is initialized as _String_ once it assigns a string value.

*Example*

[source,javascript]
----
var s="this is a string";
----

===== Properties
 
====== String::length

Returns the length of the string

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_length.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_length_out.txt[]
----

===== Static functions
 
====== String::format()

Formats a string from with a serie of args. 

*Syntax*

[source,javascript]
----
String::format(_string,..._args)
----

+++<u>Parameters</u>+++

- __string_ : String representation with specified arguments and/or its format. Argument format is defined in the string within curly brackets (i.e {} ) where it specifies argument number and its format. The argument format is described below,

[cols="1m,3d"]
|====
|Format |description
|{n}
|It replaces {_n_} by the argument _n_
|{n:dm}
|It replaces the argument _n_ padding _m_ 0s on its left
|{n,m}
|It replaces argument _n_ padding _m_ spaces on its left
|====

- __args_ : variable args to be replaced in the string representation

+++<u>Returns</u>+++

A formated string

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_format.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/string/string_format_out.txt[]
----

===== Member functions

====== String::insertAt()

Inserts string or integer value into String variable at defined position

*Syntax*

[source,javascript]
----
String::insertAt(_position,_value)
----

+++<u>Parameters</u>+++

- __position_: Position where to insert. The position ranges within 0 to the length-1 of the String
- __value_: Integer or String value

+++<u>Returns</u>+++

None

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_insert_at.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_insert_at_out.txt[]
----

====== String::eraseAt(_position)

Removes the value at defined position

+++<u>Parameters</u>+++

- __position_:  The position where there's the value to remove. The position ranges within 0 to the length-1 of the String

+++<u>Returns</u>+++ 

None

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_erase_at.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_erase_at_out.txt[]
----

====== String::toUpperCase()

Returns the calling string value converted to uppercase

*Syntax*

[source,javascript]
----
String::toUpperCase()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

An string value converted to uppercase

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_to_upper_case.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_to_upper_case_out.txt[]
----

====== String::toLowerCase()

Returns the calling string value converted to lowercase

*Syntax*

[source,javascript]
----
String::toLowerCase()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++ 

A string value converted to lowercase

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_to_lower_case.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_to_lower_case_out.txt[]
----

====== String::clear()

Erases the contents of the string

*Syntax*

[source,javascript]
----
String::clear()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

None 

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_clear.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/string/string_clear_out.txt[]
----


====== String::replace()

Returns a string replaced by a replacement 

*Syntax*

[source,javascript]
----
String::replace(_old_string, _new_string)
----

+++<u>Parameters</u>+++

- __old_string_: The old string to be replaced 
- __new_string_: The new string to be replaced

+++<u>Returns</u>+++ 

A string where the specified values has been replaced

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_replace.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/string/string_replace_out.txt[]
----

====== String::split()

Splits the string into a vector of strings using a separator

*Syntax*

[source,javascript]
----
String::split(_separator)
----

+++<u>Parameters</u>+++

- __separator_ : separator value

+++<u>Returns</u>+++ 

A vector of strings 

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_split.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_split_out.txt[]
----

====== String::contains()

Tells whether a value is contained in the string or not

*Syntax*

[source,javascript]
----
String::contains(_value)
----

+++<u>Parameters</u>+++

- __value_: a value to find

+++<u>Returns</u>+++

A boolean value telling if the value exist or not in the string 

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_contains.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/string/string_contains_out.txt[]
----

====== String::indexOf()

Returns the position of the first occurrence of a value in a string

*Syntax*

[source,javascript]
----
String::indexOf(_search_value)
----

+++<u>Parameters</u>+++

- __search_value_ : string to search for

+++<u>Returns</u>+++ 

- A value >= 0 indicating the position of the first occurrence found
- -1 if the value is not present.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_index_of.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_index_of_out.txt[]
----

====== String::startsWith()

Checks whether a string starts with the specified string passed by value

*Syntax*

[source,javascript]
----
String::startsWidth(_value)
----

+++<u>Parameters</u>+++

- __value_ :  A string representing the value to check for

+++<u>Returns</u>+++ 

A boolean value telling whether the string starts with the specified value or not

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_starts_with.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_starts_with_out.txt[]
----

====== String::endsWith()

Checks whether a string ends with the specified string passed by value

*Syntax*

[source,javascript]
----
String::endsWidth(_value)
----

+++<u>Parameters</u>+++

- __value_ :  A string representing the value to check for

+++<u>Returns</u>+++ 

A Boolean value telling whether the string ends with the specified string or not

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_ends_with.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_ends_with_out.txt[]
----

====== String::substring()

Returns a substring of the string value from string within a the start and end indexes

*Syntax*

[source,javascript]
----
String::substring(_start_index, _end_index)
----

+++<u>Parameters</u>+++

- __start_index_: The index of the first character to include in the returned substring.
- __end_index_ (optional): The index of the first character to exclude from the returned substring.

+++<u>Returns</u>+++

A string containing the specified part of the given string.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_substring.zs[]
----

Ouput:

[source,txt]
----
include::../examples/the_language/string/string_substring_out.txt[]
----

====== String::append()

Extends the string by appending additional value at the end of its current string.

*Syntax*

[source,javascript]
----
String::append(_value)
----

+++<u>Parameters</u>+++

- __value__ : value to be appended

+++<u>Returns</u>+++ 

None

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_append.zs[]
----

Output

[source,text]
----
include::../examples/the_language/string/string_append_out.txt[]
----

==== Vector

Vector type it defines a container type that stores values in a unidimensional array. A variable is initialized as _Vector_ once it assings a open/closed square brackets (i.e '[]' ), 

Example,

[source,javascript]
----
[]; // a vector
----

Variable instanced as _Vector_ can also have initialized with a sequence of elements separated with coma (i.e ',') within square brackets,

Example,

[source,javascript]
----
[1,"string",true,2.0]; // A vector with elements
----

To access element vector is done through integer as a index.

Example,

[source,javascript]
----
var v=[1,"string",true,2.0]; // variable 'v' has 4 elements where its access exist in [0..3]
v[1]; // It access vector's second element (i.e "string")
----

===== Properties

====== Vector::length

Returns the number of elements in the vector

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_length.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_length_out.txt[]
----

===== Static functions

====== Vector::concat()

Creates a new vector as a result of merge all elements from two vectors

*Syntax*

[source,javascript]
----
Vector::concat(_v1, _v2)
----

+++<u>Parameters</u>+++

- __v1_ : First vector to concatenate into the new vector
- __v2_ : Second vector to concatenate into the new vector

+++<u>Returns</u>+++ 

A new vector as a result of merge all elements from the vectors

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_concat.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_concat_out.txt[]
----


===== Member functions

====== Vector::push()

Adds a new element at the end of the vector

*Syntax*

[source,javascript]
----
Vector::push(_value)
----

+++<u>Parameters</u>+++

- __value__ : value to be added

+++<u>Returns</u>+++ 

None

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_push.zs[]
----

Output

[source,text]
----
include::../examples/the_language/vector/vector_push_out.txt[]
----

====== Vector::pop()

Removes the last element in the vector

[source,javascript]
----
Vector::pop()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++ 

Last value of the vector before be removed

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_pop.zs[]
----

Output

[source,text]
----
include::../examples/the_language/vector/vector_pop_out.txt[]
----

====== Vector::insertAt(_pos,_value)

Inserts element in the vector at defined position

[source,javascript]
----
Vector::insertAt(_pos,_value)
----

+++<u>Parameters</u>+++

- __position_: Position where to insert. The position ranges within 0 to the length-1 of the vector
- __value_: value to insert

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_insert_at.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/string/string_insert_at_out.txt[]
----

====== Vector::eraseAt()

Removes the value at defined position

[source,javascript]
----
Vector::eraseAt(_pos)
----

+++<u>Parameters</u>+++

- __position_:  The position where there's the value to remove. The position ranges within 0 to the length-1 of the vector

+++<u>Returns</u>+++ 

None

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_erase_at.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_erase_at_out.txt[]
----

====== Vector::clear()

Clears all elements in the vector

[source,javascript]
----
Vector::clear()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

None 

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_clear.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/vector/vector_clear_out.txt[]
----

====== Vector::join(_separator)

Concatenates all elements of the vector into a string using a separator

[source,javascript]
----
Vector::join(_separator)
----

+++<u>Parameters</u>+++

- __separator_ : separator value

+++<u>Returns</u>+++ 

A string of all concatenated vector's elements 

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_join.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_join_out.txt[]
----

====== Vector::contains(_value)

Tells whether a value is contained in the vector or not

[source,javascript]
----
Vector::contains(_value)
----

+++<u>Parameters</u>+++

- __value_: a value to find

+++<u>Returns</u>+++

A boolean value telling if the value exist or not in the vector 

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_contains.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/vector/vector_contains_out.txt[]
----

====== Vector::extend(_v)

Extends the calling vector by appending all elements from a vector

[source,javascript]
----
Vector::extend(_v)
----

+++<u>Parameters</u>+++

- __v_ : Vector type which all elements will appended into the vector

+++<u>Returns</u>+++ 

None

*Example*

[source,javascript]
----
include::../examples/the_language/vector/vector_extend.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/vector/vector_extend_out.txt[]
----


==== Object

Object type is a anonymous container type to store values through attributes. A variable is initialized as _Object_ once it assings a open/closed of curly brackets (i.e '{}'),

[source,javascript]
----
{}; // Object
----

Optionally we can init with some values with its attributes,

[source,javascript]
----
{
  i:1
 ,s:"string"
 ,b:true
 ,f:2.0
};
----

To acces to its elements is done through the variable name followed by '.' and attribute name or attribute name as string within brackets (i.e ["attribute_name"] ),

[source,javascript]
----

var o={
  i:1
 ,s:"string"
 ,b:true
 ,f:2.0
};

o.i; // get contens of attribute 'i' by '.'
o["i"]; // gets the contents of attribute 'i' by '[]'
----

===== Static functions

====== Object::clear()

Clears all elements of an object

*Syntax*

[source,javascript]
----
Object::clear(_o)
----

+++<u>Parameters</u>+++

- __o_: The object to clear elements

+++<u>Returns</u>+++

None 

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_clear.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/object/object_clear_out.txt[]
----

====== Object::erase(_key_id)

Removes an attribute of an object

*Syntax*

[source,javascript]
----
Object::erase(_key_id)
----

+++<u>Parameters</u>+++

- __o_: The object to erase element
- __key_id_:  The key id of the attribute to remove

+++<u>Returns</u>+++ 

None

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_erase.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_erase_out.txt[]
----

====== Object::contains()

Tells whether a key is contained in an object or not

*Syntax*

[source,javascript]
----
Object::contains(_key_id)
----

+++<u>Parameters</u>+++

- __o_: The object to check
- __key_: a key to find

+++<u>Returns</u>+++

A boolean value telling if the attribute with __key_id_ exist or not in the object 

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_contains.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/object/object_contains_out.txt[]
----

====== Object::extend()

Extends an object by the content of other object

*Syntax*

[source,javascript]
----
Object::extend(_o1,_o2)
----

+++<u>Parameters</u>+++

- __o1_ : Object where to be extended
- __o2_ : Object where to copy the extension

+++<u>Returns</u>+++ 

None

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_extend.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_extend_out.txt[]
----

====== Object::concat()

Creates a new object as a result of merge all elements from two objects

*Syntax*

[source,javascript]
----
Object::concat(_o1, _o2)
----

+++<u>Parameters</u>+++

- __o1_ : First object to concatenate into the new object
- __o2_ : Second object to concatenate into the new object

+++<u>Returns</u>+++ 

A new object as a result of merge all elements from the two objects

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_concat.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_concat_out.txt[]
----

====== Object::keys(_o)

Returns a vector of string representing its key names

*Syntax*

[source,javascript]
----
Object::keys(_o)
----

+++<u>Parameters</u>+++ 

- __o_ : Object from get the keys

+++<u>Returns</u>+++ 

A vector of strings of its key names

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_keys.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_keys_out.txt[]
----


==== Function

Function type is a type that contains function information to be invoqued at some place through paranthesis (). A variable is initialized as _Function_ once it assings an a function or anonymous function

*Example*

Assing normal function to variable

[source,javascript]
----

// function add
function add(_a,_b){
	return _a+_b
}

// function add assigned to fun
var fun=add;

...

Console::outln(fun(5,5)); // it prints "10"

----

Also it assing anonymous function to variable

[source,javascript]
----

// anonymous function assigned to fun
var fun=function(_a,_b){
	return _a+_b
};

...

Console::outln(fun(5,5)); // it prints "10"
----

==== The typeof operator

The _typeof_ operator returns the type of operand's value.

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_keys.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/object/object_keys_out.txt[]
----


=== Operators

ZetScript has the following type of operators

* Arithmetic operators
* Relational operators
* Logical operators
* Bit operators

==== Arithmetic operators

Arithmetic operators performs arithmetic operations between two values. The arithmetic operators are the following,

[cols="2d,1m,3d,6a"]
|====
|Operator |Symbol |Description |Example
|Add 
|+
a|

It performs a these operations:

* Add operation between two integer or float values 
* Concatenates two strings or other values
* Concatenates two vectors 
* Concatenates two objects 

|
[source,javascript]
----
 5+10; // = 15
 1.5+6;// = 7.5
 "string_"+"string";// ="string_string"
 "string_"+1;// ="string_1"
 [1]+[2,3];// [1,2,3]
 {a:1}+{b:2,c:3}; //{a:1,b:2,c:3}
----

|Subtract
|-
|Performs a substract operation between two integer/float values
|
[source,javascript]
10-5; // = 5
2.5-1;// = 1.5

|Multiply 
|* 
|Performs a multiplication between two integer/float values
|
[source,javascript]
10*5; //= 50
1.5*2;//= 3.0

|Divide 
|/ 
|Performs a division between two integer/float values
|
[source,javascript]
10/2; // = 5
3/2.0 // = 1.5

|Modulus 
|% 
|Performs a division between two integer/float values
|
[source,javascript]
3%2; //it results 1
10%2.5; // it results
|====

==== Relational operators

Relational operators evaluates relations through two values. The relational operators are the following,

[cols="2d,1m,3d,6a"]
|====
|Operator |symbol |Description |Example

|Equal 
|==
|Check whether two values are equal
|
[source,javascript]
 10==10;// = true
"hello"=="bye"; // = false

|Not equal 
|!= 
|Check whether two values are not equal
|
[source,javascript]
10!=10; // = false
"hello"!="bye"; // = true

|Less than 
|< 
|Checks whether first value is less than second value
|
[source,javascript]
10<20; // = true
20<10; // = false

|Greater than 
|> 
|Checks whether first value is greater than second value
|
[source,javascript]
10>20; // = false
20>10; // = true

|Less equal than 
| \<= 
|Checks whether first value is less equal than second value
|
[source,javascript]
10<=10; //= true
11<=10; // = false

|Greater equal than 
|>= 
|Checks whether first value is greater equal than second value
|
[source,javascript]
10>=11; // = false
11>=10; // = true

|Instance of 
|instanceof 
|Checks if a value is instance of a type. 
|
[source,javascript]
0 instanceof Integer; //= true
"hello" instanceof Integer;//= false

|in 
|in 
a|
Performs the following operations:

* Checks if a value exist in a string or vector
* Checks a key exist in object
|
[source,javascript]
'a' in "abc" // true
'd' in "abc" // false
"string" in [1,"string",false,10.5] // true
10       in [1,"string",false,10.5] // false
"a" in {a:1,b:2,c:3} // true
"d" in {a:1,b:2,c:3} // false


|====



==== Logic operators

Logic operators combines operations between two boolean values. The logic operators are the following,

[cols="2d,1m,3d,6a"]
|====
|Operator |symbol |Description |Example

|Logic And 
|&& 
|Performs an AND operation between two boolean values
|
[source,javascript]
true && true;// = true
true&& false;// = false

|Logic Or 
| \|\|
|Performs an OR operation between two Boolean values
|
[source,javascript]
true \|\| false;// = true
false \|\| false;// = false

|Logic Not 
|! 
|Negates boolean value
|
[source,javascript]
!true; // = false
!false; // = true
!(true \|\| false) // = false 
!(true && false) // = true
|====

==== Binary operators

Binary operators combines operations between two integer values. The binary operators are the following,

[cols="2d,1m,3d,6a"]
|====
|Operator |symbol |Description |Example

|Binary And 
|& 
|Performs binary AND operation between two integers
|
[source,javascript]
0xa & 0x2; // = 0x2
0xff & 0xf0; // = 0xf0

|Binary Or
|\|
|Performs binary OR operation between two integers
|
[source,javascript]
0xa \| 0x5; // = 0xf
0x1 \| 0xe; // = 0xf

|Binary Xor 
|^ 
|Performs binary XOR between two integers
|
[source,javascript]
0xa ^ 0xa; // = 0x0
0xa ^ 0x5; // = 0xf

|Binary shift left
|<< 
|Performs binary shift left between two integers
|
[source,javascript]
0x1 << 2; // = 0x4

|Binary shift right
|>> 
|Performs binary shift right between two integers
|
[source,javascript]
0xff >> 1; // = 0x7f

|Bitwise complement
|~
|Performs bitwise complement operation from integer value
|
[source,javascript]
~0xa; // = 0x7f

|====

==== Operator priority
Each operator it has priority in a evaluation. The priority of each operator in ZetScript is the following,

<<,>>,&,|,^,*,/,%,+,-,in,instanceof,==,!=,>=,\<=,>,<,&&,||

Starting from left to right, the most left operator is the more priority and the most right one the less priority

For example this expression,

[source,javascript]
----
2+4*5; // will result 22
----

You can change the evaluation priority usign parenthesis.

For example,

[source,javascript]
----
(2+4)*5; // will result 36
---- 

=== Conditionals

==== If,else and else if statements

===== The if statement

The _if_ statement is used to execute a block of code when a condition is _true_.

*Syntax*

[source,javascript]
----
if(condition){
	//Block of code to be executed if the condition is true
}
----

*Example*

[source,javascript]
----
var i=5
if(i<10){
	Console::outln("i is less than 10")
}
----

===== The else statement

The _else_ statement is used to execute a block of code when a condition is _false_.

*Syntax*

[source,javascript]
----
if(condition) {
	// do something if condition is true
}else{
	// do something if condition is false
} 
----

*Example*

[source,javascript]
----
var i=5
if(i<10){
	Console::outln("i is less than 10")
}else{
	Console::outln("i is greather equal than 10")
}
----

===== The else if statement

The _else if_ statement is used to execute a block of code if first condition is _false_.

[source,javascript]
----
if(condition1) {
 	// do something if condition 1is true
}else if(condition2){
	// do something if condition 2 is true
}else{
	// do something if none of above conditions are true
}
----

*Example*

[source,javascript]
----
var i=5
if(i>7){
	Console::outln("i greather than 7")
}else if(i>5){
	Console::outln("i greather than 5 and less equal than 7")
}else{
	Console::outln("i less equal than 5")
}
----


==== The ternary statement

The ternary statement to have a short _if-else_ statement into single statement. It performs expression if the condition is true or the second expression if the condition is 'false'.

*Syntax*

[source,javascript]
----
result = (condition)?first expression:2nd expression;
----

*Example*

[source,javascript]
----
var j = 0>1? 0:1; // j = 1
----

==== The switch statement

The _switch_ statement is used to select one of many blocks of code to be executed.

*Syntax*

[source,javascript]
----
switch(expression) {
	case value_0:
		code block
		break;
	case value_1:
		code block
		break;
	 	...
		case value_n
	default:
		code block
		break;
}

*Example*


[source,javascript]
----

var i=0

switch(i) {
	case 0:
		Console::outln("i == 0")
		break;
	case 1:
		Console::outln("i == 1")
		break;
	case 2:
		Console::outln("i == 2")
		break;
	default:
		Console::outln("i is not in [0,1,2]")
		break;
}

// Switch can have common code blocks in different conditions
switch(i) {
	case 0:
	case 1:
		Console::outln("i in [0,1]")
		break;
	case 2:
		Console::outln("i is 2")
		break;
	default:
		Console::outln("i is not in [0,1,2]")
		break;
}
----


=== Loops

==== The while loop

The _while_ loop loops through a block of code as long as a specified condition is true.

*Syntax*

[source,javascript]
----
while(condition){
	// code block to be executed
}
----

*Example*

[source,javascript]
----
include::../examples/the_language/loop/loop_while.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/lopp/loop_while_out.txt[]
----

==== do-while loop

The _do-while_ loop is always be executed at least once, even if the condition is _false_, because the code block is executed before the condition is tested:

*Syntax*

[source,javascript]
----
do{
	// do-while body
} while (condition);
----

*Example*

[source,javascript]
----
include::../examples/the_language/loop/loop_do_while.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/lopp/loop_do_while_out.txt[]
----

==== The for loop

The _for_ loop performs an iteration with 3 optional statements:

*Syntax*

[source,javascript]
----
for(stament1;statment2;statment3){
	// code block to be executed
}
----

* Statement 1 is executed before the loop (the code block) starts. Normally you will use statement 1 to initialize the variable used in the loop (for example var i = 0).
* Statement 2 defines the condition for running the loop.
* Statement 3 is executed each time after the code block has been executed.

*Example*

[source,javascript]
----
include::../examples/the_language/loop/loop_for.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/lopp/loop_for_out.txt[]
----


==== The for-in loop

The _for-in_ loop works as for loop but simplifies the iteration over containers like string, object or vectors. On each iteration it can evaluate its value in a variable or its key and its value in a pair of variables,

*Syntax*

[source,javascript]
----
// Evaluate container value per iteration
for(var v in vector){
	// code block to be executed
}

// Evaluate container key and value per iteration
for(var k,v in vector){
	// code block to be executed
}
----

*Example*

[source,javascript]
----
include::../examples/the_language/loop/loop_for_in.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/lopp/loop_for_in_out.txt[]
----

==== The break and continue

===== break statement

The _break_ statement is used to jump out of body loop.

*Example*

[source,javascript]
----
include::../examples/the_language/loop/loop_for_break.zs[]
----

Out:

[source,txt]
----
include::../examples/the_language/loop/loop_for_break_out.txt[]
----


===== continue statement

The _continue_ statement breaks one iteration and continues with the next iteration in the loop.

*Example*

[source,javascript]
----
include::../examples/the_language/loop/loop_for_continue.zs[]
----

Out:

[source,txt]
----
include::../examples/the_language/loop/loop_for_continue_out.txt[]
----


=== Function

A _function_ is a block of code to perform a particular task and is executed when in some part of the code it calls it

*Syntax*

Syntax,

[source,javascript]
----
function fun_name(arg1, arg2, ..., argn){
	// code to be executed
}
----

Example,

[source,javascript]
----
function add(op1, op2){
	return op1+op2;
}
----

==== Function invocation

The call of a function is done when in some part of the code it calls it as follow,

*Syntax*

[source,javascript]
----
fun_name(arg1, arg2, arg3,..., argN);
----

Note: If a function is called with less than N args the rest of arguments will remain undefined.

Example,

[source,javascript]
----

function add(op1,op2){
	return op1+op2;
}

var j=add(2,3); // calls add function. j=5
----

==== Function return

When JavaScript reaches a return statement, the function will stop executing.

If the function was invoked from a statement, JavaScript will "return" to execute the code after the invoking statement.

Functions often compute a return value. The return value is "returned" back to the "caller":

*Example*

[source,javascript]
----
let x = myFunction(4, 3);   // Function is called, return value will end up in x

function myFunction(a, b) {
  return a * b;             // Function returns the product of a and b
}
----

==== Function object

A function can be stored in variables through its reference,

[source,javascript]
----
function add(op1, op2){
	return op1+op2;
}

var fun_obj = add; // stored function add reference to fun_obj
var j=fun_obj(2,3);// calls fun_obj (aka add) function. J=5
----

Also is possible to create function objects,

Syntax

[source,javascript]
----
function(arg1, arg2, ..., argN){
	// code to be executed.
};
----

Example,

[source,javascript]
----
var add=function(op1, op2){
	return op1+op2;
};

var j=add(2,5); // j=5
----

==== Default parameters

Default function parameters allow named parameters to be initialized with default values if no value or undefined is passed.

[source,javascript]
----
function fun(arg1, arg2,arg2=default_arg){
	// ...
};
----

*Example*

Output:

==== Variable parameters

The rest parameter (...) allows a function to treat an indefinite number of arguments as an array

Syntax,

[source,javascript]
----
function var_args(...args) {
}
----

you can combine with other arguments but the array as variable parameter must be defined on the last one  

Syntax,

[source,javascript]
----
function var_args(op1, op2, ...args){
}

----


*Example*

[source,javascript]
----
include::../examples/the_language/function/function_variable_parameter.zs[]
----

Ouput:

[source,text]
----
include::../examples/the_language/function/function_variable_parameter_out.txt[]
----

==== Parameters by reference

In Pass by Reference, a function is called by directly passing the reference of the variable as the argument

*Example*

[source,javascript]
----
include::../examples/the_language/function/function_parameter_by_reference.zs[]
----

Ouput:

[source,text]
----
include::../examples/the_language/function/function_parameter_by_reference_out.txt[]
----


=== Class

A class is a template for create objects wiith its own variables and functions. A class is defined using keyword _class_ followed by the name. 

A class is a type of structure that contains properties and functions that operates with this properties. A class is defined in ZetScript using keyword class followed by the name of class. To access class properties within functions use the this keyword in
order to access to propertie or functions inside class. In a class we can find member functions (functions that affects to class property) or static functions (helper function of generic purposes about the class type). 

*Syntax*

[source,javascript]
----
class Test{
	// initialized member property
	var num1=10;
	
	// constructor
	constructor(){
		this.num2=20; // creates and initiales variable
	}
	
	// member function
	add(_op1){
		this.num1 =a;
		Console::outln("function1:"+this.data1);
		return this.property;
	}
	// static function that performs an add operation between two Test type objects
	function add_test (a,b){
	return a.data1+b.data1;
	}
};
----

Within a class we can find the following,

- Class instantiation
- Inicialization
- Member properties 
- Member functions
- Const properties


==== Class instantiantion

A class instantiation is done through the keyword _new_

*Example*

[source,javascript]
var t = new Test(); // Instantiate t as Test type.

==== Member initialization

In a class the first thing that it happens is initialization, if initialization does not ocur, then all member properties will be defined. Member initialization can be done through _constructor_ function or via initialize properties

===== Constructor

The constructor function is a special function that aims to execute when class is instanced. The definition and initialization of a member property is done through a keyword _this_. 

*Example*
[source,javascript]
----
class Test{

 	// Constructor function
	constructor(){
		this.a=0; // initialize field a=0
 	}
}
----


===== Property initialization

A property initialization is a way to define and initialize properties outside of _constructor_ 

*Example*
[source,javascript]
----
class Test{
 	
 	var a=0
 	
}
----



==== Member functions

Member functions are functions defined in the class. The function can acceded throught To access class variables/functions is done through "." operator.

Example,

[source,javascript]
----
var i=t.function1(2); // initializes data1 as 2 and return the value
----


==== Post declare function member

Is possible to add more class member through "::" punctuator.

Example,

[source,javascript]
----
	
	// post declaration of function member
	function Test::function2(){
 		this.data2="a string";
	}
----

==== Inheritance

A class can inherit another class through "extends". The new extended class will inheritance all variable/functions members from base class.

Example,

[source,javascript]
----
class TestExtended extends Test{
	function3(){
		this.data3=this.data1+this.function1(10);
	}
};
----
===== Call parent functions

The extended class can call parent functions through _super_ keyword.

Example,

[source,javascript]
----
class TestExtended extends Test{
	function1(a){
 		var t=super(a); // it calls Test::function1(2)
 		this.data1+=t; // Now data1=5+2 = 7
 		return this.data1+a;
 	}
 	
 	function3(){
 		this.data3=this.data1+this.function1(5);
 	}
}; 
----

==== Metafunctions
Metafunctions are special functions members that links with operators seen on section section 3.6. ZetScript metafunctions can be static or member function footnote:[ On script side, static function is defined as member function, but user should not access on variable/function members as well it happens on c++ static function.] depending whether the operation affects or not the object itself. 

===== Static functions

===== _equ()

Implements _equal_ operator (aka == ) between first operand and second operand

*Syntax*

[source,javascript]
----
_equ(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 and op2 are EQUAL
- False if op1 and op2 are NOT EQUAL

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_equ.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_equ_out.txt[]
----

===== _nequ()

Implements _not equal_ operator (aka != ) between first operand and second operand

*Syntax*

[source,javascript]
----
_nequ(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 and op2 are NOT EQUAL
- False if op1 and op2 are EQUAL

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_nequ.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_nequ_out.txt[]
----

===== _lt()

Implements _less than_ operator (aka < ) between first operand and second operand

*Syntax*

[source,javascript]
----
_lt(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is LESS THAN op2
- False if op1 is GRATHER EQUAL THAN op2

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_lt.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_lt_out.txt[]
----

===== _lte()

Implements _less than or equal_ operator (aka \<= ) between first operand and second operand

*Syntax*

[source,javascript]
----
_lte(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is LESS THAN OR EQUAL op2
- False if op1 is GRATHER THAN op2

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_lte.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_lte_out.txt[]
----

===== _gt()

Implements _greather than_ operator (aka > ) between first operand and second operand

*Syntax*

[source,javascript]
----
_gt(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is GREATHER THAN op2
- False if op1 is LESS OR EQUAL THAN op2

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_gt.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_gt_out.txt[]
----

===== _gte(_op1,_op2)

Implements _greather than or equal_ operator (aka >= ) between first operand and second operand

*Syntax*

[source,javascript]
----
_gte(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is GREATHER THAN OR EQUAL op2
- False if op1 is LESS THAN op2

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_gte.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_gte_out.txt[]
----

===== _add()

Implements _add_ operator (aka + ) between first operand and second operand

*Syntax*

[source,javascript]
----
_add(_op1,_op2)
----  

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of add operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_add.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_add_out.txt[]
----

===== _div()

Implements _division_ operator (aka / ) between first operand and second operand

*Syntax*

[source,javascript]
----
_div(_op1,_op2)
----  

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of division operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_div.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_div_out.txt[]
----


===== _mul()

Implements _multiplication_ operator (aka * ) between first operand and second operand

*Syntax*

[source,javascript]
----
_mul(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of multiplication operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_mul.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_mul_out.txt[]
----

===== _mod()

Implements _modulus_ operator (aka * ) between first operand and second operand

*Syntax*

[source,javascript]
----
_mod(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of modulus operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_mod.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_mul_out.txt[]
----

===== _and()

Implements _bitwise and_ operator (aka & ) between first operand and second operand

*Syntax*

[source,javascript]
----
_and(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise and operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_and.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_and_out.txt[]
----

===== _or()

Implements _bitwise or_ operator (aka | ) between first operand and second operand

*Syntax*

[source,javascript]
----
_or(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise or operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_or.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_or_out.txt[]
----

===== _xor()

Implements _bitwise xor_ operator (aka ^ ) between first operand and second operand

*Syntax*

[source,javascript]
----
_xor(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise xor operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_xor.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_xor_out.txt[]
----
===== _shl()

Implements _bitwise shift left_ operator (aka << ) between first operand and second operand

*Syntax*

[source,javascript]
----
_shl(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise shift left operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_shl.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_shl_out.txt[]
----

===== _shr()

Implements _bitwise shift right_ operator (aka << ) between first operand and second operand

*Syntax*

[source,javascript]
----
_shr(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise shift right operation 

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_shr.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_shr_out.txt[]
----

===== Member functions

====== _toString()

Returns custom when string operation operation is invoved

*Syntax*

[source,javascript]
----
_toString()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

Custom string defined by user

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_to_string.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_to_string_out.txt[]
----

===== _set()

Performs a set operation

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : value to set.

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_set.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_set_out.txt[]
----

===== _not()

Implements _not_ pre operator (aka !)  

*Syntax*

[source,javascript]
----
_not()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- Boolean value as a result of not operation

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_not.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_not_out.txt[]
----

===== _neg()

Implements _negate_ pre operator (aka -a ) 

*Syntax*

[source,javascript]
----
_neg()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- A new object as result of negate operation

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_negt.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_not_neg.txt[]
----

===== _post_inc()


Implements _post_increment_ operator (aka a++ ) 

*Syntax*

[source,javascript]
----
_post_inc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_post_inc.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_post_inc_out.txt[]
----

===== _post_dec()

Implements _post_decrement_ operator (aka a-- ) 

*Syntax*

[source,javascript]
----
_post_dec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_post_dec.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_post_dec_out.txt[]
----

===== _pre_inc()

Implements _pre_increment_ operator (aka ++a ) 

*Syntax*

[source,javascript]
----
_pre_inc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_pre_inc.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_pre_inc_out.txt[]
----

===== _pre_dec()

Implements _pre_decrement_ operator (aka --a ) 

*Syntax*

[source,javascript]
----
_pre_dec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metafunction_pre_dec.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_metafunction_pre_dec_out.txt[]
----
 
==== Custom properties

A custom property is and special property that operates with a set of metafunctions.

*Syntax*

[source,javascript]
----
class ClassWithVirtualProperty{

	// custom property
	prop{
			...
	}

}
----

==== Member functions

===== _get()

Performs a get operation

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

None

+++<u>Returns</u>+++

Returns the value of this property

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_property_metafunction_set.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_property_metafunction_set_out.txt[]
----

===== _set()

Performs a set operation

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : value to set.

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_property_metafunction_set.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_property_metafunction_set_out.txt[]
----

===== _not()

Implements _not_ pre operator (aka !)  

*Syntax*

[source,javascript]
----
_not()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- Boolean value as a result of not operation

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_property_metafunction_not.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_property_metafunction_not_out.txt[]
----

===== _neg()

Implements _negate_ pre operator (aka -a ) 

*Syntax*

[source,javascript]
----
_neg()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- A new object as result of negate operation

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_property_metafunction_negt.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_property_metafunction_not_neg.txt[]
----

===== _post_inc()


Implements _post_increment_ operator (aka a++ ) 

*Syntax*

[source,javascript]
----
_post_inc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_property_metafunction_post_inc.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_property_metafunction_post_inc_out.txt[]
----

===== _post_dec()

Implements _post_decrement_ operator (aka a-- ) 

*Syntax*

[source,javascript]
----
_post_dec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_property_metafunction_post_dec.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_property_metafunction_post_dec_out.txt[]
----

===== _pre_inc()

Implements _pre_increment_ operator (aka ++a ) 

*Syntax*

[source,javascript]
----
_pre_inc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_property_metafunction_pre_inc.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_property_metafunction_pre_inc_out.txt[]
----

===== _pre_dec()

Implements _pre_decrement_ operator (aka --a ) 

*Syntax*

[source,javascript]
----
_pre_dec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_property_metafunction_pre_dec.zs[]
----

Output:

[source,text]
----
include::../examples/the_language/class/class_property_metafunction_pre_dec_out.txt[]
----


=== Modules

==== Console

`Console` module implements a set of functions for console

===== Console::out()

Prints message to the console with a ending carry return

[source,zetscript]
Console::out(_value,..._args)

+++<u>Parameters</u>+++

- __value_: If __value_ is string it can be formated (see in table X.X), else it tries to print a the value as human readable

+++<u>Returns</u>+++

*Example*

[source,zetscript]
----
include::../examples/the_language/console/console_out.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/console/console_out_out.txt[]
----


===== Console::outln()

Prints message to the console with a ending carry return

*Syntax*

[source,zetscript]
Console::outln(_value,..._args)

+++<u>Parameters</u>+++

- __value_: If __value_ is string it can be formated (see in table X.X), else it tries to print a the value as human readable

+++<u>Returns</u>+++

*Example*

[source,zetscript]
----
include::../examples/the_language/console/console_outln.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/console/console_outln_out.txt[]
----

===== Console::error()

Prints error message to the console

[source,zetscript]
Console::out(_value,..._args)

+++<u>Parameters</u>+++

- __value_: If __value_ is string it can be formated (see in table X.X), else it tries to print a the value as human readable

+++<u>Returns</u>+++

*Example*

[source,zetscript]
----
include::../examples/the_language/console/console_error.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/console/console_error_out.txt[]
----

===== Console::errorln()

Prints error message to the console with a ending carry return

*Syntax*

[source,zetscript]
Console::outln(_value,..._args)

+++<u>Parameters</u>+++

- __value_: If __value_ is string it can be formated (see in table X.X), else it tries to print a the value as human readable

+++<u>Returns</u>+++

*Example*

[source,zetscript]
----
include::../examples/the_language/console/console_errorln.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/console/console_errorln_out.txt[]
----

===== Console::readChar()

it waits untill reads a character from console

*Syntax*

[source,zetscript]
Console::readChar()

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

The integer as the equivalent character readed from console

*Example*

[source,zetscript]
----
 // waits until reads a char
 var c=Console::readChar();
 
 // prints readed char
 Console::outln("Key pressed: {0}",c) 
  
----

==== System

`System` module implements a set of functions for system

===== System::clock()

Returns the amount of time in milliseconds

Syntax,

[source,zetscript]
System::clock()

Example,

[source,zetscript]
----
include::../examples/the_language/system/system_clock.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/system/system_clock_out.txt[]
----

===== System::eval

Evals a expression

Syntax,

[source,zetscript]
System::eval(_string,..._args)

Example,


[source,zetscript]
----
include::../examples/the_language/system/system_eval.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/system/system_eval_out.txt[]
----

===== System::assert()

Evals an assert and raise an error if the condition is false

*Syntax*

[source,zetscript]
System::assert(_condition,_string)

Example,


[source,zetscript]
----
include::../examples/the_language/system/system_assert.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/system/system_assert_out.txt[]
----

===== System::error

Raises an error by user

Syntax,

[source,zetscript]
System::error(_string,..._args)

Example,


[source,zetscript]
----
include::../examples/the_language/system/system_error.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/system/system_error_out.txt[]
----

==== Math

`Math` module implements a set of functions and properties related with maths

===== Static member properties

====== Math::PI

The number PI

*Syntax*

[source,zetscript]
Math::PI

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_pi.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_pi.txt[]
----

===== Static functions

====== Math::sin()

Performs a sinus

*Syntax*

[source,zetscript]
Math::sin(_value)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_sin.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_sin_out.txt[]
----

====== Math::cos()

Performs a cosinus

*Syntax*

[source,zetscript]
Math::cos(_value)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_cos.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_cos_out.txt[]
----

====== Math::abs()

Performs a absolute

*Syntax*

[source,zetscript]
Math::abs(_value)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_abs.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_abs_out.txt[]
----

====== Math::pow()

Performs a power

*Syntax*

[source,zetscript]
Math::pow(_base,_pow)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_pow.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_pow_out.txt[]
----

====== Math::degToRad()

Converts degres to radiants

*Syntax*

[source,zetscript]
Math::degToRad(_degres)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_deg_to_rad.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_deg_to_rad.txt[]
----

====== Math::random()

Returns random float number between [0..1)

*Syntax*

[source,zetscript]
Math::random()

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_random.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_random_out.txt[]
----

====== Math::max()

Returns maximmum of two input values

*Syntax*

[source,zetscript]
Math::max(_v1,_v2)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_max.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_max_out.txt[]
----

====== Math::min()

Returns minimmum of two input values

*Syntax*

[source,zetscript]
Math::min(_v1,_v2)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_min.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_min_out.txt[]
----

====== Math::sqrt()

Performs the sqrt of input value

*Syntax*

[source,zetscript]
Math::sqrt(_value)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_sqrt.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_sqrt_out.txt[]
----

====== Math::floor()

Returns the floor of input value

*Syntax*

[source,zetscript]
Math::floor(_value)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_floor.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_floor_out.txt[]
----

====== Math::ceil()

Returns the ceil of input value

*Syntax*

[source,zetscript]
Math::ceil(_value)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_ceil.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_ceil_out.txt[]
----

====== Math::round()

Returns the round of input value

*Syntax*

[source,zetscript]
Math::round(_value)

*Example*

[source,zetscript]
----
include::../examples/the_language/math/math_round.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/math/math_round_out.txt[]
----

==== Json

`Json` module implements a set of functions to serialize and deserialize json format from/to zetscript types

===== Json::serialize()

Serializes value or variable to json string

*Syntax*

[source,zetscript]
Json::serialize(_value)

*Example*

[source,zetscript]
----
include::../examples/the_language/json/json_serialize.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/json/json_serialize_out.tx[]
----

===== Json::deserialize()

Deserializes json string to variable

*Syntax*

[source,zetscript]
Json::deserialize(_string)

*Example*

[source,zetscript]
----
include::../examples/the_language/json/json_deserialize.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/json/json_deserialize_out.tx[]
----

==== DateTime

===== Operations
 
====== _add

Perform add operation (aka +) between two objects type DateTime

*Example*

[source,javascript]
----
include::../examples/the_language/datetime/datetime_metafunctions_add.zs[]
----

[source,txt]
----
include::../examples/the_language/datetime/datetime_metafunctions_add_out.txt[]
----

====== _sub

Perform sub (aka -)  operation between two objects type DateTime

*Example*

[source,javascript]
----
include::../examples/the_language/datetime/datetime_metafunctions_sub.zs[]
----

[source,txt]
----
include::../examples/the_language/datetime/datetime_metafunctions_sub_out.txt[]
----

====== _toString

Returns formatted date

*Example*

[source,javascript]
----
include::../examples/the_language/datetime/datetime_metafunctions_to_string.zs[]
----

[source,txt]
----
include::../examples/the_language/datetime/datetime_metafunctions_to_string_out.txt[]
----


===== Member properties

Datetime has the following memeber properties,

[cols="1m,3d"]
|====
|Variable |description
|week_day
|The week's day
|month_day
|The month's day
|year_day
|The year's day
|second
|seconds
|minute
|minutes
|hour 
|hours
|day
|day
|month
|month
|year
|year
|====

*Example*

[source,zetscript]
----
include::../examples/the_language/datetime/datetime_member_properties.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/datetime/datetime_member_properties_out.txt[]
----

===== Member functions

====== DateTime::addSeconds()

Adds seconds to datetime object

*Syntax*

[source,zetscript]
DateTime::addSeconds(_seconds)

*Example*

[source,zetscript]
----
include::../examples/the_language/datetime/datetime_add_seconds.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/datetime/datetime_add_seconds_out.txt[]
----

====== DateTime::addMinutes()

Adds minutes to datetime object

*Syntax*

[source,zetscript]
DateTime::addMinutes(_minutes)

*Example*

[source,zetscript]
----
include::../examples/the_language/datetime/datetime_add_minutes.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/datetime/datetime_add_minutes_out.txt[]
----


====== DateTime::addHours()

Adds hours to datetime object

*Syntax*

[source,zetscript]
DateTime::addHours(_hours)

*Example*

[source,zetscript]
----
include::../examples/the_language/datetime/datetime_add_hours.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/datetime/datetime_add_hours_out.txt[]
----

====== DateTime::addDays()

Adds days to datetime object

*Syntax*

[source,zetscript]
DateTime::addDays(_days)

*Example*

[source,zetscript]
----
include::../examples/the_language/datetime/datetime_add_days.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/datetime/datetime_add_days_out.txt[]
----

====== DateTime::addMonths()

Adds months to datetime object

*Syntax*

[source,zetscript]
DateTime::addMonths(_months)

*Example*

[source,zetscript]
----
include::../examples/the_language/datetime/datetime_add_months.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/datetime/datetime_add_months_out.txt[]
----

====== DateTime::addYears()

Adds years to datetime object

*Syntax*

[source,zetscript]
DateTime::addYears(_years)

*Example*

[source,zetscript]
----
include::../examples/the_language/datetime/datetime_add_years.zs[]
----

Output:

[source,txt]
----
include::../examples/the_language/datetime/datetime_add_years_out.txt[]
----

