=== Exposing C++ types to ZetScript

In this chapter will see how to to expose C&plus;&plus; types by registering its C&plus;&plus; types,  function members, metamethods and properties.


==== Register type

There's two kind of registering types,

- Register type non instanciable
- Register type instanciable



==== Register no instanciable type

Register a not instanciable type it means that it CANNOT create new objects of that 'type' in any ZetScript code using operator new, so the object only can be acceded by reference returned by some function C&plus;&plus; registered. This kind of register type is usueful when it wants to have a control of instantiated objects in the native application.

To register non instantible type is done simple by calling `ZetScript::registerType` with type as template and the name that will be referenced in the script.

*Syntax*
[source,cpp]
----
ScriptType * registerType<_Type>(const zs_string & _symbol_name);
----

+++<u>Template</u>+++ 

- _Type: C&plus;&plus; struct/class type

+++<u>Parameters</u>+++ 

- _symbol_name: Symbol name that will be referenced in ZetScript

+++<u>Returns</u>+++ 

A `ScriptType` object

*Example*

The following code shows an example of a registering non instanciable type. 

Let's define a C/C&plus;&plus; type 'MyType',

[source,cpp]
----
typedef struct{
	int x;
	int y;
}MyType;
----


Then, register type 'MyType' and symbol name as 'MyType',

[source,cpp]
----
void main(argc, char *argv[])
{
	zetscript::ZetScript zs;
	
 	//register MyType
 	zs.registerType<MyType>("MyType");
 	
 	return 0;
 }
----

Let's supose we want to instantiate a 'MyType' object in the following code,

[source,cpp]
----
void main(argc, char *argv[])
{
	zetscript::ZetScript zs;
	
 	//register MyType
 	zs.registerType<MyClass>("MyType");

	 	
	// It throws an error that MyClass is not instanciable
 	zs.eval(
 		"var my_type= new MyType();"
 	);
 	
 	return 0;
 }
----

The evaluation will fail with the following output,

 'MyType' type is not object instanceable


The only way to operate with a 'MyType' object non intanciable is by a reference returned by a registered function as it shows in the following example,


[source,cpp]
----
include::../examples/the_api/register_type/register_type_register_non_instanciable_type.cpp[]
----
  
==== Register instanciable type


Register a instanciable type it means that it CAN create new objects of that 'type' in ZetScript code using operator new.

To register instanciable type it's done also with registerType but, furthermore, it has to pass two additional parameters : A constructor function and destructor function.

*Syntax*
[source,cpp]
----
ScriptType * registerType<RegisteredType>(const zs_string & _symbol_name, RegisteredType * (*_new_native_instance)(ZetScript *_zs), void (*_delete_native_instance)(ZetScript *_zs, RegisteredType * _this));
----

+++<u>Template</u>+++ 

- __RegisteredType_: The registered type

+++<u>Parameters</u>+++ 

- __symbol_name_: Symbol name that will be referenced in ZetScript
- __new_native_instance_: A function that creates an returns a new instance. This function has the following signature,

[source,cpp]
----
RegsiteredType * RegisteredType_new(ZetScript *_zs);
----

- __delete_native_instance_: A function that deletes native instance. The function has the following signature,

[source,cpp]
----
void RegisteredType_delete(ZetScript *_zs, RegisteredType *_this);
----

+++<u>Returns</u>+++ 

A `ScriptType` object

Example,

[source,cpp]
----
include::../examples/the_api/register_type/register_type_register_instanciable_type.cpp[]
----

===== Register constructor


To register a constructor function it has to create and register a C&plus;&plus; function with a particular prototype. That function it acts as it seen in *xref:chapter_2_the_language_class.adoc#_constructor[ZetScript class constructor]*.

As parameters, the function must always include `zetscript::ZetScript *` as the FIRST parameter,the pointer of the registered type as SECOND parameter and a maximum of 8 parameters as <<ZetScript built-in type>> or other registered type. 

*Syntax*

[source,c++]
----
void RegisteredType_constructor(zetscript::ZetScript *_zs, _RegisteredType *_this, ParamType *_arg1, ..., ParamType *_arg8 ){
	....
}
----

Where,

- _RegisteredType_: The C&plus;&plus; registered type
- _ParamType_: It can be one of defined in  <<ZetScript built-in types>> or other registered type.


After the constructor function is defined it has to be registered with `ZetScript::registerConstructor`. `registerConstructor` it has the following signature,


*Syntax*
[source,cpp]
----
void registerConstructor<RegisteredType>( Function _constructor_function);
----

+++<u>Template</u>+++ 

- _RegisteredType_: The registered type
- _Function_ : Function signature

+++<u>Parameters</u>+++ 

- ___constructor_function_: Reference of defined constructor function


*Example*
[source,cpp]
----
include::../examples/the_api/register_type/register_type_register_instanciable_type_with_constructor.cpp[]
----


==== Register members

===== Register member function

To register a member function it has to create and register a C function with a particular prototype.

As parameters, the function must always include `zetscript::ZetScript *` as the FIRST parameter,the pointer of the registered type as SECOND parameter and a maximum of 8 parameters as <<ZetScript built-in type>> or other registered type. 

As a return, the function it can return nothing, or a <<ZetScript built-in type>> or other registered type.

*Syntax*

[source,c++]
----
ReturnType RegisteredType_memberFunction(zetscript::ZetScript *_zs, _RegisteredType *_this, ParamType *_arg1, ..., ParamType *_arg8 ){
	....
}
----

Where,

- _RegisteredType_: The C&plus;&plus; registered type
- _ReturnType_: It can be `void` or some type defined in <<ZetScript built-in types>> or other registered 
- _ParamType_: It can be one of defined in  <<ZetScript built-in types>> or other registered type.


After the constructor function is defined it has to be registered with `ZetScript::registerMemberFunction`. `registerMemberFunction` it has the following signature,


*Syntax*
[source,cpp]
----
void registerMemberFunction<RegisteredType>(const zs_string & _name, Function _function);
----

+++<u>Template</u>+++ 

- _RegisteredType_: The registered C&plus;&plus;type
- _Function_ : Function signature


+++<u>Parameters</u>+++ 

- __name_	: Member function name
- __function_: Member function C reference

*Example*
[source,cpp]
----
include::../examples/the_api/register_type/register_type_register_member_function.cpp[]
----


===== Register static member function

To register a static member function it has to create and register a C function with a particular prototype.

As parameters, the function must always include `zetscript::ZetScript *` as the FIRST parameter and a maximum of 9 parameters as <<ZetScript built-in type>> or other registered type. 

As a return, the function it can return nothing, or a <<ZetScript built-in type>> or other registered type.

*Syntax*

[source,c++]
----
ReturnType RegisteredType_staticMemberFunction(zetscript::ZetScript *_zs, ParamType *_arg1, ..., ParamType *_arg9 ){
	....
}
----

Where,

- _ReturnType_: It can be `void` or some type defined in <<ZetScript built-in types>> or other registered 
- _ParamType_: It can be one of defined in  <<ZetScript built-in types>> or other registered type.


After the constructor function is defined it has to be registered with `ZetScript::registerStaticMemberFunction`. `registerStaticMemberFunction` it has the following signature,


*Syntax*
[source,cpp]
----
void registerStaticMemberFunction<RegisteredType>(const zs_string & _name, Function _function);
----

+++<u>Template</u>+++ 

- _RegisteredType_: The registered C&plus;&plus;type
- _Function_ : Function signature


+++<u>Parameters</u>+++ 

- __name_	: Member function name
- __function_: Member function C reference

*Example*
[source,cpp]
----
include::../examples/the_api/register_type/register_type_register_static_member_function.cpp[]
----


==== Register metamethods

explaing that to register metamethods you have to use

registerMemberFunction

===== Register member metamethods

====== _tostring()

Returns custom string when string operation operation is invoved

*Syntax*

[source,javascript]
----
_tostring()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A string as a result when string operation operation is invoved

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_tostring.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_tostring_out.txt[]
----

===== _set()

Implements _assignment_ operator (aka = ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

+++<u>Parameters</u>+++

- __value_ :Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_set.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_set_out.txt[]
----

===== _addset()

Implements _addition assignment_ operator (aka += ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_addset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_addset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_addset_out.txt[]
----

===== _subset()

Implements _substraction assignment_ operator (aka -= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_subset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_subset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_subset_out.txt[]
----

===== _mulset()

Implements _multiplication assignment_ operator (aka *= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_mulset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_mulset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_mulset_out.txt[]
----

===== _divset()

Implements _division assignment_ operator (aka /= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_divset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_divset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_divset_out.txt[]
----

===== _modset()

Implements _modulus assignment_ operator (aka %= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_modset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_modset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_modset_out.txt[]
----

===== _andset()

Implements _bitwise AND assignment_ operator (aka &= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_andset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_andset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_andset_out.txt[]
----

===== _orset()

Implements _bitwise OR assignment_ operator (aka |= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_andset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_orset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_orset_out.txt[]
----


===== _xorset()

Implements _bitwise XOR assignment_ operator (aka ^= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_xorset(_value)
----

+++<u>Parameters</u>+++

- __op1_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_xorset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_xorset_out.txt[]
----

===== _shrset()

Implements _bitwise SHIFT RIGHT assignment_ operator (aka >>= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_shrset(_value)
----

+++<u>Parameters</u>+++

- __op1_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_shrset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_shrset_out.txt[]
----

===== _shlset()

Implements _bitwise SHIFT LEFT assignment_ operator (aka <<= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_shrset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_shlset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_shlset_out.txt[]
----

===== _not()

Implements _not_ pre operator (aka !)  

*Syntax*

[source,javascript]
----
_not()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- Boolean value as a result of not operation

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_not.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_not_out.txt[]
----

===== _neg()

Implements _negate_ pre operator (aka -a ) 

*Syntax*

[source,javascript]
----
_neg()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- A new object as result of negate operation

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_neg.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_neg_out.txt[]
----

===== _postinc()


Implements _post increment_ operator (aka a++ ) 

*Syntax*

[source,javascript]
----
_postinc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_postinc.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_postinc_out.txt[]
----

===== _postdec()

Implements _post decrement_ operator (aka a-- ) 

*Syntax*

[source,javascript]
----
_postdec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_postdec.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_postdec_out.txt[]
----

===== _preinc()

Implements _pre increment_ operator (aka ++a ) 

*Syntax*

[source,javascript]
----
_preinc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_preinc.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_preinc_out.txt[]
----

===== _predec()

Implements _pre decrement_ operator (aka --a ) 

*Syntax*

[source,javascript]
----
_predec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_predec.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_predec_out.txt[]
----

===== _in()

Implements _in_ operator 

*Syntax*

[source,javascript]
----
_in(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as value to check whether exist or not in the containing class

+++<u>Returns</u>+++

Boolean telling whether the _value exist in or not

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_in.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_in_out.txt[]
---- 

===== Static functions

====== _equ()

Implements _equal_ operator (aka == ) between first operand and second operand

*Syntax*

[source,javascript]
----
_equ(_op1,_op2)
----

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 and op2 are EQUAL
- False if op1 and op2 are NOT EQUAL

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_equ.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_equ_out.txt[]
----

===== _nequ()

Implements _not equal_ operator (aka != ) between first operand and second operand

*Syntax*

[source,javascript]
----
_nequ(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 and op2 are NOT EQUAL
- False if op1 and op2 are EQUAL

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_nequ.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_nequ_out.txt[]
----

===== _lt()

Implements _less than_ operator (aka < ) between first operand and second operand

*Syntax*

[source,javascript]
----
_lt(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is LESS THAN op2
- False if op1 is GRATHER EQUAL THAN op2

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_lt.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_lt_out.txt[]
----

===== _lte()

Implements _less than or equal_ operator (aka \<= ) between first operand and second operand

*Syntax*

[source,javascript]
----
_lte(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is LESS THAN OR EQUAL op2
- False if op1 is GRATHER THAN op2

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_lte.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_lte_out.txt[]
----

===== _gt()

Implements _greather than_ operator (aka > ) between first operand and second operand

*Syntax*

[source,javascript]
----
_gt(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is GREATHER THAN op2
- False if op1 is LESS OR EQUAL THAN op2

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_gt.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_gt_out.txt[]
----

===== _gte(_op1,_op2)

Implements _greather than or equal_ operator (aka >= ) between first operand and second operand

*Syntax*

[source,javascript]
----
_gte(_op1,_op2)
---- 

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- True if op1 is GREATHER THAN OR EQUAL op2
- False if op1 is LESS THAN op2

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_gte.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_gte_out.txt[]
----

===== _add()

Implements _add_ operator (aka + ) between first operand and second operand

*Syntax*

[source,javascript]
----
_add(_op1,_op2)
----  

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of add operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_add.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_add_out.txt[]
----

===== _div()

Implements _division_ operator (aka / ) between first operand and second operand

*Syntax*

[source,javascript]
----
_div(_op1,_op2)
----  

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of division operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_div.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_div_out.txt[]
----


===== _mul()

Implements _multiplication_ operator (aka * ) between first operand and second operand

*Syntax*

[source,javascript]
----
_mul(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of multiplication operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_mul.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_mul_out.txt[]
----

===== _mod()

Implements _modulus_ operator (aka * ) between first operand and second operand

*Syntax*

[source,javascript]
----
_mod(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of modulus operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_mod.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_mod_out.txt[]
----

===== _and()

Implements _bitwise and_ operator (aka & ) between first operand and second operand

*Syntax*

[source,javascript]
----
_and(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise and operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_and.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_and_out.txt[]
----

===== _or()

Implements _bitwise or_ operator (aka | ) between first operand and second operand

*Syntax*

[source,javascript]
----
_or(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise or operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_or.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_or_out.txt[]
----

===== _xor()

Implements _bitwise xor_ operator (aka ^ ) between first operand and second operand

*Syntax*

[source,javascript]
----
_xor(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise xor operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_xor.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_xor_out.txt[]
----
===== _shl()

Implements _bitwise shift left_ operator (aka << ) between first operand and second operand

*Syntax*

[source,javascript]
----
_shl(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise shift left operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_shl.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_shl_out.txt[]
----

===== _shr()

Implements _bitwise shift right_ operator (aka << ) between first operand and second operand

*Syntax*

[source,javascript]
----
_shr(_op1,_op2)
----   

+++<u>Parameters</u>+++

- __op1_ : 1st operand.
- __op2_ : 2nd operand.

+++<u>Returns</u>+++

- A new object as a result of bitwise shift right operation 

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_metamethod_shr.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_metamethod_shr_out.txt[]
----

 
==== Properties

explaing that to register properties you have to use

registerMemberProperty

*Syntax*

[source,javascript]
----
class Test{

	// property
	property{
			...
	}

}
----

==== Register property functions

===== _get()

__get_ returns the value of the property

*Syntax*

[source,javascript]
----
_get()
----

*Parameters

None

+++<u>Returns</u>+++

Returns the value of the property

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_get.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_get_out.txt[]
----

===== _set()

Implements _assignment_ operator (aka = ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ :Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_set.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_set_out.txt[]
----

===== _addset()

Implements _addition assignment_ operator (aka += ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_addset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_addset_out.txt[]
----


===== _subset()

Implements _substraction assignment_ operator (aka -= ) with a value entered by parameter as right operand.


*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_subset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_subset_out.txt[]
----

===== _mulset()

Implements _multiplication assignment_ operator (aka *= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_mulset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_mulset_out.txt[]
----

===== _divset()

Implements _division assignment_ operator (aka /= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_set(_value)
----

*Parameters

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_divset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_divset_out.txt[]
----

===== _modset()

Implements _modulus assignment_ operator (aka %= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_modset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_modset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_modset_out.txt[]
----

===== _andset()

Implements _bitwise AND assignment_ operator (aka &= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_andset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_andset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_andset_out.txt[]
----

===== _orset()

Implements _bitwise OR assignment_ operator (aka |= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_andset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_orset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_orset_out.txt[]
----


===== _xorset()

Implements _bitwise XOR assignment_ operator (aka ^= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_xorset(_value)
----

+++<u>Parameters</u>+++

- __op1_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_xorset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_xorset_out.txt[]
----

===== _shrset()

Implements _bitwise SHIFT RIGHT assignment_ operator (aka >>= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_shrset(_value)
----

+++<u>Parameters</u>+++

- __op1_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_shrset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_shrset_out.txt[]
----

===== _shlset()

Implements _bitwise SHIFT LEFT assignment_ operator (aka <<= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
_shrset(_value)
----

+++<u>Parameters</u>+++

- __value_ : Value or variable as right operand

+++<u>Returns</u>+++

None.

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_shlset.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_shlset_out.txt[]
----

===== _neg()

Implements _negate_ pre operator (aka -a ) 

*Syntax*

[source,javascript]
----
_neg()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

- A the value as result of negate operation

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_neg.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_neg_out.txt[]
----

===== _postinc()


Implements _post_increment_ operator (aka a++ ) 

*Syntax*

[source,javascript]
----
_postinc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_postinc.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_postinc_out.txt[]
----

===== _postdec()

Implements _post_decrement_ operator (aka a-- ) 

*Syntax*

[source,javascript]
----
_postdec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_postdec.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_postdec_out.txt[]
----

===== _preinc()

Implements _pre_increment_ operator (aka ++a ) 

*Syntax*

[source,javascript]
----
_preinc()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_preinc.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_preinc_out.txt[]
----

===== _predec()

Implements _pre_decrement_ operator (aka --a ) 

*Syntax*

[source,javascript]
----
_predec()
----

+++<u>Parameters</u>+++

None

+++<u>Returns</u>+++

A the object itself

*Example*

[source,javascript]
----
include::../examples/the_api/register_type/register_type_property_metamethod_predec.zs[]
----

Output:

[source,text]
----
include::../examples/the_api/register_type/register_type_property_metamethod_predec_out.txt[]
----




==== Register properties

