= 5 Modules

Zetscript implements the following modules,

* String
* Console
* System
* Math
* Json
* DateTime

== 5.1 String

String module exposes the following set of functions,

* String::format

=== 5.1.1 String::format

String::format formats a string

Syntax,
[source,zetscript]
String::format("string", ...args)

The possible formats is described below,


[cols="1m,3d,4a"]
|====
|Format |description |Example
|{n}
|It replaces {_n_} by the argument _n_
|
[source,zetscript]
----
 // prints '1st arg 1'
 String::format("1st arg {0}",1)

 // prints '1st,2nd as 1 and 2'
 String::format("1st,2nd as {0} and {1}",1,2)

 // prints '1st,2nd same 1 and 1'
 String::format("1st,2nd same {0} and {0}",1)
----

|{n:dm}
|It replaces the argument _n_ padding _m_ 0s on its left
|
[source,zetscript]
----
 // out == 'Score:01'
 String::format("Score:{0:d1}",1)

 // out == 'Score:0001'
 String::format("Score:{0:d4}",1)
----

|{n,m}
|It replaces argument _n_ padding _m_ spaces on its left
|
[source,zetscript]
----
 // out == 'Score: 1'
 var out=String::format("Score:{0,1}",1)
 // out == 'Score:   1'
 out=String::format("One space:{0,4}",1)
----

 
|====


== 5.2 Console

Console module exposes the following set of functions,

* outln
* errorln
* readChar

== 5.2.1 Console::outln

Console::outln prints message to the console.

Syntax,

[source,zetscript]
Console::outln(object,...args)

If _object_ is constant string it can be formated (see in table X.X)

Example,

[source,zetscript]
----
 // prints 'Hello world'
 Console::outln("Hello world");
 
 // prints 'Score:0001'
 Console::outln("Score:{0:d4}",1);  
  
----

== 5.2.2 Console::errorln

Console::errorln prints an error message to the console.

Syntax,

[source,zetscript]
Console::errorln(object,...args)

If _object_ is constant string it can be formated (see in table X.X)

Example,

[source,zetscript]
----
 // prints 'Error'
 Console::errorln("Error");
 
 // prints 'Error:02'
 Console::outln("Error:{0:d2}",2);  
  
----

== 5.2.3 Console::readChar

Console::readChar it waits untill reads a character from console

Syntax,

[source,zetscript]
Console::readChar()

Example,

[source,zetscript]
----
 // waits until reads a char
 var c=Console::readChar();
 
 // prints readed char
 Console::outln("Key pressed: {0}",c) 
  
----


== 5.3 System

System module exposes the following set of functions,

* clock
* eval
* assert
* error


== 5.3.1 Clock

Returns the amount of time in milliseconds

Syntax,

[source,zetscript]
System::clock()

Example,

[source,zetscript]
----
 var start=System::clock()

 // waste some time...
 for(var i=0;i<1000; i++){
 }

 // print elapsed time in milliseconds
 Console::outln("Elapsed time: {0} ms",System::clock()-start_time)
----

== 5.3.2 Eval


== 5.3.3 Assert


== 5.3.4 Error






== 5.4 Math

Math module exposes the following set of static members,

* PI: PI number (i.e 3.14159265359)

Math module exposes the following set of static functions,

* sin
* cos
* abs
* pow
* degToRad
* random
* max
* min
* sqrt
* floor
* ceil
* round


== 5.4.1 Math::sin

== 5.4.2 Math::cos

== 5.4.3 Math::abs

== 5.4.4 Math::pow

== 5.4.5 Math::degToRad

== 5.4.6 Math::random

== 5.4.7 Math::max

== 5.4.8 Math::min

== 5.4.9 Math::sqrt

== 5.4.10 Math::floor

== 5.4.11 Math::ceil

== 5.4.12 Math::round


== 5.5 Json

Json exposes the following set of static members,

* serialize
* deserialize

== 5.5.1 Json::serialize

== 5.5.2 Json::serialize

== 5.6 DateTime

Json exposes the following set of member variables,

//-> maybe a table

* week_day (zs_int): The week's day
* month_day (zs_int): The month's day
* year_day (zs_int): The year's day

* second (zs_int): seconds
* minute (zs_int): minutes
* hour (zs_int): hours

* day (zs_int): day
* month (zs_int):month
* year (zs_int): year


Json exposes the following set of member functions,

* addSeconds
* addMinutes
* addHours
* addDays
* addMonths
* addYears

Json exposes the following set of member metamethods,

* _add
* _sub
* _toString

== 5.6.1 DateTime::addSeconds

== 5.6.2 DateTime::addMinutes

== 5.6.3 DateTime::addHours

== 5.6.4 DateTime::addDays

== 5.6.5 DateTime::addMonths

== 5.6.6 DateTime::addYears

== 5.6.7 DateTime::_add

== 5.6.8 DateTime::_sub

== 5.6.9 DateTime::_toString

