
==== Properties

ZetScript API allows to register class properties as we could see in <<language_class.adoc#_properties,Language Class Properties>>.


===== Register constant property

Returns a constant property.

*Syntax*

[source,javascript]
----
ReturnType RegisteredTypeProperty_get(ScriptEngine *_script_engine, RegisteredType *_this)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance.
- ___this__ : The current instance.

[.underline]#Returns#

Returns the value of the property

*Example*

The following code defines a function that returns the _value_ contents of current instance,

[source,cpp]
----

zs_float NumberZs_MAX_VALUE_get(ScriptEngine *_script_engine,Number *_this){
	return FLT_MAX;
}

----

Next, the function _NumberZs_MAX_VALUE_get_ is registered through _ScriptEngine::registerConstMemberProperty_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerConstMemberProperty<Number>("MAX_VALUE",NumberZs_MAX_VALUE_get);

	//...

}
----

Finally, the following code it shows an example of a script that returns _Number::MAX_VALUE_ property,

[source,javascript]
----
include::../examples/api/register_type/register_constant_member_property.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_constant_member_property_out.txt[]
----

<<<

===== Register property metamethods

====== _addassign()

Implements _addition assignment_ operator (aka += ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_addassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _addassign_ to _value_ variable of current instance,

[source,cpp]
----
void NumberZs_value_addassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value+=*_value;
}
----

Next, the function _NumberZs_value_addassign_ is registered as member metamethod __addassign__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_addassign",NumberZs_value_addassign));

	//...

}
----

Finally, the following code it shows an example of a script that performs a __addassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_addassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_addassign_out.txt[]
----

<<<


====== _andassign()

Implements __bitwise AND assignment__ operator (aka &= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_andassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and __andassign__ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_andassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)&(int)(*_value);
}
----

Next, the function __NumberZs_value_andassign__ is registered as member metamethod __andassign__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_andassign",NumberZs_value_andassign);
	
	//...

}
----

Finally, the following code it shows an example of a script that performs a __andassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_andassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_andassign_out.txt[]
----

<<<

====== _divassign()

Implements __division assignment__ operator (aka /= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_divassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and __divassign__ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_divassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value/=*_value;
}
----

Next, the function __NumberZs_value_divassign__ is registered as member metamethod __divassign__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_divassign",NumberZs_value_divassign);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __divassign__ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_divassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_divassign_out.txt[]
----

<<<

====== _get()

___get__ returns the value of the property

*Syntax*

[source,javascript]
----
ReturnType RegisteredTypeProperty_get(ScriptEngine *_script_engine, RegisteredType *_this)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance

[.underline]#Returns#

Returns the value of the property

*Example*

The following code defines a function as a __get__ property operation that returns the _value_ contents of current instance,

[source,cpp]
----

zs_float NumberZs_value_get(ScriptEngine *_script_engine,Number *_this){
	return _this->value;
}

----

Next, the function __NumberZs_value_get__ is registered as member metamethod __get__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_get",NumberZs_value_get);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __get__ operation from __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_get.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_get_out.txt[]
----

<<<


====== _modassign()

Implements _modulus assignment_ operator (aka %= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_modassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and __modassign__ to __value__ variable of current instance,

[source,cpp]
----
void NumberZs_value_modassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value=fmod(_this->value,*_value);
}
----

Next, the function __NumberZs_value_modassign__ is registered as member metamethod __addassign__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_modassign",NumberZs_value_modassign);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __modassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_modassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_modassign_out.txt[]
----

<<<

====== _mulassign()

Implements __multiplication assignment__ operator (aka *= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_mulassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.

[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and __mulassign__ to __value__ variable of current instance,

[source,cpp]
----

void NumberZs_value_mulassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value*=*_value;
}

----

Next, the function __NumberZs_value_mulassign__ is registered as member metamethod __mulassign__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_mulassign",NumberZs_value_mulassign);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __mulassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_mulassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_mulassign_out.txt[]
----

<<<


====== _orassign()

Implements __bitwise OR assignment__ operator (aka |= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_orassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and __orassign__ to __value__ variable of current instance,

[source,cpp]
----

void NumberZs_value_orassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)|(int)(*_value);
}
----

Next, the function _NumberZs_value_orassign_ is registered as member metamethod __orassign__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_orassign",NumberZs_value_orassign);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __orassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_orassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_orassign_out.txt[]
----

<<<


====== _postdec()

Implements __post_decrement__ operator (aka a-- ) 

*Syntax*

[source,javascript]
----
ReturnType  RegisteredType_value_postdec(ScriptEngine *_script_engine, RegisteredType *_this);
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance

[.underline]#Returns#

Return the value before perform post decrement operation. The return value can be one defined in <<api_call_cpp_from_zetscript.adoc#_return_types,return types>>.

*Example*

The following code defines a function that performs a __postdec__ of current instance,

[source,cpp]
----

zs_float  NumberZs_value_postdec(ScriptEngine *_script_engine,Number *_this){
	return _this->value--;
}

----

Next, the function __NumberZs_value_postdec__ is registered as member metamethod __postdec__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberFunction<Number>("_postdec",NumberZs_postdec);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __postdec__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_postdec.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_postdec_out.txt[]
----

<<<

====== _postinc()

Implements __post_increment__ operator (aka a++ ) 

*Syntax*

[source,javascript]
----
ReturnType  RegisteredType_value_postinc(ScriptEngine *_script_engine, RegisteredType *_this);
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance

[.underline]#Returns#

Return the value before perform post increment operation. The return value can be one defined in <<api_call_cpp_from_zetscript.adoc#_return_types,return types>>.

*Example*

The following code defines a function that performs a __postinc__ of current instance,

[source,cpp]
----

zs_float  NumberZs_value_postinc(ScriptEngine *_script_engine,Number *_this){
	return _this->value++;
}

----

Next, the function __NumberZs_value_postinc__ is registered as member metamethod __postinc__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberFunction<Number>("_postinc",NumberZs_postinc);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __postinc__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_postinc.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_postinc_out.txt[]
----

<<<

====== _predec()

[source,javascript]
----
ReturnType  RegisteredType_value_predec(ScriptEngine *_script_engine, RegisteredType *_this);
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance

[.underline]#Returns#

Return the value before perform pre decrement operation. The return value can be one defined in <<api_call_cpp_from_zetscript.adoc#_return_types,return types>>.

*Example*

The following code defines a function that performs a _predec_ of current instance,

[source,cpp]
----

zs_float  NumberZs_value_predec(ScriptEngine *_script_engine,Number *_this){
	return --_this->value;
}
----

Next, the function __NumberZs_value_predec__ is registered as member metamethod __predec__ through __ScriptEngine::registerMemberPropertyMetamethod__,


[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_predec",NumberZs_value_predec);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __predec__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_predec.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_predec_out.txt[]
----

<<<

====== _preinc()

Implements __pre_increment__ operator (aka ++a ) 

*Syntax*

[source,javascript]
----
ReturnType  RegisteredType_value_preinc(ScriptEngine *_script_engine, RegisteredType *_this);
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance

[.underline]#Returns#

Return the value before perform pre increment operation. The return value can be one defined in <<api_call_cpp_from_zetscript.adoc#_return_types,return types>>.

*Example*

The following code defines a function that performs a __preinc__ of current instance,

[source,cpp]
----
zs_float  NumberZs_value_preinc(ScriptEngine *_script_engine,Number *_this){
	return ++_this->value;
}
----

Next, the function __NumberZs_value_preinc__ is registered as member metamethod __preinc__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_preinc",NumberZs_value_preinc);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __preinc__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_preinc.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_preinc_out.txt[]
----

<<<

====== _set()

Implements _assignment_ operator (aka = ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_set(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.

[.underline]#Returns#

None.

*Example*

The following code defines a function that performs a __set__ to __value__ variable of current instance,

[source,cpp]
----

void NumberZs_value_set(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value=*_value;
}
----

Next, the function __NumberZs_value_set__ is registered as member metamethod __set__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_set",NumberZs_value_set);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __set__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_set.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_set_out.txt[]
----

<<<

====== _shlassign()

Implements __bitwise SHIFT LEFT assignment__ operator (aka <<= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_shlassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and __shlassign__ to __value__ variable of current instance,

[source,cpp]
----

void NumberZs_value_shlassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)<<(int)(*_value);
}
----

Next, the function __NumberZs_value_shlassign__ is registered as member metamethod __shlassign__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_shlassign",NumberZs_value_shlassign);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __shlassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_shlassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_shlassign_out.txt[]
----

<<<

====== _shrassign()

Implements __bitwise SHIFT RIGHT assignment__ operator (aka >>= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_shrassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and __shrassign__ to __value__ variable of current instance,

[source,cpp]
----

void NumberZs_value_shrassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)>>(int)(*_value);
}
----

Next, the function __NumberZs_value_shrassign__ is registered as member metamethod __shrassign__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_shrassign",NumberZs_value_shrassign);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __shrassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_shrassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_shrassign_out.txt[]
----

<<<

====== _subassign()

Implements __substraction assignment__ operator (aka -= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_subassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs a __subassign__ to __value__ variable of current instance,

[source,cpp]
----

void NumberZs_value_subassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value-=*_value;
}

----

Next, the function __NumberZs_value_subassign__ is registered as member metamethod __subassign__ through __ScriptEngine::registerMemberPropertyMetamethod__,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_subassign",NumberZs_value_subassign);

	//...

}
----

Finally, the following code it shows an example of a script that performs a __subassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_subassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_subassign_out.txt[]
----

<<<

====== _xorassign()

Implements __bitwise XOR assignment__ operator (aka ^= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_xorassign(ScriptEngine *_script_engine, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- ___script_engine__ : ScriptEngine instance
- ___this__ : The current instance
- ___value__ : Value or variable as right operand. Its type can be one defined in <<api_call_cpp_from_zetscript.adoc#_parameter_types,parameter types>>.


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _xorassign_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_xorassign(ScriptEngine *_script_engine,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)^(int)(*_value);
}
----

Next, the function _NumberZs_value_xorassign_ is registered as member metamethod __xorassign__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_script_engine){

	//...

	_script_engine->registerMemberPropertyMetamethod<Number>("value","_xorassign",NumberZs_value_xorassign);

	//...

}

----

Finally, the following code it shows an example of a script that performs a __xorassign__ operation to __Number::value__ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_xorassign.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_xorassign_out.txt[]
----

