
=== Data types

This section will describe the data types used in the ZetScript API that  interops within both native and script environments. Some of the types described has methods and properties that usually are used internally by the ZetScript API and in order to simply the documentation won't be described.

==== zs_int

Integer data type it defines a integer variable with range from -(2^b-1^) to 2^b-1^-1 where b=32 or b=64 it depending whether ZetScript is compiled for 32bits or 64bits. 

*Example*

[source,cpp]
----
zetscript::zs_int i=10;
----

==== zs_float

_zs_float_ type it defines a float variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits.

*Example*

[source,cpp]
----
zetscript::zs_float f=20.5;
----

==== zs_string

_zs_string_ it defines a string represented a sequence of chars

===== Constructor

The zs_string constructor creates a new zs_tring as empty or initialized with other string or zs_string.

*Syntax*

[source,cpp]
----
zs_string();
zs_string(const char * _s);
zs_string(const zs_string & _str);
zs_string(zs_string && _str);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : A zs_string object.


*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_constructor_out.txt[]
----

===== Static constants

====== zs_string::n_pos

npos is a static member constant value with the greatest possible value.

===== Member functions

====== zs_string::length()

Returns the length of the string, in terms of bytes.

*Syntax*

[source,cpp]
----
int length() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of bytes in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_length.cpp[]
----

Console output:

[source,cpp]
----
include::../examples/api/types/zs_string_length_out.txt[]
----


====== zs_string::empty()

Returns whether the string is empty.

*Syntax*

[source,cpp]
----
bool empty() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

true if the string length is 0, false otherwise.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_empty.cpp[]
----

Console output:

[source,cpp]
----
include::../examples/api/types/zs_string_empty_out.txt[]
----

====== zs_string::c_str()

Returns a pointer to an array that contains a null-terminated sequence of characters (i.e., a C-string) representing the current value of the string object.

*Syntax*

[source,cpp]
----
const char * c_str() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

A pointer of characters of the string object's value.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_c_str.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_c_str_out.txt[]
----

====== zs_string::operator=()

Assigns a new value to the string, replacing its current contents.

*Syntax*

[source,cpp]
----
zs_string& operator=(const zs_string & _str);
zs_string& operator=(zs_string && _str);
zs_string& operator=(const char* _s);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : A zs_string object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_operator_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_operator_assign_out.txt[]
----

======  zs_string::operator+=()

Appends string at the end of current contents.

*Syntax*

[source,cpp]
----
zs_string& operator+=(const zs_string& _string);
zs_string& operator+=(const char* _string);
zs_string& operator+=(char _char);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : zs_string object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_operator_add_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_operator_add_assign_out.txt[]
----

====== zs_string::operator[]()

Returns a reference to the character from a position.

*Syntax*

[source,cpp]
----
char& operator[] (int _pos);
const char& operator[] (int _pos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The character at the specified position in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_operator_access.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_operator_access_out.txt[]
----

====== zs_string::at()

Returns a reference to the character at position __pos_.

*Syntax*

[source,cpp]
----
char& at (int _pos);
const char& at (int _pos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The character at the specified position in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_at.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_at_out.txt[]
----

====== zs_string::clear()

Erases the contents of the string.

*Syntax*

[source,cpp]
----
void clear();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_clear.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_clear_out.txt[]
----

====== zs_string::substr()

Returns a new string with its value initialized to a copy of a substring of this object.

*Syntax*

[source,cpp]
----
zs_string  substr (int _pos = 0, int _len = npos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be copied as a substring.
- _&#95;len_ : Number of characters to include in the substring. As default it passes zs_string::npos that indicates it will take all characters until the end of the string.

[.underline]#Return#

A string with a substring of this object.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_substr.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_substr_out.txt[]
----

======  zs_string::find()

Searches the string for the first occurrence of the sequence specified by its arguments.

*Syntax*

[source,cpp]
----
int find(const zs_string & _str, int _pos = 0) const;
int find(const char *_s, int _pos = 0) const;
----

[.underline]#Parameters#

- _&#95;s_ :  A pointer to an array of characters.
- _&#95;str_ : A zs_string object.
- _&#95;pos_ : Position of the first character in the string to be considered in the search.

[.underline]#Return#

The position of the first character of the first match. If no matches were found, the function returns zs_string::npos

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_find.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_find_out.txt[]
----

====== zs_string::find_last_of()

Searches the string for the last character that matches any of the characters specified in its arguments.


*Syntax*

[source,cpp]
----
int find_last_of(const char *_s, int _pos = npos) const;
int find_last_of(const zs_string & _str, int _pos = npos) const;
----

[.underline]#Parameters#

- _&#95;str_ : A zs_string object.
- _&#95;s_ :  A pointer to an array of characters.
- _&#95;pos_ : Position of the last character in the string to be considered in the search.


[.underline]#Return#

The position of the last character that matches. If no matches are found, the function returns string::npos.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_find_last_of.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_find_last_of_out.txt[]
----

====== zs_string::replace()

Replaces the portion of the string.

*Syntax*

[source,cpp]
----
zs_string & replace(int _pos, int _len, const zs_string & _to_replace);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be replaced.
- _&#95;len_ : Number of characters to replace. A value of string::npos indicates all characters until the end of the string.
- _&#95;str_ : A zs_string object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_replace.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_replace_out.txt[]
----


====== zs_string::append()

Appends a character o string at the end of current contents.

*Syntax*

[source,cpp]
----
void append(char _c);
void append(const char * _s);
void append(const char *_s, int _len);
void append(const zs_string & _str);

----

[.underline]#Parameters#

- _&#95;c_ : The character to append.
- _&#95;s_ : A pointer to array of characters.
- _&#95;len_ : The length of number of characters to copy.
- _&#95;str_ : A zs_string object.


[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_append.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_append_out.txt[]
----


====== zs_string::erase()

Erases part of the string, reducing its length.

*Syntax*

[source,cpp]
----
void erase(int _pos, int _len);
void erase(int _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be erased.
- _&#95;len_ : Number of characters to erase.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_erase.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_erase_out.txt[]
----


====== zs_string::insert()

Inserts additional characters into the string right before the character indicated by _&#x5f;pos_.

*Syntax*

[source,cpp]
----
void insert(int _pos, char _char);
void insert(int _pos, const zs_string & _string);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to insert.
- _&#95;c_ : The character to insert.
- _&#95;str_ : The characters from zs_string object to insert.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_insert.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_insert_out.txt[]
----

===== Static functions

====== zs_string::operator+()

Returns a new string object with its value being the concatenation of the characters in left operand followed by those of right operand.

*Syntax*

[source,cpp]
----
friend zs_string operator+(const zs_string & _s1, const zs_string &_s2);
friend zs_string operator+(const zs_string & _s1, const char *_s2);
friend zs_string operator+(const char * _s1, const zs_string & _s2);

friend zs_string operator+(const zs_string & _s1, char _s2);
friend zs_string operator+(char  _s1, const zs_string & _s2);
----

[.underline]#Parameters#

- _&#95;s1_ : A char, pointer to array of characters or zs_string object as left operand.
- _&#95;s2_ : A char, pointer to array of characters or zs_string object as right operand.

[.underline]#Return#

A string whose value is the concatenation of &#95;s1 and &#95;s2.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_operator_add.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_operator_add_out.txt[]
----

====== Relational operators

zs_string implements the EQUAL (aka ==) and NOT EQUAL (aka !=) comparison operation between the left operand and right operand.

*Syntax*

[source,cpp]
----
friend bool operator _REL_OPERATOR_(const zs_string & _s1, const zs_string &_s2);
friend bool operator _REL_OPERATOR_(const zs_string & _s1, const char *_s2);
friend bool operator _REL_OPERATOR_(const char * _s1, const zs_string & _s2);
----

Where &#95;REL_OPERATOR&#95; can be *==* or *!=*

[.underline]#Parameters#

- _&#95;s1_ : A pointer to array of characters or zs_string object as left operand.
- _&#95;s2_ : A pointer to array of characters or zs_string object as right operand.

[.underline]#Return#

true if satisfies the condition &#95;s1 _R &#95;s2 and false otherwise.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_relational_operators.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_relational_operators_out.txt[]
----

==== zs_vector

_zs_vector_ it defines a unidimensional vector of elements of type defined on its template parameter. 


===== Constructor

The zs_vector constructor creates a new zs_vector as empty or initialized with other zs_vector.

[source,cpp]
----
zs_vector();
zs_vector(const zs_vector & _vector);
----

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_constructor_out.txt[]
----

[.underline]#Parameters#

- _&#95;vector_ : A vector object.

===== Static constants

====== zs_vector::n_pos

npos is a static member constant value with the greatest possible value.

===== Member functions

====== zs_vector::push_back()

Appends an element at the end of current contents.

*Syntax*

[source,cpp]
----
bool 		push_back( const _T & _element);
----

[.underline]#Parameters#

- _&#95;element_ : The element to append.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_push_back.cpp[]
----

====== zs_vector::size()

Returns the number of elements of the vector. 

*Syntax*

[source,cpp]
----
int	size() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of elements in the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_size.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_size_out.txt[]
----

====== zs_vector::set()

Replaces the element from a position.

*Syntax*

[source,cpp]
----
void 		set( int  _pos_, const _T & _element);
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.
- _&#95;element_ : The element to replace.

[.underline]#Return#

none

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_set.cpp[]
----

====== zs_vector::get()

Returns a reference to the element from a position.

*Syntax*

[source,cpp]
----
const _T &	get( int  _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The element at the specified position in the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_get_out.txt[]
----

====== zs_vector::pop_back()

Returns the last element by copy and erases the last element.

*Syntax*

[source,cpp]
----
void    		pop_back();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_pop_back.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_pop_back_out.txt[]
----

====== zs_vector::operator=()

Replaces current content by the set of elements from other vector.

*Syntax*

[source,cpp]
----
zs_vector& operator=(const zs_vector& _vector);		
----

[.underline]#Parameters#

- _&#95;vector_ : A vector object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_operator_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_operator_assign_out.txt[]
----


====== zs_vector::erase()

Erases an element from a position.

*Syntax*

[source,cpp]
----
void 		erase( int  _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the element to be erased.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_erase.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_erase_out.txt[]
----

====== zs_vector::concat()

Copies all elements from other vector at the end of current contents.

*Syntax*

[source,cpp]
----
void 		concat(const zs_vector<_T>  & _vector);
----

[.underline]#Parameters#

- _&#95;vector_ : A vector object.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_concat.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_concat_out.txt[]
----

====== zs_vector::insert()        

Inserts an element or copies all elements of other vector from a position.

*Syntax*

[source,cpp]
----
void 		insert(int _pos,const _T & _element);
void 		insert(int _pos,const zs_vector<_T>  & _vector, int _len=npos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first element to insert.
- _&#95;vector_ : The elements of vector source to insert.
- _&#95;len_ : The number of elements to insert. A value of zs_vector::npos indicates all elements until the end of the vector.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_insert.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_insert_out.txt[]
----

====== zs_vector::clear()

Erases the contents of the vector.

*Syntax*

[source,cpp]
----
void 		clear();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_clear.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_clear_out.txt[]
----

====== zs_vector::resize()

Resizes the vector by a length.

*Syntax*

[source,cpp]
----
void    	resize(int _len);
----

[.underline]#Parameters#

- _&#95;len_ : The new capacity of the vector.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_resize.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_resize_out.txt[]
----


====== zs_vector::data()

Returns the pointer to the array of the elements.

*Syntax*

[source,cpp]
----
_T *data();
----

[.underline]#Parameters#

None

[.underline]#Return#

A pointer of elements of the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_data.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_data_out.txt[]
----

==== ScriptType

ScriptType is an type managed by ZetScript that defines a builtin or registered script type. ScriptType has the following fields.

- id: id script type
- name: Name script type
- scope: Scope of script type
- native_name: Native name of script type
- properties: A integer value composed of the following mask values,  

[cols="1d,2m,2d"]
|====
|Name |Mask value|Description

|ZS_SCRIPT_TYPE_PROPERTY_C_OBJECT_REF		
|0x1
|It tells script type is native

|ZS_SCRIPT_TYPE_PROPERTY_NON_INSTANTIABLE	
|0x2
|it tells script type is static or not instantiable

|====

==== Scope

Scope is an type managed internally by ZetScript that defines the variables, types or functions in a scope. Symbol type has the following fields.

- script_type_owner: Script type owner
- scope_parent: Scope parent
- scope_base: Scope root
- symbol_variables: List of symbols as the variables defined in the scope.
- symbol_functions: List of symbols as the functions defined in the scope.
- symbol_types: List of symbols as the types defined in the scope.
- properties: A integer value composed of the following mask values,  

[cols="1d,2m,2d"]
|====
|Name |Mask value|Description

|ZS_SCOPE_PROPERTY_IS_C_OBJECT_REF
|0x01
|Tells that scope is native

|ZS_SCOPE_PROPERTY_IS_SCOPE_FUNCTION
|0x02
|Tells that scopes references a function

|ZS_SCOPE_PROPERTY_IS_SCOPE_CLASS
|0x04
|Tells that scope references a class

|ZS_SCOPE_PROPERTY_IS_SCOPE_BLOCK|
|0x08
|Tells that scope references a block 

|ZS_SCOPE_PROPERTY_UNUSUED
|0x10
|Tells that scope is unused

|====


==== Symbol

_Symbol_ is a type managed internally by ZetScript that defines a symbol. The _Symbol_ type has the following fields:

- scope : scope where symbol was registered
- name: symbol name
- ref_ptr: Pointer reference that holds information about the instance of symbol type.
- n_params; Number of parameters in case the symbol is refers a function.
- properties: A integer value composed of the following mask values,  

[cols="1d,2m,2d"]
|====
|Name |Mask value|Description
|ZS_SYMBOL_PROPERTY_C_OBJECT_REF
|0x0001
|ref_ptr holds C object

|ZS_SYMBOL_PROPERTY_STATIC
|0x0002
|C function or C++ static functions

|ZS_SYMBOL_PROPERTY_TYPE
|0x0004
|symbol is type

|ZS_SYMBOL_PROPERTY_FUNCTION
|0x0008
|ref_ptr holds script function ptr

|ZS_SYMBOL_PROPERTY_CONST
|0x0010
|This symbol is not assignable
	
|ZS_SYMBOL_PROPERTY_MEMBER_PROPERTY
|0x0020
|Member attrib

|ZS_SYMBOL_PROPERTY_ARG_BY_REF
|0x0040
|Is a reference

|ZS_SYMBOL_PROPERTY_ALLOCATED_STK
|0x0080
|Is a reference

|====

==== StackElement

StackElement is the data used by the VirtualMachine.  StackElement contents _value and _properties_ fields that defines the type of StackElement and how to fetch its contents in function of its properties.

[cols="1d,2m,2d"]
|====
|Name |Mask value|Description

|ZS_STK_PROPERTY_UNDEFINED
|0x0000
|Its value is 0 defined as *Undefined* type

|ZS_STK_PROPERTY_NULL
|0x0001
|Its value is 0 defined as *Null* type

|ZS_STK_PROPERTY_CHAR_PTR
|0x0002
|Its value is a *const char &#42;* type

|ZS_STK_PROPERTY_INT
|0x0004
|Its value is a *zs_int* type
		
|ZS_STK_PROPERTY_FLOAT
|0x0008
|Its value is a *zs_float &#42;* type 

|ZS_STK_PROPERTY_BOOL
|0x0010
|Its value is a *bool* type 

|ZS_STK_PROPERTY_INDEX_CLASS_TYPE
|0x0020
|Its value a zs_int as the index of a defined or registered Class

|ZS_STK_PROPERTY_FUNCTION
|0x0040
|Its value is *Symbol &#42;* as the symbol that refers a *ScriptFunction &#42;* of a function in _ref_ptr_ field

|ZS_STK_PROPERTY_MEMBER_FUNCTION
|0x0080
|Its value is *Symbol &#42;* as the symbol that refererences a *ScriptFunction &#42;* of a member function in _ref_ptr_ field

|ZS_STK_PROPERTY_MEMBER_PROPERTY
|0x0100
|Its value is a *StackElementMemberProperty &#42;*

|ZS_STK_PROPERTY_SCRIPT_OBJECT
|0x0200
|Its value is a *ScriptObject &#42;*

|ZS_STK_PROPERTY_CONTAINER_SLOT
|0x0400
|Its value is a *ContainerSlot &#42;*

|ZS_STK_PROPERTY_PTR_STK
|0x0800
|Its value is a *StackElement &#42;*
		
|ZS_STK_PROPERTY_READ_ONLY
|0x1000
|StackElement is defined as read only

|====


==== ScriptObject

_ScriptObject_ defines a the parent class of any object in TypeScript. This type is usually used internally by ZetScript. The _ScriptObject_ type has the following fields:

- script_type_id: The script type representated by the instance of script object.
- properties: A integer value composed of the following mask values,  

[cols="1d,2m,2d"]
|====
|Name |Mask value|Description
|ZS_SCRIPT_OBJECT_PROPERTY_CONSTANT
|0x1
|Tells if ScriptObject represents a constant object

|====

==== StringScriptObject

_StringScriptObject_ defines a string script object.

===== Constructor

The StringScriptObject constructor creates a new string script object as empty or initialized with a string.  The StringScriptObject constructor needs a ZetScript context.

*Syntax*

[source,cpp]
----
StringScriptObject(ZetScript *_zs, const zs_string & _str="");
----

[.underline]#Parameters#

- _&#95;zs_ : ZetScript instance.
- _&#95;str_ : String value as a initialize value (empty by default).

*Example*

[source,cpp]
----
include::../examples/api/types/string_script_object_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_script_object_constructor_out.txt[]
----

===== Member functions

====== StringScriptObject::set()

Replaces current string value.

*Syntax*

[source,cpp]
----
void set(const zs_string & _str);
----

[.underline]#Parameters#

- _&#95;str_ : The string value.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/string_script_object_set.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_script_object_set_out.txt[]
----

====== StringScriptObject::get()

Gets its current string value as zs_string or array of characters

*Syntax*

[source,cpp]
----
const zs_string & get();
----

[.underline]#Parameters#

None

[.underline]#Return#

Its contents as string as zs_string

*Example*

[source,cpp]
----
include::../examples/api/types/string_script_object_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_script_object_get_out.txt[]
----

====== StringScriptObject::getConstChar()

Gets its current string value as array of characters

*Syntax*

[source,cpp]
----
const char *getConstChar();
----

[.underline]#Parameters#

None

[.underline]#Return#

Its contents as string as array of characters

*Example*

[source,cpp]
----
include::../examples/api/types/string_script_object_get_const_char.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_script_object_get_const_char_out.txt[]
----

====== StringScriptObject::toString()

Gets its current string value

*Syntax*

[source,cpp]
----
zs_string toString();
----

[.underline]#Parameters#

None

[.underline]#Return#

Its contents as string as zs_string

*Example*

[source,cpp]
----
include::../examples/api/types/string_script_object_to_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_script_object_to_string_out.txt[]
----

====== StringScriptObject::length()

Returns the length of the string, in terms of bytes.

*Syntax*

[source,cpp]
----
virtual int length();
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of bytes in the string.

[source,cpp]
----
include::../examples/api/types/string_script_object_length.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_script_object_length_out.txt[]
----
		
==== ArrayScriptObject

_ArrayScriptObject_ it defines a array script object.

===== Contructor

The ArrayScriptObject constructor creates a new array script object. ArrayScriptObject constructor needs a ZetScript context.

*Syntax*

[source,cpp]
----
ArrayScriptObject(ZetScript *_zs);
----

[.underline]#Parameters#

- _&#95;zs_ : ZetScript instance.

*Example*

[source,cpp]
----
include::../examples/api/types/array_script_object_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_script_object_constructor_out.txt[]
----

===== Member functions

====== ArrayScriptObject::push()

Appends _&#x5f;value_  of type _&#x5f;T_ at the end of array.

*Syntax*

[source,cpp]
----
void push(_T _element);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;element_ : The element to append.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/array_script_object_push.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_script_object_push_out.txt[]
----

====== ArrayScriptObject::length()

Returns the number of the elements of the array.

*Syntax*

[source,cpp]
----
int length();
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of elements in the array.

[source,cpp]
----
include::../examples/api/types/string_array_object_length.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_array_object_length_out.txt[]
----

====== ArrayScriptObject::set()

Replaces current value at position _&#x5f;pos_ by _&#x5f;value_ of type _&#x5f;T_. 

*Syntax*

[source,cpp]
----
void set<_T>(int _pos, _T _element);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.
- _&#95;element_ : The element to replace.

[.underline]#Return#

None


*Example*


[source,cpp]
----
include::../examples/api/types/array_script_object_set.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_script_object_set_out.txt[]
----

====== ArrayScriptObject::elementInstanceOf()

Says whether the element at a position is instance of zetscript data type or a registered type.

*Syntax*

[source,cpp]
----
bool 	elementInstanceOf<_T>(int _pos);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

Returns true if the element at position _&#95;pos_ it type or extends from type _&#95;T_

*Example*

[source,cpp]
----
include::../examples/api/types/array_script_object_element_instanceof.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_script_object_element_instanceof_out.txt[]
----


====== ArrayScriptObject::get()

Returns a reference element of type _&#x5f;T_ at position __pos_.

*Syntax*

[source,cpp]
----
_T 	get(int _pos);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The element at the specified position in the array.

*Example*

[source,cpp]
----
include::../examples/api/types/array_script_object_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_script_object_get_out.txt[]
----

====== ArrayScriptObject::toString()

Returns a string as the array contents in json format.

*Syntax*

[source,cpp]
----
zs_string toString();
----

[.underline]#Parameters#

None

[.underline]#Return#

A string of the array contents in json format.

*Example*

[source,cpp]
----
include::../examples/api/types/array_script_object_tostring.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_script_object_tostring_out.txt[]
----

==== ObjectScriptObject

_ObjectScriptObject_ it defines a array script object.

===== Contructor

The ObjectScriptObject constructor creates a new object script object. ObjectScriptObject constructor needs a ZetScript context.


*Syntax*

[source,cpp]
----
ObjectScriptObject(ZetScript *_zs);
----

[.underline]#Parameters#

- _&#95;zs_ : ZetScript instance.

*Example*

[source,cpp]
----
include::../examples/api/types/object_script_object_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_script_object_constructor_out.txt[]
----


===== Member functions


====== ObjectScriptObject::set()

Replaces current value at key _&#x5f;key_ by _&#x5f;value_ of type _&#x5f;T_.

*Syntax*

[source,cpp]
----
void ObjectScriptObject::set(int _key, _T _element)
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;key_ : The string value as the key.
- _&#95;element_ : The element to replace.

[.underline]#Return#

None


*Example*

[source,cpp]
----
include::../examples/api/types/object_script_object_set.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_script_object_set_out.txt[]
----

====== ObjectScriptObject::elementInstanceOf()

Says whether the element is instance of zetscript data type or a registered type.

*Syntax*

[source,cpp]
----
bool 	elementInstanceOf<_T>(const zs_string & _key);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;key_ : The string value as the key.

[.underline]#Return#

Returns true if the element at key _&#95;key_ it type or extends from type _&#95;T_

*Example*

[source,cpp]
----
include::../examples/api/types/object_script_object_element_instanceof.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_script_object_element_instanceof_out.txt[]
----

====== ObjectScriptObject::get()

Returns element of type _&#x5f;T_ at key __key_.

*Syntax*

[source,cpp]
----
_T 	get(const zs_string & _key);
----

====== ArrayScriptObject::get()

Returns a reference element at key.

*Syntax*

[source,cpp]
----
_T 	get(const zs_string & _key);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;key_ : The integer value as the position.

[.underline]#Return#

The element at the specified position in the array.

*Example*

[source,cpp]
----
include::../examples/api/types/object_script_object_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_script_object_get_out.txt[]
----

====== ObjectScriptObject::toString()

Returns a string as the object contents in json format.

*Syntax*

[source,cpp]
----
zs_string toString();
----

[.underline]#Parameters#

None

[.underline]#Return#

A string of the object contents in json format.

*Example*

[source,cpp]
----
include::../examples/api/types/object_script_object_tostring.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_script_object_tostring_out.txt[]
----

====== ArrayScriptObject::getKeys()

Returns a vector of strings as the keys of the Object.

*Syntax*

[source,cpp]
----
zs_vector<zs_string> getKeys();
----

[.underline]#Parameters#

None

[.underline]#Return#

A vector of strings as the keys of the Object.

*Example*

[source,cpp]
----
include::../examples/api/types/object_script_object_get_keys.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_script_object_get_keys_out.txt[]
----

==== ClassScriptObject

_ClassScriptObject_ it a subclass of _ObjectScriptObject_ that implements the _class_ type defined in ZetScript. Also it is used as a wrapper for instanced of registered C++ types.



template<typename _C>
_C to();


==== ScriptFunction

_ScriptFunction_ it defines a function object that contains function information. 

- id: id from factory
- name: function name
- scope: funcio


		// script type
		int 				return_script_type_id; 		// idx return type
		int					owner_script_type_id; 				// which type belongs to...

		uint16_t			properties;


typedef enum{
	FUNCTION_PROPERTY_C_OBJECT_REF			= 0x0001, // function is C
	FUNCTION_PROPERTY_STATIC				= 0x0002,
	FUNCTION_PROPERTY_MEMBER_FUNCTION		= 0x0004,// Member function
	FUNCTION_PROPERTY_DEDUCE_AT_RUNTIME		= 0x0008,// Deduce runtime functions becuse is C and it has functions with same name but different signature
}FunctionProperty;

==== ZetScript


===== ZetScript::eval()
		StackElement	eval(const zs_string & expresion,unsigned short _eval_options, const char * _script_file_by_ref="", const char *__invoke_file__="", int __invoke_line__=-1);

		StackElement	eval(const zs_string & expresion, const char *__invoke_file__="", int __invoke_line__=-1);


===== ZetScript::evalFile()
		StackElement	evalFile(const zs_string & _filename,unsigned short _eval_options=0, EvalData *_eval_data_from=NULL, const char *__invoke_file__="", int __invoke_line__=-1);


===== ZetScript::intToStackElement()

		StackElement   			intToStackElement(zs_int);

===== ZetScript::floatToStackElement()

		StackElement    		floatToStackElement(zs_float);

===== ZetScript::boolToStackElement()

		StackElement    		boolToStackElement(bool);

===== ZetScript::stackElementTo()
		template<typename _C>
		_C stackElementTo(StackElement   _stk);

===== ZetScript::stackElementToString()
		zs_string		stackElementToString(StackElement _stk,const zs_string & _format="");

===== ZetScript::stackElementToStringTypeOf()
		zs_string		stackElementToStringTypeOf(StackElement _stk);

===== ZetScript::toStackElement()
		template<typename _C>
		StackElement	toStackElement( _C _val);

===== newStringScriptObject();

		StringScriptObject * newStringScriptObject(const zs_string & _str="");

===== ZetScript::newObjectScriptObject()

		ObjectScriptObject * newObjectScriptObject();

===== ZetScript::newArrayScriptObject()
		ArrayScriptObject * newArrayScriptObject();

===== ZetScript::newClassScriptObject()

		template<typename _C>
		ClassScriptObject * newClassScriptObject(_C  *_instance=NULL);


===== ZetScript::registerConstant()


		void registerConstant(const zs_string & var_name, int value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, zs_float value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, bool value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, const zs_string & v, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, const char * v, const char *registered_file="", short registered_line=-1);

		// register object
		StackElement * registerStkConstantStringObject(const zs_string & _key,const zs_string & _value);

		StackElement * getStkConstantStringObject(const zs_string & _key);


===== ZetScript::registerType()

		template<typename T>
		ScriptType * registerType(
				const zs_string & name
				, T  * (*_new_native_instance)(ZetScript *_zs)=NULL
				, void (*_delete_native_instance)(ZetScript *_zs,T *)=NULL
				, const char *_registered_file="",short _registered_line=-1
		)


===== ZetScript::registerFunction()

		template <typename F>
		void registerFunction( const zs_string & _name_script_function,F ptr_function)

*Syntax*

[source,cpp]
----
void registerFunction( const zs_string & _function_name,F _c_function, const char *_registered_file="",short _registered_line=-1);
----

[.underline]#Parameters#

- __function_name_ : The function name to be refered in ZetScript.
- __c_function_ : The C function to register.
- __registered_file_ : Source file where the function was registered
- __registered_line_ : Line file where the function was registered


===== ZetScript::extends()

		template<class T, class B>
		void extends()

===== ZetScript::registerConstructor()        

		template<typename T,typename F>
		void registerConstructor(
				 F function_type
				 , const char *_registered_file=""
				,short _registered_line=-1
		)

===== ZetScript::registerMemberFunction()

		template <typename T,typename F>
		void	registerMemberFunction(
				const zs_string & _name_script_function
				,F function_type
				 , const char *_registered_file=""
				,short _registered_line=-1
		)

===== ZetScript::registerConstMemberProperty()        

		template <typename T,typename F>
		void	registerConstMemberProperty(
				const zs_string & _property_name
				,F ptr_function
				 , const char *_registered_file=""
				,short _registered_line=-1
		)


===== ZetScript::registerMemberPropertyMetamethod()

		template <typename T,typename F>
		void	registerMemberPropertyMetamethod(
				const zs_string & _property_name
				,const zs_string & _metamethod_name
				,F _ptr_function
				 , const char *_registered_file=""
				,short _registered_line=-1
		);

===== ZetScript::registerStaticMemberFunction()

		template <typename T,typename F>
		void registerStaticMemberFunction(const zs_string & _name_script_function,F _fun, const char *_registered_file="",short _registered_line=-1);

===== ZetScript::unrefLifetimeObject()        

		void unrefLifetimeObject(ScriptObject *so);

===== ZetScript::bindScriptFunction()        

		template <  typename F>
		std::function<F> bindScriptFunction(const zs_string & function_access, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(MemberFunctionScriptObject *_sf, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(ScriptFunction *_sf, ScriptObject *_calling_object, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(ScriptFunction *_sf, const char *_file="", int _line=-1);


===== ZetScript::clear()
		void clear();

===== ZetScript::saveState()
		void saveState();



