
=== Data types

This section will describe the data types used in the ZetScript API. Some of them are used as helpers and others interops with script environments. Some of types described it has methods and fields that are used in ZetScript internally but this documentation only will explain the relevant ones needed for the user.

==== zetscript::zs_int

Integer data type it defines a integer variable with range from -(2^b-1^) to 2^b-1^-1 where b=32 or b=64 it depending whether ZetScript is compiled for 32bits or 64bits. 

*Example*

[source,cpp]
----
zetscript::zs_int i=10;
----

==== zetscript::zs_float

_zs_float_ type it defines a float variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits.

*Example*

[source,cpp]
----
zetscript::zs_float f=20.5;
----

==== zetscript::String

_String_ it defines a string represented a sequence of chars

===== Constructor

The String constructor creates a new zs_tring as empty or initialized with other string or String.

*Syntax*

[source,cpp]
----
String();
String(const char * _s);
String(const String & _str);
String(String && _str);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : A String object.


*Example*

[source,cpp]
----
include::../examples/api/types/string_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_constructor_out.txt[]
----

===== Static constants

====== String::n_pos

npos is a static member constant value with the greatest possible value.

===== Member functions

====== String::length()

Returns the length of the string, in terms of bytes.

*Syntax*

[source,cpp]
----
int length() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of bytes in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/string_length.cpp[]
----

Console output:

[source,cpp]
----
include::../examples/api/types/string_length_out.txt[]
----


====== String::empty()

Returns whether the string is empty.

*Syntax*

[source,cpp]
----
bool empty() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

true if the string length is 0, false otherwise.

*Example*

[source,cpp]
----
include::../examples/api/types/string_empty.cpp[]
----

Console output:

[source,cpp]
----
include::../examples/api/types/string_empty_out.txt[]
----

====== String::toConstChar()

Returns a pointer to an array that contains a null-terminated sequence of characters (i.e., a C-string) representing the current value of the string object.

*Syntax*

[source,cpp]
----
const char * toConstChar() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

A pointer of characters of the string object's value.

*Example*

[source,cpp]
----
include::../examples/api/types/string_to_const_char.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_to_const_char_out.txt[]
----

====== String::operator=()

Assigns a new value to the string, replacing its current contents.

*Syntax*

[source,cpp]
----
String& operator=(const String & _str);
String& operator=(String && _str);
String& operator=(const char* _s);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : A String object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/string_operator_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_operator_assign_out.txt[]
----

======  String::operator+=()

Appends string at the end of current contents.

*Syntax*

[source,cpp]
----
String& operator+=(const String& _string);
String& operator+=(const char* _string);
String& operator+=(char _char);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : String object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/string_operator_add_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_operator_add_assign_out.txt[]
----

====== String::operator[]()

Returns a reference to the character from a position.

*Syntax*

[source,cpp]
----
char& operator[] (int _pos);
const char& operator[] (int _pos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The character at the specified position in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/string_operator_access.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_operator_access_out.txt[]
----

====== String::at()

Returns a reference to the character at position __pos_.

*Syntax*

[source,cpp]
----
char& at (int _pos);
const char& at (int _pos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The character at the specified position in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/string_at.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_at_out.txt[]
----

====== String::clear()

Erases the contents of the string.

*Syntax*

[source,cpp]
----
void clear();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/string_clear.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_clear_out.txt[]
----

====== String::substr()

Returns a new string with its value initialized to a copy of a substring of this object.

*Syntax*

[source,cpp]
----
String  substr (int _pos = 0, int _len = npos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be copied as a substring.
- _&#95;len_ : Number of characters to include in the substring. As default it passes String::npos that indicates it will take all characters until the end of the string.

[.underline]#Return#

A string with a substring of this object.

*Example*

[source,cpp]
----
include::../examples/api/types/string_substr.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_substr_out.txt[]
----

======  String::find()

Searches the string for the first occurrence of the sequence specified by its arguments.

*Syntax*

[source,cpp]
----
int find(const String & _str, int _pos = 0) const;
int find(const char *_s, int _pos = 0) const;
----

[.underline]#Parameters#

- _&#95;s_ :  A pointer to an array of characters.
- _&#95;str_ : A String object.
- _&#95;pos_ : Position of the first character in the string to be considered in the search.

[.underline]#Return#

The position of the first character of the first match. If no matches were found, the function returns String::npos

*Example*

[source,cpp]
----
include::../examples/api/types/string_find.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_find_out.txt[]
----

====== String::findLastOf()

Searches the string for the last character that matches any of the characters specified in its arguments.


*Syntax*

[source,cpp]
----
int findLastOf(const char *_s, int _pos = npos) const;
int findLastOf(const String & _str, int _pos = npos) const;
----

[.underline]#Parameters#

- _&#95;str_ : A String object.
- _&#95;s_ :  A pointer to an array of characters.
- _&#95;pos_ : Position of the last character in the string to be considered in the search.


[.underline]#Return#

The position of the last character that matches. If no matches are found, the function returns string::npos.

*Example*

[source,cpp]
----
include::../examples/api/types/string_find_last_of.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_find_last_of_out.txt[]
----

====== String::replace()

Replaces the portion of the string.

*Syntax*

[source,cpp]
----
String & replace(int _pos, int _len, const String & _to_replace);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be replaced.
- _&#95;len_ : Number of characters to replace. A value of string::npos indicates all characters until the end of the string.
- _&#95;str_ : A String object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/string_replace.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_replace_out.txt[]
----


====== String::append()

Appends a character o string at the end of current contents.

*Syntax*

[source,cpp]
----
void append(char _c);
void append(const char * _s);
void append(const char *_s, int _len);
void append(const String & _str);

----

[.underline]#Parameters#

- _&#95;c_ : The character to append.
- _&#95;s_ : A pointer to array of characters.
- _&#95;len_ : The length of number of characters to copy.
- _&#95;str_ : A String object.


[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/string_append.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_append_out.txt[]
----


====== String::erase()

Erases part of the string, reducing its length.

*Syntax*

[source,cpp]
----
void erase(int _pos, int _len);
void erase(int _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be erased.
- _&#95;len_ : Number of characters to erase.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/string_erase.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_erase_out.txt[]
----


====== String::insert()

Inserts additional characters into the string right before the character indicated by _&#x5f;pos_.

*Syntax*

[source,cpp]
----
void insert(int _pos, char _char);
void insert(int _pos, const String & _string);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to insert.
- _&#95;c_ : The character to insert.
- _&#95;str_ : The characters from String object to insert.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/string_insert.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_insert_out.txt[]
----

===== Static functions

====== String::operator+()

Returns a new string object with its value being the concatenation of the characters in left operand followed by those of right operand.

*Syntax*

[source,cpp]
----
friend String operator+(const String & _s1, const String &_s2);
friend String operator+(const String & _s1, const char *_s2);
friend String operator+(const char * _s1, const String & _s2);

friend String operator+(const String & _s1, char _s2);
friend String operator+(char  _s1, const String & _s2);
----

[.underline]#Parameters#

- _&#95;s1_ : A char, pointer to array of characters or String object as left operand.
- _&#95;s2_ : A char, pointer to array of characters or String object as right operand.

[.underline]#Return#

A string whose value is the concatenation of &#95;s1 and &#95;s2.

*Example*

[source,cpp]
----
include::../examples/api/types/string_operator_add.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_operator_add_out.txt[]
----

====== Relational operators

String implements the EQUAL (aka ==) and NOT EQUAL (aka !=) comparison operation between the left operand and right operand.

*Syntax*

[source,cpp]
----
friend bool operator _REL_OPERATOR_(const String & _s1, const String &_s2);
friend bool operator _REL_OPERATOR_(const String & _s1, const char *_s2);
friend bool operator _REL_OPERATOR_(const char * _s1, const String & _s2);
----

Where &#95;REL_OPERATOR&#95; can be *==* or *!=*

[.underline]#Parameters#

- _&#95;s1_ : A pointer to array of characters or String object as left operand.
- _&#95;s2_ : A pointer to array of characters or String object as right operand.

[.underline]#Return#

true if satisfies the condition &#95;s1 _R &#95;s2 and false otherwise.

*Example*

[source,cpp]
----
include::../examples/api/types/string_relational_operators.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_relational_operators_out.txt[]
----

==== zetscript::Vector

_Vector_ it defines a unidimensional vector of elements of type defined on its template parameter. 


===== Constructor

The Vector constructor creates a new Vector as empty or initialized with other Vector.

[source,cpp]
----
Vector();
Vector(const Vector & _vector);
----

*Example*

[source,cpp]
----
include::../examples/api/types/vector_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_constructor_out.txt[]
----

[.underline]#Parameters#

- _&#95;vector_ : A vector object.

===== Static constants

====== Vector::n_pos

npos is a static member constant value with the greatest possible value.

===== Member functions

====== Vector::push()

Appends an element at the end of current contents.

*Syntax*

[source,cpp]
----
bool 		push( const _T & _element);
----

[.underline]#Parameters#

- _&#95;element_ : The element to append.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/vector_push.cpp[]
----

====== Vector::length()

Returns the number of elements of the vector. 

*Syntax*

[source,cpp]
----
int	length() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of elements in the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/vector_length.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_length_out.txt[]
----

====== Vector::set()

Replaces the element from a position.

*Syntax*

[source,cpp]
----
void 		set( int  _pos_, const _T & _element);
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.
- _&#95;element_ : The element to replace.

[.underline]#Return#

none

*Example*

[source,cpp]
----
include::../examples/api/types/vector_set.cpp[]
----

====== Vector::get()

Returns a reference to the element from a position.

*Syntax*

[source,cpp]
----
const _T &	get( int  _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The element at the specified position in the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/vector_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_get_out.txt[]
----

====== Vector::pop()

Returns the last element by copy and erases the last element.

*Syntax*

[source,cpp]
----
void    		pop();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/vector_pop_back.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_pop_back_out.txt[]
----

====== Vector::operator=()

Replaces current content by the set of elements from other vector.

*Syntax*

[source,cpp]
----
Vector& operator=(const Vector& _vector);		
----

[.underline]#Parameters#

- _&#95;vector_ : A vector object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/vector_operator_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_operator_assign_out.txt[]
----


====== Vector::erase()

Erases an element from a position.

*Syntax*

[source,cpp]
----
void 		erase( int  _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the element to be erased.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/vector_erase.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_erase_out.txt[]
----

====== Vector::concat()

Copies all elements from other vector at the end of current contents.

*Syntax*

[source,cpp]
----
void 		concat(const Vector<_T>  & _vector);
----

[.underline]#Parameters#

- _&#95;vector_ : A vector object.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/vector_concat.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_concat_out.txt[]
----

====== Vector::insert()        

Inserts an element or copies all elements of other vector from a position.

*Syntax*

[source,cpp]
----
void 		insert(int _pos,const _T & _element);
void 		insert(int _pos,const Vector<_T>  & _vector, int _len=npos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first element to insert.
- _&#95;vector_ : The elements of vector source to insert.
- _&#95;len_ : The number of elements to insert. A value of Vector::npos indicates all elements until the end of the vector.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/vector_insert.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_insert_out.txt[]
----

====== Vector::clear()

Erases the contents of the vector.

*Syntax*

[source,cpp]
----
void 		clear();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/vector_clear.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_clear_out.txt[]
----

====== Vector::resize()

Resizes the vector by a length.

*Syntax*

[source,cpp]
----
void    	resize(int _len);
----

[.underline]#Parameters#

- _&#95;len_ : The new capacity of the vector.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/vector_resize.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_resize_out.txt[]
----


====== Vector::data()

Returns the pointer to the array of the elements.

*Syntax*

[source,cpp]
----
_T *data();
----

[.underline]#Parameters#

None

[.underline]#Return#

A pointer of elements of the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/vector_data.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/vector_data_out.txt[]
----

==== ByteCode

ByteCode represents
Here there's a meaning of each byte code

[cols="1m,1m,2d"]
|====
|Instruction |Name| Description

|BYTE_CODE_EQU
|EQU
|Logical equal

|BYTE_CODE_NOT_EQU
|NOT_EQU
|Logical not equal

|BYTE_CODE_LT
|LT
|Less than

|BYTE_CODE_LTE
|LTE
|Less than equal

|BYTE_CODE_GT
|GT
|Greather than		

|BYTE_CODE_GTE
|GTE
|Greather than equal

|BYTE_CODE_LOGIC_AND
|LOGIC_AND
|Login AND

|BYTE_CODE_LOGIC_OR
|LOGIC_OR
|Logic OR

|BYTE_CODE_INSTANCEOF
|INSTANCEOF
|Instanceof

|BYTE_CODE_NOT
|NOT
|Not

|BYTE_CODE_NEG
|NEG
|Negate

|BYTE_CODE_ADD
|ADD
|Addition

|BYTE_CODE_SUB
|SUB
|Substraction

|BYTE_CODE_DIV
|DIV
|Division	

|BYTE_CODE_MUL
|MUL
|Multiplication	

|BYTE_CODE_MOD
|MOD
|Modulus

|BYTE_CODE_AND
|AND
|Bitwise AND

|BYTE_CODE_OR
|OR
|Bitwise OR

|BYTE_CODE_XOR
|XOR
|Bitwise XOR

|BYTE_CODE_SHL
|SHL
|Bitwise SHIFT LEFT

|BYTE_CODE_SHR
|SHR
|Bitwise SHIFT RIGHT

|BYTE_CODE_BWC
|BWC
|Bitwise complement

|BYTE_CODE_ASSIGN
|ASSIGN
|Assign

|BYTE_CODE_ADD_ASSIGN
|ADD_ASSIGN
|Addition and assignment

|BYTE_CODE_SUB_ASSIGN
|SUB_ASSIGN
|Substraction and assignment

|BYTE_CODE_MUL_ASSIGN
|MUL_ASSIGN
|Multiplication and assignment

|BYTE_CODE_DIV_ASSIGN
|DIV_ASSIGN
|Division and assignment

|BYTE_CODE_MOD_ASSIGN
|MOD_ASSIGN
|Modulus and assignment

|BYTE_CODE_AND_ASSIGN
|AND_ASSIGN
|Bitwise AND and assignment

|BYTE_CODE_OR_ASSIGN
|OR_ASSIGN
|Bitwise OR and assignment

|BYTE_CODE_XOR_ASSIGN
|XOR_ASSIGN
|Bitwise XOR and assignment

|BYTE_CODE_SHL_ASSIGN
|SHL_ASSIGN
|Bitwise SHIFT LEFT and assignment

|BYTE_CODE_SHR_ASSIGN
|SHR_ASSIGN
|Bitwise SHIFT RIGHT and assignment

|BYTE_CODE_PUSH_STK_GLOBAL_IRGO
|PUSH_STK_GLOBAL_IRGO
|Push global variable from return function to stack

|BYTE_CODE_PUSH_STK_GLOBAL
|PUSH_STK_GLOBAL
|Push global variable to stack

|BYTE_CODE_
|PUSH_STK_LOCAL
|Push local variable to stack
			
|BYTE_CODE_
|PUSH_STK_REF
|Push argument reference to stack

|BYTE_CODE_
|PUSH_STK_THIS
|Push current object instance to stack

|BYTE_CODE_
|PUSH_STK_ARRAY@ITEM
|Push array item to stack

|BYTE_CODE_
|PUSH_STK_OBJ@ITEM 
|Push object item to stack

|BYTE_CODE_
|PUSH_STK_THIS@VAR
|Push member variable to stack

|BYTE_CODE_
|LOAD_GLOBAL
|Load global variable to stack

|BYTE_CODE_
|LOAD_LOCAL
|Load local variable to stack

|BYTE_CODE_
|LOAD_REF
|Load argument reference to stack

|BYTE_CODE_
|LOAD_THIS
|Load current instance to stack

|BYTE_CODE_
|LOAD_CONSTRUCTOR_FUNCT
|Load constructor function to stack

|BYTE_CODE_
|LOAD_???
|Unresolved load symbol. It tries to resolve and load at runtime

|BYTE_CODE_
|CALL
|Performs a direct call

|BYTE_CODE_
|CALL???
|Unresolved direct call. It tries to load at runtime

|BYTE_CODE_
|STK_CALL
|Performs a call from current stack

|BYTE_CODE_
|MEMBER_CALL
|Performs member call

|BYTE_CODE_
|LOAD_THIS@VAR
|Load member variable to stack

|BYTE_CODE_
|LOAD_THIS@FUN
|Load member function to stack

|BYTE_CODE_
|LOAD_ARRAY@ITEM
|Load array item to stack

|BYTE_CODE_
|LOAD_OBJ@ITEM
|Load object item to stack

|BYTE_CODE_
|LOAD_FUN
|Load function to stack

|BYTE_CODE_
|LOAD_UNDEFINED
|Load undefined value to stack

|BYTE_CODE_
|LOAD_NULL
|Load Null value to stack

|BYTE_CODE_
|LOAD_STK
|Load stack element to stack

|BYTE_CODE_
|LOAD_STR
|Load _String_ value to stack

|BYTE_CODE_
|LOAD_FLT
|Load _Float_ value to stack

|BYTE_CODE_
|LOAD_BOOL
|Load _Boolean_ value to stack

|BYTE_CODE_
|LOAD_INT
|Load _Integer_ value to stack

|BYTE_CODE_
|LOAD_TYPE
|Load _Type_ value to stack

|BYTE_CODE_
|JMP
|Performs an unconditional jump.

|BYTE_CODE_
|JMP_CASE 
|Performs a jump Switch-Case.
			
|BYTE_CODE_
|JNT
|Performs a jump if not true

|BYTE_CODE_
|JT
|Performs jump if true.
			
|BYTE_CODE_
|JE_CASE
|Performs a jump if equal Switch-Case

|BYTE_CODE_
|CALL_CONSTRUCTOR
|Performs a constructor call

|BYTE_CODE_
|NEW_ARRAY
|Creates an array object

|BYTE_CODE_			
|PUSH_AITEM
|Push array item to stack
			
|BYTE_CODE_
|RET
|Return

|BYTE_CODE_
|NEW_OBJECT_BY_TYPE
|Creates new object by type

|BYTE_CODE_
|NEW_OBJECT_BY_VALUE
|Creates new object by value
			
|BYTE_CODE_
|DELETE
|Deletes object

|BYTE_CODE_
|POP_SCOPE
|Pop scope

|BYTE_CODE_
|PUSH_SCOPE
|Push scope

|BYTE_CODE_
|PUSH_OITEM
|Push object item

|BYTE_CODE_
|NEW_OBJECT
|Creates new object

|BYTE_CODE_
|NEW_STR
|Creates new string
	
|BYTE_CODE_	
|IT_INIT
|Performs iterator init

|BYTE_CODE_
|STORE_CONST
|Performs a constant assignment

|BYTE_CODE_			
|PRE_INC
|Performs a preincrement

|BYTE_CODE_
|PRE_DEC
|Performs a predecrement

|BYTE_CODE_
|POST_INC
|Performs a postincrement

|BYTE_CODE_
|POST_DEC
|Performs a postdecrement

|BYTE_CODE_
|RESET_STACK
|Resets stack
			
|BYTE_CODE_
|TYPEOF
|Typeof

|BYTE_CODE_
|IN
|In operator
|====

==== Type

Type is an type managed by ZetScript that defines a builtin or registered script type. Type has the following fields.

- id: The script type id
- name: The script type name
- native_name: Native name of script type
- properties: A integer value composed of the following mask values,  

[cols="1d,2m,2d"]
|====
|Name |Description

|TYPE_PROPERTY_C_OBJECT_REF		
|It tells script type is native

|TYPE_PROPERTY_NON_INSTANTIABLE	
|it tells script type is static or not instantiable

|====


==== Symbol

_Symbol_ is a type managed internally by ZetScript that defines a symbol. The _Symbol_ type has the following fields:

- scope : scope where symbol was registered
- name: symbol name
- ref_ptr: Pointer reference that holds information about the instance of symbol type.
- n_params; Number of parameters in case the symbol is refers a function.
- properties: A integer value composed of the following mask values,  

[cols="1d,2m,2d"]
|====
|Name |Description
|SYMBOL_PROPERTY_NATIVE_OBJECT_REF
|ref_ptr holds native object

|SYMBOL_PROPERTY_STATIC
|C function or C++ static functions

|SYMBOL_PROPERTY_TYPE
|symbol is type

|SYMBOL_PROPERTY_FUNCTION
|ref_ptr holds script function ptr

|SYMBOL_PROPERTY_CONST
|This symbol is not assignable
	
|SYMBOL_PROPERTY_MEMBER_PROPERTY
|Member attrib

|SYMBOL_PROPERTY_ARG_BY_REF
|Is a reference

|SYMBOL_PROPERTY_ALLOCATED_STK
|Is a reference

|====

==== StackElement

StackElement is the data used by the VirtualMachine.  StackElement contents _value and _properties_ fields that defines the type of StackElement and how to fetch its contents in function of its properties.

[cols="1d,2m,2d"]
|====
|Name |Mask value|Description

|STACK_ELEMENT_PROPERTY_UNDEFINED
|Its value is 0 defined as *Undefined* type

|STACK_ELEMENT_PROPERTY_NULL
|Its value is 0 defined as *Null* type

|STACK_ELEMENT_PROPERTY_CHAR_PTR
|Its value is a *const char &#42;* type

|STACK_ELEMENT_PROPERTY_INT
|Its value is a *zs_int* type
		
|STACK_ELEMENT_PROPERTY_FLOAT
|Its value is a *zs_float &#42;* type 

|STACK_ELEMENT_PROPERTY_BOOL
|Its value is a *bool* type 

|STACK_ELEMENT_PROPERTY_INDEX_CLASS_TYPE
|Its value a zs_int as the index of a defined or registered Class

|STACK_ELEMENT_PROPERTY_FUNCTION
|Its value is *Symbol &#42;* as the symbol that refers a *Function &#42;* of a function in _ref_ptr_ field

|STACK_ELEMENT_PROPERTY_MEMBER_FUNCTION
|Its value is *Symbol &#42;* as the symbol that refererences a *Function &#42;* of a member function in _ref_ptr_ field

|STACK_ELEMENT_PROPERTY_MEMBER_PROPERTY
|Its value is a *StackElementMemberProperty &#42;*

|STACK_ELEMENT_PROPERTY_OBJECT
|Its value is a *Object &#42;*

|STACK_ELEMENT_PROPERTY_CONTAINER_SLOT
|Its value is a *ContainerSlot &#42;*

|STACK_ELEMENT_PROPERTY_PTR_STK
|Its value is a *StackElement &#42;*
		
|STACK_ELEMENT_PROPERTY_READ_ONLY
|StackElement is defined as read only

|====


==== Object

_Object_ defines a the parent class of any object in TypeScript. This type is usually used internally by ZetScript. The _Object_ type has the following fields:

- type_id: The script type representated by the instance of script object. ZetScript it register primitive objects as which type_ids matches with the following,

[cols="1d,2m,2d"]
|====

|Name|Description

|TYPE_ID_OBJECT_STRING
|Tells that the object is an instance of StringObject

|TYPE_ID_OBJECT_ARRAY
|Tells that the object is an instance of  ObjectArray

|TYPE_ID_DICTIONARY_OBJECT
|Tells that the object is an instance of  DictionaryObject

|TYPE_ID_OBJECT_CLASS
|Tells that the object is an instance of  ClassObject
|====

- properties: A integer value composed of the following mask values,  

[cols="1d,2m,2d"]
|====
|Name |Mask value|Description
|OBJECT_PROPERTY_CONSTANT
|Tells if Object represents a constant object

|====

==== StringObject

_StringObject_ defines a string script object.

===== Constructor

The StringObject constructor creates a new string script object as empty or initialized with a string.  The StringObject constructor needs a ZetScript context.

*Syntax*

[source,cpp]
----
StringObject(ZetScript *_zs, const String & _str="");
----

[.underline]#Parameters#

- _&#95;zs_ : ZetScript instance.
- _&#95;str_ : String value as a initialize value (empty by default).

*Example*

[source,cpp]
----
include::../examples/api/types/string_object_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_object_constructor_out.txt[]
----

===== Member functions

====== StringObject::set()

Replaces current string value.

*Syntax*

[source,cpp]
----
void set(const String & _str);
----

[.underline]#Parameters#

- _&#95;str_ : The string value.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/string_object_set.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_object_set_out.txt[]
----

====== StringObject::get()

Gets its current string value as String or array of characters

*Syntax*

[source,cpp]
----
const String & get();
----

[.underline]#Parameters#

None

[.underline]#Return#

Its contents as string as String

*Example*

[source,cpp]
----
include::../examples/api/types/string_object_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_object_get_out.txt[]
----

====== StringObject::getConstChar()

Gets its current string value as array of characters

*Syntax*

[source,cpp]
----
const char *getConstChar();
----

[.underline]#Parameters#

None

[.underline]#Return#

Its contents as string as array of characters

*Example*

[source,cpp]
----
include::../examples/api/types/string_object_get_const_char.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_object_get_const_char_out.txt[]
----

====== StringObject::toString()

Gets its current string value

*Syntax*

[source,cpp]
----
String toString();
----

[.underline]#Parameters#

None

[.underline]#Return#

Its contents as string as String

*Example*

[source,cpp]
----
include::../examples/api/types/string_object_to_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_object_to_string_out.txt[]
----

====== StringObject::length()

Returns the length of the string, in terms of bytes.

*Syntax*

[source,cpp]
----
virtual int length();
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of bytes in the string.

[source,cpp]
----
include::../examples/api/types/string_object_length.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_object_length_out.txt[]
----
		
==== ArrayObject

_ArrayObject_ it defines a array script object.

===== Contructor

The ArrayObject constructor creates a new array script object. ArrayObject constructor needs a ZetScript context.

*Syntax*

[source,cpp]
----
ArrayObject(ZetScript *_zs);
----

[.underline]#Parameters#

- _&#95;zs_ : ZetScript instance.

*Example*

[source,cpp]
----
include::../examples/api/types/array_object_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_object_constructor_out.txt[]
----

===== Member functions

====== ArrayObject::push()

Appends _&#x5f;value_  of type _&#x5f;T_ at the end of array.

*Syntax*

[source,cpp]
----
void push(_T _element);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;element_ : The element to append.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/array_object_push.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_object_push_out.txt[]
----

====== ArrayObject::length()

Returns the number of the elements of the array.

*Syntax*

[source,cpp]
----
int length();
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of elements in the array.

[source,cpp]
----
include::../examples/api/types/string_array_object_length.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/string_array_object_length_out.txt[]
----

====== ArrayObject::set()

Replaces current value at position _&#x5f;pos_ by _&#x5f;value_ of type _&#x5f;T_. 

*Syntax*

[source,cpp]
----
void set<_T>(int _pos, _T _element);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.
- _&#95;element_ : The element to replace.

[.underline]#Return#

None


*Example*


[source,cpp]
----
include::../examples/api/types/array_object_set.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_object_set_out.txt[]
----

====== ArrayObject::elementInstanceOf()

Says whether the element at a position is instance of zetscript data type or a registered type.

*Syntax*

[source,cpp]
----
bool 	elementInstanceOf<_T>(int _pos);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

Returns true if the element at position _&#95;pos_ it type or extends from type _&#95;T_

*Example*

[source,cpp]
----
include::../examples/api/types/array_object_element_instanceof.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_object_element_instanceof_out.txt[]
----


====== ArrayObject::get()

Returns a reference element of type _&#x5f;T_ at position __pos_.

*Syntax*

[source,cpp]
----
_T 	get(int _pos);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The element at the specified position in the array.

*Example*

[source,cpp]
----
include::../examples/api/types/array_object_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_object_get_out.txt[]
----

====== ArrayObject::toString()

Returns a string as the array contents in json format.

*Syntax*

[source,cpp]
----
String toString();
----

[.underline]#Parameters#

None

[.underline]#Return#

A string of the array contents in json format.

*Example*

[source,cpp]
----
include::../examples/api/types/array_object_tostring.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/array_object_tostring_out.txt[]
----

==== DictionaryObject

_ObjectObject_ it defines a array script object.

===== Contructor

The DictionaryObject constructor creates a new object script object. DictionaryObject constructor needs a ZetScript context.


*Syntax*

[source,cpp]
----
DictionaryObject(ZetScript *_zs);
----

[.underline]#Parameters#

- _&#95;zs_ : ZetScript instance.

*Example*

[source,cpp]
----
include::../examples/api/types/object_object_constructor.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_object_constructor_out.txt[]
----


===== Member functions


====== DictionaryObject::set()

Replaces current value at key _&#x5f;key_ by _&#x5f;value_ of type _&#x5f;T_.

*Syntax*

[source,cpp]
----
void DictionaryObject::set(int _key, _T _element)
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;key_ : The string value as the key.
- _&#95;element_ : The element to replace.

[.underline]#Return#

None


*Example*

[source,cpp]
----
include::../examples/api/types/object_object_set.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_object_set_out.txt[]
----

====== DictionaryObject::elementInstanceOf()

Says whether the element is instance of zetscript data type or a registered type.

*Syntax*

[source,cpp]
----
bool 	elementInstanceOf<_T>(const String & _key);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;key_ : The string value as the key.

[.underline]#Return#

Returns true if the element at key _&#95;key_ it type or extends from type _&#95;T_

*Example*

[source,cpp]
----
include::../examples/api/types/object_object_element_instanceof.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_object_element_instanceof_out.txt[]
----

====== DictionaryObject::get()

Returns element of type _&#x5f;T_ at key __key_.

*Syntax*

[source,cpp]
----
_T 	get(const String & _key);
----

====== ArrayObject::get()

Returns a reference element at key.

*Syntax*

[source,cpp]
----
_T 	get(const String & _key);
----

[.underline]#Template#

- _&#95;T_ : Zetscript data type or a registered type.

[.underline]#Parameters#

- _&#95;key_ : The integer value as the position.

[.underline]#Return#

The element at the specified position in the array.

*Example*

[source,cpp]
----
include::../examples/api/types/object_object_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_object_get_out.txt[]
----

====== DictionaryObject::toString()

Returns a string as the object contents in json format.

*Syntax*

[source,cpp]
----
String toString();
----

[.underline]#Parameters#

None

[.underline]#Return#

A string of the object contents in json format.

*Example*

[source,cpp]
----
include::../examples/api/types/object_object_tostring.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_object_tostring_out.txt[]
----

====== ArrayObject::getKeys()

Returns a vector of strings as the keys of the Object.

*Syntax*

[source,cpp]
----
Vector<String> getKeys();
----

[.underline]#Parameters#

None

[.underline]#Return#

A vector of strings as the keys of the Object.

*Example*

[source,cpp]
----
include::../examples/api/types/object_object_get_keys.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/object_object_get_keys_out.txt[]
----

==== ClassObject

_ClassObject_ it a subclass of _ObjectObject_ that implements the _class_ type defined in ZetScript. Also it is used as a wrapper for instanced of registered C++ types.



template<typename _C>
_C to();


==== Function

_Function_ it defines a function object that contains function information. 

- id: id from factory
- name: function name
- scope: funcio


		// script type
		int 				return_type_id; 		// idx return type
		int					owner_type_id; 				// which type belongs to...

		uint16_t			properties;


typedef enum{
	FUNCTION_PROPERTY_C_OBJECT_REF			= 0x0001, // function is C
	FUNCTION_PROPERTY_STATIC				= 0x0002,
	FUNCTION_PROPERTY_MEMBER_FUNCTION		= 0x0004,// Member function
	FUNCTION_PROPERTY_DEDUCE_AT_RUNTIME		= 0x0008,// Deduce runtime functions becuse is C and it has functions with same name but different signature
}FunctionProperty;

==== ZetScript


===== ZetScript::eval()
		StackElement	eval(const String & expresion,unsigned short _eval_options, const char * _script_file_by_ref="", const char *__invoke_file__="", int __invoke_line__=-1);

		StackElement	eval(const String & expresion, const char *__invoke_file__="", int __invoke_line__=-1);


===== ZetScript::evalFile()
		StackElement	evalFile(const String & _filename,unsigned short _eval_options=0, EvalData *_eval_data_from=NULL, const char *__invoke_file__="", int __invoke_line__=-1);


===== ZetScript::intToStackElement()

		StackElement   			intToStackElement(zs_int);

===== ZetScript::floatToStackElement()

		StackElement    		floatToStackElement(zs_float);

===== ZetScript::boolToStackElement()

		StackElement    		boolToStackElement(bool);

===== ZetScript::stackElementTo()
		template<typename _C>
		_C stackElementTo(StackElement   _stk);

===== ZetScript::stackElementToString()
		String		stackElementToString(StackElement _stk,const String & _format="");

===== ZetScript::stackElementToStringTypeOf()
		String		stackElementToStringTypeOf(StackElement _stk);

===== ZetScript::toStackElement()
		template<typename _C>
		StackElement	toStackElement( _C _val);

===== newStringObject();

		StringObject * newStringObject(const String & _str="");

===== ZetScript::newObjectObject()

		DictionaryObject * newObjectObject();

===== ZetScript::newArrayObject()
		ArrayObject * newArrayObject();

===== ZetScript::newClassObject()

		template<typename _C>
		ClassObject * newClassObject(_C  *_instance=NULL);


===== ZetScript::registerConstant()


		void registerConstant(const String & var_name, int value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const String & var_name, zs_float value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const String & var_name, bool value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const String & var_name, const String & v, const char *registered_file="", short registered_line=-1);
		void registerConstant(const String & var_name, const char * v, const char *registered_file="", short registered_line=-1);

		// register object
		StackElement * registerStkConstantStringObject(const String & _key,const String & _value);

		StackElement * getStkConstantStringObject(const String & _key);


===== ZetScript::registerType()

		template<typename T>
		Type * registerType(
				const String & name
				, T  * (*_new_native_instance)(ZetScript *_zs)=NULL
				, void (*_delete_native_instance)(ZetScript *_zs,T *)=NULL
				, const char *_registered_file="",short _registered_line=-1
		)


===== ZetScript::registerFunction()

		template <typename F>
		void registerFunction( const String & _name_script_function,F ptr_function)

*Syntax*

[source,cpp]
----
void registerFunction( const String & _function_name,F _c_function, const char *_registered_file="",short _registered_line=-1);
----

[.underline]#Parameters#

- __function_name_ : The function name to be refered in ZetScript.
- __c_function_ : The C function to register.
- __registered_file_ : Source file where the function was registered
- __registered_line_ : Line file where the function was registered


===== ZetScript::extends()

		template<class T, class B>
		void extends()

===== ZetScript::registerConstructor()        

		template<typename T,typename F>
		void registerConstructor(
				 F function_type
				 , const char *_registered_file=""
				,short _registered_line=-1
		)

===== ZetScript::registerMemberFunction()

		template <typename T,typename F>
		void	registerMemberFunction(
				const String & _name_script_function
				,F function_type
				 , const char *_registered_file=""
				,short _registered_line=-1
		)

===== ZetScript::registerConstMemberProperty()        

		template <typename T,typename F>
		void	registerConstMemberProperty(
				const String & _property_name
				,F ptr_function
				 , const char *_registered_file=""
				,short _registered_line=-1
		)


===== ZetScript::registerMemberPropertyMetamethod()

		template <typename T,typename F>
		void	registerMemberPropertyMetamethod(
				const String & _property_name
				,const String & _metamethod_name
				,F _ptr_function
				 , const char *_registered_file=""
				,short _registered_line=-1
		);

===== ZetScript::registerStaticMemberFunction()

		template <typename T,typename F>
		void registerStaticMemberFunction(const String & _name_script_function,F _fun, const char *_registered_file="",short _registered_line=-1);

===== ZetScript::unrefLifetimeObject()        

		void unrefLifetimeObject(Object *so);

===== ZetScript::bindFunction()        

		template <  typename F>
		std::function<F> bindFunction(const String & function_access, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindFunction(MemberFunctionObject *_sf, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindFunction(Function *_sf, Object *_calling_object, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindFunction(Function *_sf, const char *_file="", int _line=-1);


===== ZetScript::clear()
		void clear();

===== ZetScript::saveState()
		void saveState();



