=== Call ZetScript from C++

To make a ZetScript function callable from C&#43;&#43; is done through _ZetScript::bindScriptFunction_. _ZetScript::bindScriptFunction_ it binds ZetScript function by the C&#43;&#43; function signature and the symbol name or _ScriptFunction_ object.

*Syntax*

[source,cpp]
----
 ZetScript::bindScriptFunction<ReturnType(ParamType1 *, ParamType2 *, ..., ParamType9 *)>(const zs_string & _script_function);
----

[.underline]#Parameters#

 - _ReturnType_: It can be void, a xref:api_types#_types[built-in type] or a xref:api_expose_cpp_types#_register_a_type[registered type].
 - _ParamTypeX_: It can be a pointer of xref:api_types#_types[built-in type] or a pointer of xref:api_expose_cpp_types#_register_a_type[registered type].
 - __script_function_: _ZetScript::zs_string_ or _ScriptFunction *_ as the name or the script function reference to be registered.


[.underline]#Returns#

Returns a _std::function_ with the signature provided.

*Example*

The following example it binds a _sayHelloWorld_ function.

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_out.txt[]
----

==== Return types

This section will explain how to bind script functions that return the following types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Instance of class type object
- Instance of registered type object

===== Return Boolean

To bind a ZetScript function that returns a _xref:language_data_types.adoc#_boolean[Boolean]_ it must specify _bool_ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_bool_out.txt[]
----

===== Return Integer

To bind a ZetScript function that returns a _xref:language_data_types.adoc#_integer[Integer]_ it must specify _zs_int_ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_int_out.txt[]
----

<<<

===== Return Float

To bind a ZetScript function that returns a _xref:language_data_types.adoc#_float[Float]_ it must specify _zs_float_ return type on its function signature.


*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_float_out.txt[]
----


===== Return String

To bind a ZetScript function that returns a _xref:language_data_types.adoc#_string[String]_ it can be done by specifying the following return types in its function signature,

  - zs_string
 - StringScriptObject *

====== Return String as zs_string

To bind a ZetScript function that returns a _xref:language_data_types.adoc#_string[String]_ it can specify _zs_string_ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_zs_string_out.txt[]
----


====== Return String as StringScriptObject *

To bind a ZetScript function that returns a _xref:language_data_types.adoc#_string[String]_ it can specify _StringScriptObject &#42;_ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling _ZetScript::unrefLifeTimeObject_.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_string_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_string_script_object_out.txt[]
----

<<<

===== Return Array

To bind a ZetScript function that returns a _xref:language_data_types.adoc#_array[Array]_ it must specify _ArrayScriptObject &#42;_ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling _ZetScript::unrefLifeTimeObject_.


*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_array_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_array_script_object_out.txt[]
----

<<<

===== Return Object

To bind a ZetScript function that returns a _xref:language_data_types.adoc#_object[Object]_ it must specify _ObjectScriptObject &#42;_ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling _ZetScript::unrefLifeTimeObject_.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_object_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_object_script_object_out.txt[]
----

<<<

===== Return instance of class type object

To bind a ZetScript function that returns an instance of _xref:language_data_types.adoc#_class[Class]_ type object it can specify _ObjectScriptObject &#42;_ or _ClassScriptObject &#42;_ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling _ZetScript::unrefLifeTimeObject_.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_class_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_class_script_object_out.txt[]
----

===== Return instance of registered type object

To bind a ZetScript function that returns an instance of _xref:chapter_3_the_api.adoc#_registered_type[registered type]_ object it must specify _ClassScriptObject &#42;_ return type on its function signature. After returning  _ClassScriptObject &#42;_, it can fetch its C++ registered type by calling _ClassScriptObject::to<_T *>_, where _T is the C&#43;&#43; type.

After using the object returned by the function it has to decrease its reference count by calling _ZetScript::unrefLifeTimeObject_.

*Example*

In this example, it registers the _Number_ type (see xref:api_expose_cpp_types#&#x5f;register_type[section 3.5.1] to know how to register a type) and the property _Number::value_ (see xref:api_expose_cpp_types#&#x5f;properties[section 3.5.5] to know how to register a property). In the example also, it can see the implementation of a function 'newNumber' in the ZetScript code that returns a new _Number_. After evaluate the script code, it binds the script function _newNumber_ into a in C&#x2b;&#x2b;  variable called _newNumber_.  Finally, it calls _newNumber_ from C&#x2b;&#x2b; and save the _ClassScriptObject &_ type returned into C&#x2b;&#x2b; _class_script_object_number_ variable to print its content information.

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_return_registered_type_out.txt[]
----

<<<

==== Parameter types

This section will explain how to bind script functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered class

===== Parameter Boolean

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_boolean[Boolean]_ it must specify _bool &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_bool_out.txt[]
----

<<<

===== Parameter Integer

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_integer[Integer]_ it must specify _zs_int_ or _zs_int &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_int_out.txt[]
----

===== Parameter Float

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_float[Float]_ it must specify or _zs_float &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_float_out.txt[]
----

<<<

===== Parameter String

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_string[String]_ it can specify the following types as a parameter on its function signature,

 - const char *
 - zs_string *
 - StringScriptObject *

===== Parameter String as const char *

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_string[String]_ it can specify _const char &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_const_char.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_const_char_out.txt[]
----

===== Parameter String as zs_string *

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_string[String]_ it can specify _zs_string &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_zs_string_out.txt[]
----


===== Parameter String as StringScriptObject *

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_string[String]_ it can specify _StringScriptObject &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_string_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_string_script_object_out.txt[]
----

<<<

===== Parameter Array

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_array[Array]_ it must specify or _ArrayScriptObject &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_array_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_array_script_object_out.txt[]
----

<<<

===== Parameter Object

To bind a ZetScript function that accepts a _xref:language_data_types.adoc#_object[Object]_ it must specify _ObjectScriptObject &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_object_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_object_script_object_out.txt[]
----

<<<

===== Parameter registered type

To bind a ZetScript function that accepts a _xref:api_expose_cpp_types#&#x5f;register_type[registered type]_ as a parameter, it must specify native pointer type as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/bind_script_function/bind_script_function_param_registered_type_out.txt[]
----

