
=== Data types

This section wil describe the data types used in the library in order to interop data native/script and the ZetScript class, the core the most operations in the library. Some of the types have methods and properties that are used internally for ZetScript but this section will describe ONLY methods or propierties that user can use.

==== zs_int

Integer data type it defines a integer variable with range from -(2^b-1^) to 2^b-1^-1 where b=32 or b=64 it depending whether ZetScript is compiled for 32bits or 64bits. 

*Example*

[source,cpp]
----
zetscript::zs_int i=10;
----

==== zs_float

_zs_float_ type it defines a float variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits.

*Example*

[source,cpp]
----
zetscript::zs_float f=20.5;
----

==== zs_string

_zs_string_ it defines a string represented a sequence of chars

*Example*

[source,cpp]
----
zetscript::zs_string s="Hello World";
----

===== Member constants

====== zs_string::n_pos

npos is a static member constant value with the greatest possible value.

===== Member functions

====== zs_string::zs_string()

Constructs a zs_string object as empty or initialized from other string.

*Syntax*

[source,cpp]
----
zs_string();
zs_string(const char * _s);
zs_string(const zs_string & _str);
zs_string(zs_string && _str);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : A zs_string object.


*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_constructor.cpp[]
----

====== zs_string::length()

Returns the length of the string, in terms of bytes.

*Syntax*

[source,cpp]
----
int length() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of bytes in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_length.cpp[]
----

Output,

[source,cpp]
----
include::../examples/api/types/zs_string_length_out.txt[]
----


====== zs_string::empty()

Returns whether the string is empty.

*Syntax*

[source,cpp]
----
bool empty() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

true if the string length is 0, false otherwise.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_empty.cpp[]
----

Output,

[source,cpp]
----
include::../examples/api/types/zs_string_empty_out.txt[]
----

====== zs_string::c_str()

Returns a pointer to an array that contains a null-terminated sequence of characters (i.e., a C-string) representing the current value of the string object.

*Syntax*

[source,cpp]
----
const char * c_str() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

A pointer of characters of the string object's value.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_c_str.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_c_str_out.txt[]
----

====== zs_string::operator=()

Assigns a new value to the string, replacing its current contents.

*Syntax*

[source,cpp]
----
zs_string& operator=(const zs_string & _str);
zs_string& operator=(zs_string && _str);
zs_string& operator=(const char* _s);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : A zs_string object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_operator_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_operator_assign_out.txt[]
----

======  zs_string::operator+=()

Appends string at the end of current contents.

*Syntax*

[source,cpp]
----
zs_string& operator+=(const zs_string& _string);
zs_string& operator+=(const char* _string);
zs_string& operator+=(char _char);
----

[.underline]#Parameters#

- _&#95;s_ : A pointer to an array of characters.
- _&#95;str_ : zs_string object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_operator_add_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_operator_add_assign_out.txt[]
----

====== zs_string::operator[]()

Returns a reference to the character from a position.

*Syntax*

[source,cpp]
----
char& operator[] (int _pos);
const char& operator[] (int _pos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The character at the specified position in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_operator_access.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_operator_access_out.txt[]
----

====== zs_string::at()

Returns a reference to the character at position __pos_.

*Syntax*

[source,cpp]
----
char& at (int _pos);
const char& at (int _pos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The character at the specified position in the string.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_at.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_at_out.txt[]
----


====== zs_string::clear()

Erases the contents of the string.

*Syntax*

[source,cpp]
----
void clear();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_clear.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_clear_out.txt[]
----

====== zs_string::substr()

Returns a new string with its value initialized to a copy of a substring of this object.

*Syntax*

[source,cpp]
----
zs_string  substr (int _pos = 0, int _len = npos) const;
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be copied as a substring.
- _&#95;len_ : Number of characters to include in the substring. As default it passes zs_string::npos that indicates it will take all characters until the end of the string.

[.underline]#Return#

A string with a substring of this object.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_substr.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_substr_out.txt[]
----

======  zs_string::find()

Searches the string for the first occurrence of the sequence specified by its arguments.

*Syntax*

[source,cpp]
----
int find(const zs_string & _str, int _pos = 0) const;
int find(const char *_s, int _pos = 0) const;
----

[.underline]#Parameters#

- _&#95;s_ :  A pointer to an array of characters.
- _&#95;str_ : A zs_string object.
- _&#95;pos_ : Position of the first character in the string to be considered in the search.

[.underline]#Return#

The position of the first character of the first match. If no matches were found, the function returns zs_string::npos

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_find.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_find_out.txt[]
----

====== zs_string::find_last_of()

Searches the string for the last character that matches any of the characters specified in its arguments.


*Syntax*

[source,cpp]
----
int find_last_of(const char *_s, int _pos = npos) const;
int find_last_of(const zs_string & _str, int _pos = npos) const;
----

[.underline]#Parameters#

- _&#95;str_ : A zs_string object.
- _&#95;s_ :  A pointer to an array of characters.
- _&#95;pos_ : Position of the last character in the string to be considered in the search.


[.underline]#Return#

The position of the last character that matches. If no matches are found, the function returns string::npos.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_find_last_of.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_find_last_of_out.txt[]
----

====== zs_string::replace()

Replaces the portion of the string.

*Syntax*

[source,cpp]
----
zs_string & replace(int _pos, int _len, const zs_string & _to_replace);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be replaced.
- _&#95;len_ : Number of characters to replace. A value of string::npos indicates all characters until the end of the string.
- _&#95;str_ : A zs_string object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_replace.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_replace_out.txt[]
----


====== zs_string::append()

Appends a character o string at the end of current contents.

*Syntax*

[source,cpp]
----
void append(char _c);
void append(const char * _s);
void append(const char *_s, int _len);
void append(const zs_string & _str);

----

[.underline]#Parameters#

- _&#95;c_ : The character to append.
- _&#95;s_ : A pointer to array of characters.
- _&#95;len_ : The length of number of characters to copy.
- _&#95;str_ : A zs_string object.


[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_append.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_append_out.txt[]
----


====== zs_string::erase()

Erases part of the string, reducing its length.

*Syntax*

[source,cpp]
----
void erase(int _pos, int _len);
void erase(int _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to be erased.
- _&#95;len_ : Number of characters to erase.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_erase.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_erase_out.txt[]
----


====== zs_string::insert()

Inserts additional characters into the string right before the character indicated by _&#x5f;pos_.

*Syntax*

[source,cpp]
----
void insert(int _pos, char _char);
void insert(int _pos, const zs_string & _string);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first character to insert.
- _&#95;c_ : The character to insert.
- _&#95;str_ : The characters from zs_string object to insert.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_insert.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_insert_out.txt[]
----


===== Static functions

====== zs_string::operator+()

Returns a new string object with its value being the concatenation of the characters in left operand followed by those of right operand.

*Syntax*

[source,cpp]
----
friend zs_string operator+(const zs_string & _s1, const zs_string &_s2);
friend zs_string operator+(const zs_string & _s1, const char *_s2);
friend zs_string operator+(const char * _s1, const zs_string & _s2);

friend zs_string operator+(const zs_string & _s1, char _s2);
friend zs_string operator+(char  _s1, const zs_string & _s2);
----

[.underline]#Parameters#

- _&#95;s1_ : A char, pointer to array of characters or zs_string object as left operand.
- _&#95;s2_ : A char, pointer to array of characters or zs_string object as right operand.

[.underline]#Return#

A string whose value is the concatenation of &#95;s1 and &#95;s2.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_operator_add.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_operator_add_out.txt[]
----

====== Relational operators

zs_string implements the EQUAL (aka ==) and NOT EQUAL (aka !=) comparison operation between the left operand and right operand.

*Syntax*

[source,cpp]
----
friend bool operator _REL_OPERATOR_(const zs_string & _s1, const zs_string &_s2);
friend bool operator _REL_OPERATOR_(const zs_string & _s1, const char *_s2);
friend bool operator _REL_OPERATOR_(const char * _s1, const zs_string & _s2);
----

Where &#95;REL_OPERATOR&#95; can be *==* or *!=*

[.underline]#Parameters#

- _&#95;s1_ : A pointer to array of characters or zs_string object as left operand.
- _&#95;s2_ : A pointer to array of characters or zs_string object as right operand.

[.underline]#Return#

true if satisfies the condition &#95;s1 _R &#95;s2 and false otherwise.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_string_relational_operators.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_string_relational_operators_out.txt[]
----

==== zs_vector

_zs_vector_ it defines a unidimensional vector of elements of type defined on its template parameter. 

*Example*

[source,cpp]
----
// Create a vector containing integers
zetscript::zs_vector<int> v;
----

===== Member constants

====== zs_vector::n_pos

npos is a static member constant value with the greatest possible value.

===== Member functions

====== zs_vector::zs_vector()

Constructs a zs_vector object as empty or initialized from other vector.

[source,cpp]
----
zs_vector();
zs_vector(const zs_vector & _vector);
----

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_constructor.cpp[]
----


[.underline]#Parameters#

- _&#95;vector_ : A vector object.


====== zs_vector::push_back()

Appends an element at the end of current contents.

*Syntax*

[source,cpp]
----
bool 		push_back( const _T & _element);
----

[.underline]#Parameters#

- _&#95;element_ : The element to append.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_push_back.cpp[]
----

====== zs_vector::size()

Returns the number of elements of the vector. 

*Syntax*

[source,cpp]
----
int	size() const;
----

[.underline]#Parameters#

None

[.underline]#Return#

The number of elements in the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_size.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_size_out.txt[]
----

====== zs_vector::set()

Replaces the element from a position.

*Syntax*

[source,cpp]
----
void 		set( int  _pos_, const _T & _element);
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.
- _&#95;element_ : The element to replace.

[.underline]#Return#

none

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_set.cpp[]
----

====== zs_vector::get()

Returns a reference to the element from a position.

*Syntax*

[source,cpp]
----
const _T &	get( int  _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : The integer value as the position.

[.underline]#Return#

The element at the specified position in the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_get.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_get_out.txt[]
----

====== zs_vector::pop_back()

Returns the last element by copy and erases the last element.

*Syntax*

[source,cpp]
----
void    		pop_back();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_pop_back.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_pop_back_out.txt[]
----

====== zs_vector::operator=()

Replaces current content by the set of elements from other vector.

*Syntax*

[source,cpp]
----
zs_vector& operator=(const zs_vector& _vector);		
----

[.underline]#Parameters#

- _&#95;vector_ : A vector object.

[.underline]#Return#

*this

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_operator_assign.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_operator_assign_out.txt[]
----


====== zs_vector::erase()

Erases an element from a position.

*Syntax*

[source,cpp]
----
void 		erase( int  _pos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the element to be erased.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_erase.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_erase_out.txt[]
----

====== zs_vector::concat()

Copies all elements from other vector at the end of current contents.

*Syntax*

[source,cpp]
----
void 		concat(const zs_vector<_T>  & _vector);
----

[.underline]#Parameters#

- _&#95;vector_ : A vector object.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_concat.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_concat_out.txt[]
----

====== zs_vector::insert()        

Inserts an element or copies all elements of other vector from a position.

*Syntax*

[source,cpp]
----
void 		insert(int _pos,const _T & _element);
void 		insert(int _pos,const zs_vector<_T>  & _vector, int _len=npos);
----

[.underline]#Parameters#

- _&#95;pos_ : Position of the first element to insert.
- _&#95;vector_ : The elements of vector source to insert.
- _&#95;len_ : The number of elements to insert. A value of zs_vector::npos indicates all elements until the end of the vector.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_insert.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_insert_out.txt[]
----

====== zs_vector::clear()

Erases the contents of the vector.

*Syntax*

[source,cpp]
----
void 		clear();
----

[.underline]#Parameters#

None

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_clear.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_clear_out.txt[]
----

====== zs_vector::resize()

Resizes the vector by a length.

*Syntax*

[source,cpp]
----
void    	resize(int _len);
----

[.underline]#Parameters#

- _&#95;len_ : The new capacity of the vector.

[.underline]#Return#

None

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_resize.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_resize_out.txt[]
----


====== zs_vector::data()

Returns the pointer to the array of the elements.

*Syntax*

[source,cpp]
----
_T *data();
----

[.underline]#Parameters#

None

[.underline]#Return#

A pointer of elements of the vector.

*Example*

[source,cpp]
----
include::../examples/api/types/zs_vector_data.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/types/zs_vector_data_out.txt[]
----


==== ArrayScriptObject

_ArrayScriptObject_ it defines a array script object that acts as a array container of elements. It uses zetscript context in order to be instanced.

===== Member functions


*Syntax*

[source,cpp]
----
ArrayScriptObject(ZetScript *_zs);
----

====== ArrayScriptObject::push()

Appends _&#x5f;value_  of type _&#x5f;T_ at the end of array.

*Syntax*

[source,cpp]
----
void push(_T _value);
----

====== ArrayScriptObject::set()

Replaces current value at position _&#x5f;pos_ by _&#x5f;value_ of type _&#x5f;T_.

*Syntax*

[source,cpp]
----
void set(int _idx, _T _value);
----


====== ArrayScriptObject::get()

Returns a reference element of type _&#x5f;T_ at position __pos_.

*Syntax*

[source,cpp]
----
_T 	get(int _idx);
----

====== ArrayScriptObject::toString()


*Syntax*

[source,cpp]
----
virtual 							zs_string toString();
----

==== ObjectScriptObject

_ObjectScriptObject_ it defines a object script object that acts as a container of fields. It uses zetscript context in order to be instanced.


===== Member functions


ObjectScriptObject(ZetScript	*_zs);

====== ObjectScriptObject::set()

Replaces current value at key _&#x5f;key_ by _&#x5f;value_ of type _&#x5f;T_.

*Syntax*

[source,cpp]
----
----


====== ObjectScriptObject::get()

Returns element of type _&#x5f;T_ from key __key_.

*Syntax*

[source,cpp]
----
----

====== ObjectScriptObject::get()


*Syntax*

[source,cpp]
----
zs_vector<zs_string> getKeys();
----

==== ClassScriptObject

_ClassScriptObject_ it a subclass of _ObjectScriptObject_ that implements the _class_ type defined in ZetScript. Also it is used as a wrapper for instanced of registered C++ types.



			ClassScriptObject(ZetScript *_zs,short _idx_script_type,void *  _c_object=NULL);

			template<typename _C>
			_C to();


==== StackElement

===== Propeties

value

bla,bla,bla

properties

	
		
- ZS_STK_PROPERTY_UNDEFINED:
- ZS_STK_PROPERTY_NULL:
- ZS_STK_PROPERTY_CHAR_PTR:
- ZS_STK_PROPERTY_INT:
- ZS_STK_PROPERTY_FLOAT:
- ZS_STK_PROPERTY_BOOL:	
- ZS_STK_PROPERTY_TYPE:
	
- ZS_STK_PROPERTY_FUNCTION:
- ZS_STK_PROPERTY_MEMBER_FUNCTION:
- ZS_STK_PROPERTY_MEMBER_PROPERTY:
- ZS_STK_PROPERTY_SCRIPT_OBJECT:
- ZS_STK_PROPERTY_CONTAINER_SLOT:
- ZS_STK_PROPERTY_PTR_STK:
- ZS_STK_PROPERTY_READ_ONLY:

	


===== Member functions

====== StackElement::setUndefined

		void 					setUndefined();

====== StackElement::typeOf

		StackElement			typeOf();

==== StringScriptObject

_StringScriptObject_ it defines a string script object and encapsules _zs_string_ reference. It uses zetscript context in order to be instanced

===== Member functions

_ArrayScriptObject_ member functions available for user operations are the following,

====== StringScriptObject::set()

Replaces current string value.

void set(const zs_string & _s);

====== StringScriptObject::get()

const zs_string & get();

====== StringScriptObject::getConstChar()

		const char *getConstChar();

====== StringScriptObject::length()

		virtual int length();

====== StringScriptObject::toString()

		virtual zs_string toString();

==== ScriptFunction

_ScriptFunction_ it defines a function object that contains function information. 


==== ZetScript


===== ZetScript::eval()
		StackElement	eval(const zs_string & expresion,unsigned short _eval_options, const char * _script_file_by_ref="", const char *__invoke_file__="", int __invoke_line__=-1);

		StackElement	eval(const zs_string & expresion, const char *__invoke_file__="", int __invoke_line__=-1);


===== ZetScript::evalFile()
		StackElement	evalFile(const zs_string & _filename,unsigned short _eval_options=0, EvalData *_eval_data_from=NULL, const char *__invoke_file__="", int __invoke_line__=-1);


===== ZetScript::intToStackElement()

		StackElement   			intToStackElement(zs_int);

===== ZetScript::floatToStackElement()

		StackElement    		floatToStackElement(zs_float);

===== ZetScript::boolToStackElement()

		StackElement    		boolToStackElement(bool);

===== ZetScript::stackElementTo()
		template<typename _C>
		_C stackElementTo(StackElement   _stk);

===== ZetScript::stackElementToString()
		zs_string		stackElementToString(StackElement _stk,const zs_string & _format="");

===== ZetScript::stackElementToStringTypeOf()
		zs_string		stackElementToStringTypeOf(StackElement _stk);

===== ZetScript::toStackElement()
		template<typename _C>
		StackElement	toStackElement( _C _val);

===== newStringScriptObject();

		StringScriptObject * newStringScriptObject(const zs_string & _str="");

===== ZetScript::newObjectScriptObject()

		ObjectScriptObject * newObjectScriptObject();

===== ZetScript::newArrayScriptObject()
		ArrayScriptObject * newArrayScriptObject();

===== ZetScript::newClassScriptObject()

		template<typename _C>
		ClassScriptObject * newClassScriptObject(_C  *_instance=NULL);


===== ZetScript::registerConstant()


		void registerConstant(const zs_string & var_name, int value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, zs_float value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, bool value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, const zs_string & v, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, const char * v, const char *registered_file="", short registered_line=-1);

		// register object
		StackElement * registerStkConstantStringObject(const zs_string & _key,const zs_string & _value);

		StackElement * getStkConstantStringObject(const zs_string & _key);


===== ZetScript::registerType()

		template<typename T>
		ScriptType * registerType(
				const zs_string & str_script_type
				, T  * (*_new_native_instance)(ZetScript *_zs)=NULL
				, void (*_delete_native_instance)(ZetScript *_zs,T *)=NULL
				, const char *_registered_file="",short _registered_line=-1
		)


===== ZetScript::registerFunction()

		template <typename F>
		void registerFunction( const zs_string & _name_script_function,F ptr_function)

*Syntax*

[source,cpp]
----
void registerFunction( const zs_string & _function_name,F _c_function, const char *_registered_file="",short _registered_line=-1);
----

[.underline]#Parameters#

- __function_name_ : The function name to be refered in ZetScript.
- __c_function_ : The C function to register.
- __registered_file_ : Source file where the function was registered
- __registered_line_ : Line file where the function was registered


===== ZetScript::extends()

		template<class T, class B>
		void extends()

===== ZetScript::registerConstructor()        

		template<typename T,typename F>
		void registerConstructor(
				 F function_type
				 , const char *_registered_file=""
				,short _registered_line=-1
		)

===== ZetScript::registerMemberFunction()

		template <typename T,typename F>
		void	registerMemberFunction(
				const zs_string & _name_script_function
				,F function_type
				 , const char *_registered_file=""
				,short _registered_line=-1
		)

===== ZetScript::registerConstMemberProperty()        

		template <typename T,typename F>
		void	registerConstMemberProperty(
				const zs_string & _property_name
				,F ptr_function
				 , const char *_registered_file=""
				,short _registered_line=-1
		)


===== ZetScript::registerMemberPropertyMetamethod()

		template <typename T,typename F>
		void	registerMemberPropertyMetamethod(
				const zs_string & _property_name
				,const zs_string & _metamethod_name
				,F _ptr_function
				 , const char *_registered_file=""
				,short _registered_line=-1
		);

===== ZetScript::registerStaticMemberFunction()

		template <typename T,typename F>
		void registerStaticMemberFunction(const zs_string & _name_script_function,F _fun, const char *_registered_file="",short _registered_line=-1);

===== ZetScript::unrefLifetimeObject()        

		void unrefLifetimeObject(ScriptObject *so);

===== ZetScript::bindScriptFunction()        

		template <  typename F>
		std::function<F> bindScriptFunction(const zs_string & function_access, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(MemberFunctionScriptObject *_sf, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(ScriptFunction *_sf, ScriptObject *_calling_object, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(ScriptFunction *_sf, const char *_file="", int _line=-1);


===== ZetScript::clear()
		void clear();

===== ZetScript::saveState()
		void saveState();



