
==== Properties

the ScriptEngine API allows to register class properties as we could see in xref:language_class.adoc#_properties[chapter 2 class properties].


===== Register constant property

Returns a constant property.

*Syntax*

[source,javascript]
----
ReturnType RegisteredTypeProperty_get(ScriptEngine *_se, RegisteredType *_this)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context.
- __this_ : The current instance.

[.underline]#Returns#

Returns the value of the property

*Example*

The following code defines a function that returns the _value_ contents of current instance,

[source,cpp]
----

zs_float NumberZs_MAX_VALUE_get(ScriptEngine *_se,Number *_this){
	return FLT_MAX;
}

----

Next, the function _NumberZs_MAX_VALUE_get_ is registered through _ScriptEngine::registerConstMemberProperty_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerConstMemberProperty<Number>("MAX_VALUE",NumberZs_MAX_VALUE_get);

	//...

}
----

Finally, the following code it shows an example of a script that returns _Number::MAX_VALUE_ property,

[source,javascript]
----
include::../examples/api/register_type/register_constant_member_property.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_constant_member_property_out.txt[]
----

<<<

===== Register property metamethods

====== _get()

__get_ returns the value of the property

*Syntax*

[source,javascript]
----
ReturnType RegisteredTypeProperty_get(ScriptEngine *_se, RegisteredType *_this)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance

[.underline]#Returns#

Returns the value of the property

*Example*

The following code defines a function as a _get_ property operation that returns the _value_ contents of current instance,

[source,cpp]
----

zs_float NumberZs_value_get(ScriptEngine *_se,Number *_this){
	return _this->value;
}

----

Next, the function _NumberZs_value_get_ is registered as member metamethod __get__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_get",NumberZs_value_get);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _get_ operation from _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_get.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_get_out.txt[]
----

<<<

====== _set()

Implements _assignment_ operator (aka = ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_set(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].

[.underline]#Returns#

None.

*Example*

The following code defines a function that performs a _set_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_set(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value=*_value;
}
----

Next, the function _NumberZs_value_set_ is registered as member metamethod _set_ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_set",NumberZs_value_set);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _set_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_set.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_set_out.txt[]
----

<<<

====== _addset()

Implements _addition assignment_ operator (aka += ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_addset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _addset_ to _value_ variable of current instance,

[source,cpp]
----
void NumberZs_value_addset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value+=*_value;
}
----

Next, the function _NumberZs_value_addset_ is registered as member metamethod __addset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_addset",NumberZs_value_addset));

	//...

}
----

Finally, the following code it shows an example of a script that performs a _addset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_addset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_addset_out.txt[]
----

<<<

====== _subset()

Implements _substraction assignment_ operator (aka -= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_subset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs a _subset_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_subset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value-=*_value;
}

----

Next, the function _NumberZs_value_subset_ is registered as member metamethod __subset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_subset",NumberZs_value_subset);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _subset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_subset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_subset_out.txt[]
----

<<<

====== _mulset()

Implements _multiplication assignment_ operator (aka *= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_mulset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].

[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _mulset_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_mulset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value*=*_value;
}

----

Next, the function _NumberZs_value_mulset_ is registered as member metamethod __mulset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_mulset",NumberZs_value_mulset);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _mulset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_mulset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_mulset_out.txt[]
----

<<<

====== _divset()

Implements _division assignment_ operator (aka /= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_divset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _divset_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_divset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value/=*_value;
}
----

Next, the function _NumberZs_value_divset_ is registered as member metamethod __divset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_divset",NumberZs_value_divset);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _divset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_divset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_divset_out.txt[]
----

<<<

====== _modset()

Implements _modulus assignment_ operator (aka %= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_modset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _modset_ to _value_ variable of current instance,

[source,cpp]
----
void NumberZs_value_modset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value=fmod(_this->value,*_value);
}
----

Next, the function _NumberZs_value_modset_ is registered as member metamethod __addset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_modset",NumberZs_value_modset);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _modset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_modset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_modset_out.txt[]
----

<<<

====== _andset()

Implements _bitwise AND assignment_ operator (aka &= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_andset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _andset_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_andset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)&(int)(*_value);
}
----

Next, the function _NumberZs_value_andset_ is registered as member metamethod __andset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_andset",NumberZs_value_andset);
	
	//...

}
----

Finally, the following code it shows an example of a script that performs a _andset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_andset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_andset_out.txt[]
----

<<<

====== _orset()

Implements _bitwise OR assignment_ operator (aka |= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_orset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _orset_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_orset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)|(int)(*_value);
}
----

Next, the function _NumberZs_value_orset_ is registered as member metamethod __orset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_orset",NumberZs_value_orset);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _orset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_orset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_orset_out.txt[]
----

<<<

====== _xorset()

Implements _bitwise XOR assignment_ operator (aka ^= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_xorset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _xorset_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_xorset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)^(int)(*_value);
}
----

Next, the function _NumberZs_value_xorset_ is registered as member metamethod __xorset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_xorset",NumberZs_value_xorset);

	//...

}

----

Finally, the following code it shows an example of a script that performs a _xorset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_xorset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_xorset_out.txt[]
----

<<<

====== _shrset()

Implements _bitwise SHIFT RIGHT assignment_ operator (aka >>= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_shrset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _shrset_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_shrset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)>>(int)(*_value);
}
----

Next, the function _NumberZs_value_shrset_ is registered as member metamethod __shrset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_shrset",NumberZs_value_shrset);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _shrset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_shrset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_shrset_out.txt[]
----

<<<

====== _shlset()

Implements _bitwise SHIFT LEFT assignment_ operator (aka <<= ) with a value entered by parameter as right operand.

*Syntax*

[source,javascript]
----
void RegisteredTypeProperty_shlset(ScriptEngine *_se, RegisteredType *_this, ParamType *_value)
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance
- __value_ : Value or variable as right operand. Its type can be a pointer of one defined in  xref:api_types#_types[primitive types] or a pointer of other xref:api_expose_cpp_types#_register_a_type[registered type].


[.underline]#Returns#

None.

*Example*

The following code defines a function that performs and _shlset_ to _value_ variable of current instance,

[source,cpp]
----

void NumberZs_value_shlset(ScriptEngine *_se,Number *_this,zs_float *_value){
	_this->value=(int)(_this->value)<<(int)(*_value);
}
----

Next, the function _NumberZs_value_shlset_ is registered as member metamethod __shlset__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_shlset",NumberZs_value_shlset);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _shlset_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_shlset.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_shlset_out.txt[]
----

<<<

====== _postinc()


Implements _post_increment_ operator (aka a++ ) 

*Syntax*

[source,javascript]
----
ReturnType  RegisteredType_value_postinc(ScriptEngine *_se, RegisteredType *_this);
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance

[.underline]#Returns#

Return the value before perform post increment operation. The return value can be one defined in  xref:api_call_cpp_from_zetscript#_return_types[return types].

*Example*

The following code defines a function that performs a _postinc_ of current instance,

[source,cpp]
----

zs_float  NumberZs_value_postinc(ScriptEngine *_se,Number *_this){
	return _this->value++;
}

----

Next, the function _NumberZs_value_postinc_ is registered as member metamethod __postinc__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberFunction<Number>("_postinc",NumberZs_postinc);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _postinc_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_postinc.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_postinc_out.txt[]
----

<<<

====== _postdec()

Implements _post_decrement_ operator (aka a-- ) 

*Syntax*

[source,javascript]
----
ReturnType  RegisteredType_value_postdec(ScriptEngine *_se, RegisteredType *_this);
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance

[.underline]#Returns#

Return the value before perform post decrement operation. The return value can be one defined in  xref:api_call_cpp_from_zetscript#_return_types[return types].

*Example*

The following code defines a function that performs a _postdec_ of current instance,

[source,cpp]
----

zs_float  NumberZs_value_postdec(ScriptEngine *_se,Number *_this){
	return _this->value--;
}

----

Next, the function _NumberZs_value_postdec_ is registered as member metamethod __postdec__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberFunction<Number>("_postdec",NumberZs_postdec);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _postdec_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_postdec.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_postdec_out.txt[]
----

<<<

====== _preinc()

Implements _pre_increment_ operator (aka ++a ) 

*Syntax*

[source,javascript]
----
ReturnType  RegisteredType_value_preinc(ScriptEngine *_se, RegisteredType *_this);
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance

[.underline]#Returns#

Return the value before perform pre increment operation. The return value can be one defined in  xref:api_call_cpp_from_zetscript#_return_types[return types].

*Example*

The following code defines a function that performs a _preinc_ of current instance,

[source,cpp]
----
zs_float  NumberZs_value_preinc(ScriptEngine *_se,Number *_this){
	return ++_this->value;
}
----

Next, the function _NumberZs_value_preinc_ is registered as member metamethod __preinc__ through _ScriptEngine::registerMemberPropertyMetamethod_,

[source,cpp]
----

void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_preinc",NumberZs_value_preinc);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _preinc_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_preinc.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_preinc_out.txt[]
----

<<<

====== _predec()

[source,javascript]
----
ReturnType  RegisteredType_value_predec(ScriptEngine *_se, RegisteredType *_this);
----

[.underline]#Parameters#

- __zs_ : ScriptEngine context
- __this_ : The current instance

[.underline]#Returns#

Return the value before perform pre decrement operation. The return value can be one defined in  xref:api_call_cpp_from_zetscript#_return_types[return types].

*Example*

The following code defines a function that performs a _predec_ of current instance,

[source,cpp]
----

zs_float  NumberZs_value_predec(ScriptEngine *_se,Number *_this){
	return --_this->value;
}
----

Next, the function _NumberZs_value_predec_ is registered as member metamethod __predec__ through _ScriptEngine::registerMemberPropertyMetamethod_,


[source,cpp]
----
void NumberZs_register(zetscript::ScriptEngine *_se){

	//...

	_se->registerMemberPropertyMetamethod<Number>("value","_predec",NumberZs_value_predec);

	//...

}
----

Finally, the following code it shows an example of a script that performs a _predec_ operation to _Number::value_ property,

[source,javascript]
----
include::../examples/api/register_type/register_member_property_metamethod_predec.cpp[]
----

Console output:

[source,text]
----
include::../examples/api/register_type/register_member_property_metamethod_predec_out.txt[]
----
