
=== Call C++ from ZetScript

To call C&#43;&#43; code from _ZetScript_ it has to create a C function with the following signature,

include::api_register_c_function_signature.adoc[]


After the C function is created, it has to registered with xref:api_data_types#&#95;_scriptengine_registerfunction[ScriptEngine::registerFunction]. 


==== Return types

This section will explain how to register C functions that return the following ZetScript types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Registered type

===== Return Boolean

To register a C function that returns a xref:language_data_types#_boolean[Boolean] it must specify _bool_ as return type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_return_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_bool_out.txt[]
----

===== Return Integer

To register a C function that returns a xref:language_data_types.adoc#_integer[Integer] it must specify _zs_int_ as return type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_return_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_zs_int_out.txt[]
----

===== Return Float

To register a C function that returns a xref:language_data_types.adoc#_float[Float] it must specify _zs_float_ as return type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_return_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_zs_float_out.txt[]
----

===== Return a String

To register a C function that returns a xref:language_data_types.adoc#&lowbar;string[String] it can be done by specifying the following return types,

- _String_
- _StringScriptObject *_


====== Return String as String

To register a C function that returns a xref:language_data_types.adoc#lowbar;string[String] it can specify _String_ as return type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_return_String.cpp[]
----

<<<

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_String_out.txt[]
----

====== Return String as StringScriptObject &#42;

To register a C function that returns a xref:language_data_types.adoc#&#95;string[String] it can specify xref:api_data_types.adoc#&#95;stringscriptobject[zetscript::StringScriptObject] pointer as return type. The instantiation of _StringScriptObject_ is done throught ScriptEngine instance.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_return_string_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_string_object_out.txt[]
----

<<<

===== Return Array

To register a C function that returns a xref:language_data_types.adoc#lowbar;array[Array] it must specify _ArrayScriptObject &#42;_ as return type. The instantiation of _ArrayScriptObject &#42;_ it's done through _ScriptEngine::newArrayScriptObject_ using ScriptEngine context.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_return_array_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_array_object_out.txt[]
----

<<<

===== Return Object

To register a C function that returns a xref:language_data_types.adoc#lowbar;object[Object] it must specify _ObjectScriptObject &#42;_ as return type. The instantiation of _ObjectScriptObject &#42;_ it's done through _ScriptEngine::newObjectScriptObject_ using ScriptEngine context.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_return_object_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_object_object_out.txt[]
----

===== Return registered type


To register a C function that returns a xref:api_expose_cpp_types#_register_type[registered type] it can be done by specifying the following return types,

- Return registered type by its reference
- Return registered type by ClassObject 


<<<
 
===== Return registered type by its reference

To register a C function that returns a xref:api_expose_cpp_types#_register_type[registered type] it must specify its native pointer type as return.

====
ScriptEngine *NEVERS* destroy a native pointer returned from registered function. This is why it *CANNOT* allocate and return a type from the C function because this becomes a memory leak. Instead, the object  should be instantiated outside of ScriptEngine and accessible from a location where its lifetime is active during the execution of the script.
====

Because the function it returns a native reference the type can be registered as instantiable or not instantiable (see xref:api_expose_cpp_types#&#x5f;register_a_type_as_instantiable[section 3.5.1])

*Example*

In the following example it registers a type _Number_ as non instantiable (This is because in this example it doesn't need to instantiate any new object in the script code. See xref:api_expose_cpp_types#&#x5f;register_a_type_as_non_instantiable[section 3.5.1] to know how to register a type as NON INSTANTIABLE) and the property _Number::value_ (see xref:api_expose_cpp_types#&#x5f;properties[section 3.5.5] to know how to register a property). Finally, it registers C function _returnNumber_ that returns a _Number *_. In the main program instantiates _Number_ object and is acceded globally, so is active during the execution of the script.


[source,cpp]
----
include::../examples/api/register_function/register_function_return_registered_type.cpp[]
----

<<<

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_registered_type_out.txt[]
----

===== Return registered type by ClassObject &#42;

To register a C function that returns a xref:api_expose_cpp_types#_register_type[registered type] it must specify _ClassObject &#42;_ as return type. To instantiate _ClassObject &#42;_  is done through _ScriptEngine::newClassObject_ using ScriptEngine context and the registered class instantiated.

A difference from returning a pointer type of a registered type, when the C function returns a _ClassObject &#42;_ ScriptEngine is in charge to deallocate automatically when it has no more references to it. 

====
The action of return a _ClassObject &#42;_ ScriptEngine it considers the instance of a new object in the script code so it needs to register the type as INSTANTIABLE (See xref:api_expose_cpp_types#&#x5f;register_a_type_an_instantiable[section 3.5.1] to know how to register a type AS INSTANTIABLE)
====

*Example*

In the following example it registers type _Number_ as instantiable (See xref:api_expose_cpp_types#&#x5f;register_a_type_as_instantiable[section 3.5.1] to know how to register a type AS INSTANTIABLE) and the property _Number::value_. Finally, it registers C function _returnNumber_ that instances and returns a _ClassObject_ as _Number_ type. 

[source,cpp]
----
include::../examples/api/register_function/register_function_return_class_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_return_class_object_out.txt[]
----

==== Parameter types


This section will explain how to register C functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered type

===== Parameter Boolean

To register a C function that accepts a xref:language_data_types.adoc#_boolean[Boolean] it must specify _bool &#x2a;_ as parameter type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_param_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_param_bool_out.txt[]
----

===== Parameter Integer

To register a C function that accepts a xref:language_data_types.adoc#lowbar;integer[Integer]_ it can specify _zs_int_ or _zs_int &#x2a;_ as parameter type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_param_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_param_zs_int_out.txt[]
----

===== Parameter Float

To register a C function that accepts a xref:language_data_types.adoc#lowbar;float[Float] it must specify _zs_float &#x2a;_ as parameter type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_param_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_param_zs_float_out.txt[]
----

<<<

===== Parameter String

To register a C function that accepts a xref:language_data_types.adoc#_string[String] it can specify _const char *_ , _String *_  or _StringScriptObject *_ as a parameter type,

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_param_String.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_param_String_out.txt[]
----

===== Parameter Array

To register a C function that accepts a xref:language_data_types.adoc#lowbar;array[Array] it must specify _ArrayScriptObject &#42;_ as parameter type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_param_array_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_param_array_object_out.txt[]
----

<<<

===== Parameter Object

To register a C function that accepts a xref:language_data_types.adoc#lowbar;object[Object] it must specify _ObjectScriptObject &#42;_ as parameter type.

*Example*

[source,cpp]
----
include::../examples/api/register_function/register_function_param_object_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_param_object_object_out.txt[]
----

<<<

===== Parameter Function

To register a C function that accepts a xref:language_data_types.adoc#lowbar;function[Function] it must specify _Function &#42;_ as parameter type. To make  _Function_ callable from C++ must use _ScriptEngine::bindScriptFunction_ (see xref:_api_call_zetscript_from_cpp#&#x5f;call_zetscript_from_c[section 3.4] to know more about ScriptEngine functions binding)

*Example*

The following example it registers function _paramFunction_ that accepts a xref:language_data_types.adoc#lowbar;function[Function] as parameter. Later, it evaluates an script that calls _paramFunction_ passing anonymous function. In the calling function _paramFunction_ it binds the anonymous function and it calls.

[source,cpp]
----
include::../examples/api/register_function/register_function_param_script_function.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_param_script_function_out.txt[]
----

<<<

===== Parameter Registered Type

To register a C function that accepts a xref:api_expose_cpp_types#&#x5f;register_type[registered type] as a parameter, it must specify native pointer type as parameter type.

*Example*

In the following example it registers the _Number_ type (see xref:api_expose_cpp_types#&#x5f;register_type[section 3.5.1] to know how to register a type) and the property _Number::value_ (see xref:api_expose_cpp_types#&#x5f;properties[section 3.5.5] to know how to register a property) and it registers function _mul10Number_ that accepts a _Number &#x2a;_ type as parameter. In the script execution it instances a _Number_ and it is passed as argument to _mul10Number_ that multiplies its property _value_ by 10.

[source,cpp]
----
include::../examples/api/register_function/register_function_param_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/register_function/register_function_param_registered_type_out.txt[]
----