=== Call ZetScript from C++

To make a ZetScript function callable from C++ is done through xref:language_data_types.adoc#_scriptenginebindscriptfunction[ScriptEngine::bindScriptFunction]. 

==== Return types

This section will explain how to bind script functions that return the following types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Instance of class type object
- Instance of registered type object

===== Return Boolean

To bind a ZetScript function that returns a xref:language_data_types.adoc#_boolean[Boolean] it must specify _bool_ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_bool_out.txt[]
----

===== Return Integer

To bind a ZetScript function that returns a xref:language_data_types.adoc#_integer[Integer] it must specify _zetscript::zs_int_ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_zs_int_out.txt[]
----

<<<

===== Return Float

To bind a ZetScript function that returns a xref:language_data_types.adoc#_float[Float] it must specify _zetscript::zs_float_ return type on its function signature.


*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_zs_float_out.txt[]
----


===== Return String

To bind a ZetScript function that returns a xref:language_data_types.adoc#_string[String] it can be done by specifying the following return types in its function signature,

 - String
 - StringScriptObject *

====== Return String as zetscript::String

To bind a ZetScript function that returns a xref:language_data_types.adoc#_string[String] it can specify _zetscript::String_ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_string_out.txt[]
----


====== Return String as zetscript::StringScriptObject *

To bind a ZetScript function that returns a xref:language_data_types.adoc#_string[String] it can specify _zetscript::StringScriptObject &#42;_ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling _ScriptEngine::unrefLifeTimeObject_.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_string_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_string_object_out.txt[]
----

<<<

===== Return Array

To bind a ZetScript function that returns a xref:language_data_types.adoc#_array[Array] it must specify _ArrayScriptObject &#42;_ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling _ScriptEngine::unrefLifeTimeObject_.


*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_array_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_array_object_out.txt[]
----

<<<

===== Return Object

To bind a ZetScript function that returns a xref:language_data_types.adoc#_object[Object] it must specify _ObjectScriptObject &#42;_ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling _ScriptEngine::unrefLifeTimeObject_.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_object_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_object_object_out.txt[]
----

<<<

===== Return instance of class type object

To bind a ZetScript function that returns an instance of xref:language_data_types.adoc#_class[Class] type object it can specify _ObjectScriptObject &#42;_ or _ClassObject &#42;_ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling _ScriptEngine::unrefLifeTimeObject_.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_class_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_class_object_out.txt[]
----

===== Return instance of registered type object

To bind a ZetScript function that returns an instance of xref:chapter_3_the_api.adoc#_registered_type[registered type] object it must specify _ClassObject &#42;_ return type on its function signature. After returning  _ClassObject &#42;_, it can fetch its C++ registered type by calling _ClassObject::to<_T *>_, where _T is the C&#43;&#43; type.

After using the object returned by the function it has to decrease its reference count by calling _ScriptEngine::unrefLifeTimeObject_.

*Example*

In this example, it registers the _Number_ type (see xref:api_expose_cpp_types#&#x5f;register_type[section 3.5.1] to know how to register a type) and the property _Number::value_ (see xref:api_expose_cpp_types#&#x5f;properties[section 3.5.5] to know how to register a property). In the example also, it can see the implementation of a function 'newNumber' in the ZetScript code that returns a new _Number_. After evaluate the script code, it binds the script function _newNumber_ into a in C&#x2b;&#x2b;  variable called _newNumber_.  Finally, it calls _newNumber_ from C&#x2b;&#x2b; and save the _ClassObject &_ type returned into C&#x2b;&#x2b; _class_object_number_ variable to print its content information.

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_registered_type_out.txt[]
----

<<<

==== Parameter types

This section will explain how to bind script functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered class

===== Parameter Boolean

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_boolean[Boolean]_ it must specify _bool &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_bool_out.txt[]
----

<<<

===== Parameter Integer

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_integer[Integer] it must specify _zs_int_ or _zs_int &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_zs_int_out.txt[]
----

===== Parameter Float

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_float[Float] it must specify or _zs_float &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_zs_float_out.txt[]
----

<<<

===== Parameter String

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_string[String] it can specify the following types as a parameter on its function signature,

 - const char *
 - String *
 - StringScriptObject *

===== Parameter String as const char *

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_string[String] it can specify _const char &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_const_char.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_const_char_out.txt[]
----

===== Parameter String as String *

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_string[String] it can specify _String &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_String.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_String_out.txt[]
----


===== Parameter String as StringScriptObject *

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_string[String] it can specify _StringScriptObject &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_string_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_string_object_out.txt[]
----

<<<

===== Parameter Array

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_array[Array] it must specify or _ArrayScriptObject &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_array_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_array_object_out.txt[]
----

<<<

===== Parameter Object

To bind a ZetScript function that accepts a xref:language_data_types.adoc#_object[Object] it must specify _ObjectScriptObject &#42;_ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_object_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_object_object_out.txt[]
----

<<<

===== Parameter registered type

To bind a ZetScript function that accepts a xref:api_expose_cpp_types#&#x5f;register_type[registered type] as a parameter, it must specify native pointer type as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_registered_type_out.txt[]
----

