=== Call ZetScript from C++

To make a ZetScript function callable from C++ is done through <<language_data_types.adoc#_scriptenginebindscriptfunction,ScriptEngine::bindScriptFunction>>. 

==== Return types

This section will explain how to bind script functions that return the following types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Instance of class type object
- Instance of registered type object

===== Return Boolean

To bind a __ZetScript__ function that returns a <<language_data_types.adoc#_boolean,Boolean>> it must specify __bool__ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_bool_out.txt[]
----

===== Return Integer

To bind a ZetScript function that returns a <<language_data_types.adoc#_integer,Integer>> it must specify __zetscript::zs_int__ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_zs_int_out.txt[]
----

<<<

===== Return Float

To bind a ZetScript function that returns a <<language_data_types.adoc#_float,Float>> it must specify __zetscript::zs_float__ return type on its function signature.


*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_zs_float_out.txt[]
----


===== Return String

To bind a ZetScript function that returns a <<language_data_types.adoc#_string,String>> it can be done by specifying the following return types in its function signature,

 - String
 - StringScriptObject *

====== Return String as zetscript::String

To bind a ZetScript function that returns a <<language_data_types.adoc#_string,String>> it can specify __zetscript::String__ return type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_string_out.txt[]
----


====== Return String as zetscript::StringScriptObject *

To bind a ZetScript function that returns a <<language_data_types.adoc#_string,String>> it can specify __zetscript::StringScriptObject *__ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling __ScriptEngine::unrefLifeTimeObject__.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_string_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_string_object_out.txt[]
----

<<<

===== Return Array

To bind a ZetScript function that returns a <<language_data_types.adoc#_array,Array>> it must specify __zetscript::ArrayScriptObject *__ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling __ScriptEngine::unrefLifeTimeObject__.


*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_array_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_array_object_out.txt[]
----

<<<

===== Return Object

To bind a ZetScript function that returns a <<language_data_types.adoc#_object,Object>> it must specify __zetscript::ObjectScriptObject *__ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling __ScriptEngine::unrefLifeTimeObject__.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_object_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_object_object_out.txt[]
----

<<<

===== Return instance of class type object

To bind a ZetScript function that returns an instance of <<language_data_types.adoc#_class,Class>> type object it can specify __zetscript::ObjectScriptObject *__ or __zetscript::ClassScriptObject *__ return type on its function signature.

After using the object returned by the function it has to decrease its reference count by calling __ScriptEngine::unrefLifeTimeObject__.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_class_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_class_object_out.txt[]
----

===== Return instance of registered type object

To bind a ZetScript function that returns an instance of <<api_data_types.adoc#_scriptengineregistertype,registered type>> object it must specify __zetscript::ClassScriptObject *__ return type on its function signature. After returning  __zetscript::ClassScriptObject *__, it can fetch its C++ registered type by calling __ClassScriptObject::to<_T *>__, where _T is the C&#43;&#43; type.

After using the object returned by the function it has to decrease its reference count by calling __ScriptEngine::unrefLifeTimeObject__.

*Example*

In this example, it registers the __Number__ type and the property __Number::value__ (see <<api_data_types.adoc#_scriptengineregistermemberpropertymetamethod,ScriptEngine::registerMemberPropertyMetamethod>>). In the example also, it can see the implementation of a function 'newNumber' in the ZetScript code that returns a new __Number__. After evaluate the script code, it binds the script function __newNumber__ into a in C&#x2b;&#x2b;  variable called __newNumber__.  Finally, it calls __newNumber__ from C&#x2b;&#x2b; and save the __ClassScriptObject__ type returned into C++ __class_object_number__ variable to print its content information.

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_return_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_return_registered_type_out.txt[]
----

<<<

==== Parameter types

This section will explain how to bind script functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered class

===== Parameter Boolean

To bind a ZetScript function that accepts a <<language_data_types.adoc#_boolean,Boolean>> it must specify __bool *__ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_bool_out.txt[]
----

<<<

===== Parameter Integer

To bind a ZetScript function that accepts a <<language_data_types.adoc#_integer,Integer>> it must specify __zetscript::zs_int__ or __zetscript::zs_int *__ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_zs_int_out.txt[]
----

===== Parameter Float

To bind a ZetScript function that accepts a <<language_data_types.adoc#_float,Float>> it must specify or __zetscript::zs_float *__ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_zs_float_out.txt[]
----

<<<

===== Parameter String

To bind a ZetScript function that accepts a <<language_data_types.adoc#_string,String>> it can specify the following types as a parameter on its function signature,

 - const char *
 - zetscript::String *
 - zetscript::StringScriptObject *

===== Parameter String as const char *

To bind a ZetScript function that accepts a <<language_data_types.adoc#_string,String>> it can specify __const char *__ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_const_char.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_const_char_out.txt[]
----

===== Parameter String as String *

To bind a ZetScript function that accepts a <<language_data_types.adoc#_string,String>> it can specify __zetscript::String *__ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_string_out.txt[]
----


===== Parameter String as StringScriptObject *

To bind a ZetScript function that accepts a <<language_data_types.adoc#_string,String>> it can specify __zetscript::StringScriptObject *__ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_string_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_string_object_out.txt[]
----

<<<

===== Parameter Array

To bind a ZetScript function that accepts a <<language_data_types.adoc#_array,Array>> it must specify or __zetscript::ArrayScriptObject *__ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_array_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_array_object_out.txt[]
----

<<<

===== Parameter Object

To bind a ZetScript function that accepts a <<language_data_types.adoc#_object,Object>> it must specify __zetscript::ObjectScriptObject *__ as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_object_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_object_object_out.txt[]
----

<<<

===== Parameter registered type

To bind a ZetScript function that accepts a <<api_data_types.adoc#_scriptengineregistertype,registered type>> as a parameter, it must specify native pointer type as parameter type on its function signature.

*Example*

[source,cpp]
----
include::../examples/api/bind_script_function/bind_script_function_param_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/api/bind_script_function/bind_script_function_param_registered_type_out.txt[]
----

<<<