
=== Types

This section wil describe the types used in the library in order to interop data native/script and the ZetScript class, the core the most operations in the library.

==== zs_int

Integer data type it defines a integer variable with range from -(2^b-1^) to 2^b-1^-1 where b=32 or b=64 it depending whether ZetScript is compiled for 32bits or 64bits. 

*Example*

[source,cpp]
----
zetscript::zs_int i=10;
----

==== zs_float

_zs_float_ type it defines a float variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits.

*Example*

[source,cpp]
----
zetscript::zs_float f=20.5;
----

==== zs_string

_zs_string_ it defines a string represented a sequence of chars

*Example*

[source,cpp]
----
zetscript::zs_string s="Hello World";
----

===== Member functions

_zs_string_ has the following member functions,

====== zs_string::operator=()

Assigns a new value to the string, replacing its current contents.

*Syntax*

[source,cpp]
----
zs_string& operator=(const zs_string & _string);
zs_string& operator=(zs_string && _string);
zs_string& operator=(const char* _string);
----

======  zs_string::operator+=()

Appends __string_ at the end of current contents.

*Syntax*

[source,cpp]
----
zs_string& operator+=(const zs_string& _string);
zs_string& operator+=(const char* _string);
zs_string& operator+=(char _char);
----

====== zs_string::operator[]()

Returns a reference to the character at position __pos_.

*Syntax*

[source,cpp]
----
char& operator[] (int _pos);
const char& operator[] (int _pos) const;
----

====== zs_string::at()

Returns a reference to the character at position __pos_.

*Syntax*

[source,cpp]
----
char& at (int _pos);
const char& at (int _pos) const;
----

====== zs_string::clear()

Erases the contents of the string.

*Syntax*

[source,cpp]
----
void clear();
----

====== zs_string::substr()

Returns a new string with its value initialized to a copy of a substring of this object. The substring is the portion of the object that starts at character position __pos_ and spans _&#x5f;len_ characters.

*Syntax*

[source,cpp]
----
zs_string  substr (int _pos = 0, int _len = npos) const;
----

======  zs_string::find()

Searches the string for the first occurrence of the sequence specified by its arguments. When _&#x5f;pos_ is specified, the search only includes characters at or after position _&#x5f;pos_, ignoring any possible occurrences that include characters before _&#x5f;pos_.

*Syntax*

[source,cpp]
----
int find(const zs_string &_string, int _pos = 0) const;
int find(const char *_string, int _pos = 0) const;
----

====== zs_string::find_last_of()

Searches the string for the last character that matches any of the characters specified in its arguments. When _&#x5f;pos_ is specified, the search only includes characters at or before position _&#x5f;pos_, ignoring any possible occurrences after _&#x5f;pos_.


*Syntax*

[source,cpp]
----
int find_last_of(const char *_string, int _pos = npos) const;
----

====== zs_string::replace()

Replaces the portion of the string that begins at character _&#x5f;pos_ and spans _&#x5f;len_ characters.

*Syntax*

[source,cpp]
----
zs_string & replace(int _pos, int _len, const zs_string & _to_replace);
----

====== zs_string::append()

Appends __string_ at the end of current contents.

*Syntax*

[source,cpp]
----
void append(const char *_string, int _len);
void append(char _c);
void append(const zs_string & _s);
void append(const char * _s);
----

====== zs_string::erase()

Erases part of the string, reducing its length.

*Syntax*

[source,cpp]
----
void erase(int _pos, int _len);
void erase(int _pos);
----

====== zs_string::insert()

Inserts additional characters into the string right before the character indicated by _&#x5f;pos_.

*Syntax*

[source,cpp]
----
void insert(int _pos, char _char);
void insert(int _pos, const zs_string & _string);
----

====== zs_string::empty()

Returns whether the string is empty.

*Syntax*

[source,cpp]
----
bool empty() const;
----

====== zs_string::length()

Returns the length of the string, in terms of bytes.

*Syntax*

[source,cpp]
----
int length() const;
----

====== zs_string::c_str()

Returns a pointer to an array that contains a null-terminated sequence of characters (i.e., a C-string) representing the current value of the string object.

*Syntax*

[source,cpp]
----
const char * c_str() const;
----

===== Static functions

_zs_string_ has the following static functions,

====== zs_string::operator+()

Returns a new string object with its value being the concatenation of the characters in left operand followed by those of right operand.

*Syntax*

[source,cpp]
----
friend zs_string operator+(const zs_string & _s1, const zs_string &_s2);
friend zs_string operator+(const zs_string & _s1, const char *_s2);
friend zs_string operator+(const char * _s1, const zs_string & _s2);

friend zs_string operator+(const zs_string & _s1, char _s2);
friend zs_string operator+(char  _s1, const zs_string & _s2);
----


====== zs_string::operator==()

Performs the EQUAL comparison operation between the left operand and right operand.


*Syntax*

[source,cpp]
----
friend bool operator==(const zs_string & _s1, const zs_string &_s2);
friend bool operator==(const zs_string & _s1, const char *_s2);
friend bool operator==(const char * _s1, const zs_string & _s2);
----


====== zs_string::operator!=()

Performs the NOT EQUAL comparison operation between the left operand and right operand.

*Syntax*

[source,cpp]
----
friend bool operator!=(const zs_string & _s1, const zs_string &_s2);
friend bool operator!=(const zs_string & _s1, const char *_s2);
friend bool operator!=(const char * _s1, const zs_string & _s2);
----



==== zs_vector

===== Member functions

====== zs_vector::operator=()

Assigns a new value to the vector, replacing its current contents.

*Syntax*

[source,cpp]
----
zs_vector& operator=(const zs_vector& _vector);		
----

====== zs_vector::set()

Sets _&#x5f;element_ at position  _&#x5f;pos_.

*Syntax*

[source,cpp]
----
void 		set( int  _pos_, const _T & _element);
----

====== zs_vector::get()

Gets the _&#x5f;element_ at position  _&#x5f;pos_.

*Syntax*

[source,cpp]
----
const _T &	get( int  _pos);
----

====== zs_vector::erase()

Erases the  _&#x5f;element_ at position  _&#x5f;pos_ reducing its length by one.

*Syntax*

[source,cpp]
----
void 		erase( int  _pos);
----

====== zs_vector::push_back()

Appends an  _&#x5f;element_ at the end of current contents.

*Syntax*

[source,cpp]
----
bool 		push_back( const _T & _val);
----

====== zs_vector::concat()

Copies all elements of a vector at the end of current contents.

*Syntax*

[source,cpp]
----
void 		concat(const zs_vector<_T>  & _vector);
----

====== zs_vector::insert()        

Inserts an  element or copies all elements of vector at position.

*Syntax*

[source,cpp]
----
void 		insert(int _pos,const _T & _element);
void 		insert(int _pos,const zs_vector<_T>  & _vector, int _n_list_elements_to_copy=npos);
----


====== zs_vector::clear()
		void 		clear();

====== zs_vector::pop_back()
		_T    		pop_back();

====== zs_vector::resize()
		void    	resize(int _len);


====== zs_vector::data()
		inline _T *data(){
			return items;
		}

====== zs_vector::size()

		inline int	size() const{
			return count;
		}

==== ArrayScriptObject

_ArrayScriptObject_ it defines a array script object that acts as a array container of elements. It uses zetscript context in order to be instanced.

===== Member functions

_ArrayScriptObject_ member functions available for user operations are the following,

====== ArrayScriptObject::push()

Appends _&#x5f;value_  of type _&#x5f;T_ at the end of array.

template<typename _T>
void 								push(_T _value);

====== ArrayScriptObject::set()

Replaces current value at position _&#x5f;pos_ by _&#x5f;value_ of type _&#x5f;T_.

	template<typename _T>
		void 								set(int _idx, _T _value);


====== ArrayScriptObject::get()

Returns a reference element of type _&#x5f;T_ at position __pos_.

		template<typename _T>
		_T 									get(int _idx);

====== ArrayScriptObject::toString()

virtual 							zs_string toString();

==== ObjectScriptObject

_ObjectScriptObject_ it defines a object script object that acts as a container of fields. It uses zetscript context in order to be instanced.


===== Member functions

_ObjectScriptObject_ member functions available for user operations are the following,

====== ObjectScriptObject::set()

Replaces current value at key _&#x5f;key_ by _&#x5f;value_ of type _&#x5f;T_.

====== ObjectScriptObject::get()

Returns element of type _&#x5f;T_ from key __key_.

==== ClassScriptObject

_ClassScriptObject_ it a subclass of _ObjectScriptObject_ that implements the _class_ type defined in ZetScript. Also it is used as a wrapper for instanced of registered C++ types.


==== StackElement

===== Propeties

value

bla,bla,bla

properties

	
		
- ZS_STK_PROPERTY_UNDEFINED:
- ZS_STK_PROPERTY_NULL:
- ZS_STK_PROPERTY_CHAR_PTR:
- ZS_STK_PROPERTY_INT:
- ZS_STK_PROPERTY_FLOAT:
- ZS_STK_PROPERTY_BOOL:	
- ZS_STK_PROPERTY_TYPE:
	
- ZS_STK_PROPERTY_FUNCTION:
- ZS_STK_PROPERTY_MEMBER_FUNCTION:
- ZS_STK_PROPERTY_MEMBER_PROPERTY:
- ZS_STK_PROPERTY_SCRIPT_OBJECT:
- ZS_STK_PROPERTY_CONTAINER_SLOT:
- ZS_STK_PROPERTY_PTR_STK:
- ZS_STK_PROPERTY_READ_ONLY:

	


===== Member functions

====== StackElement::setUndefined

		void 					setUndefined();

====== StackElement::typeOf

		StackElement			typeOf();

==== StringScriptObject

_StringScriptObject_ it defines a string script object and encapsules _zs_string_ reference. It uses zetscript context in order to be instanced

===== Member functions

_ArrayScriptObject_ member functions available for user operations are the following,

====== StringScriptObject::set()

Replaces current string value.

void set(const zs_string & _s);

====== StringScriptObject::get()

const zs_string & get();

====== StringScriptObject::getConstChar()

		const char *getConstChar();

====== StringScriptObject::length()

		virtual int length();

====== StringScriptObject::toString()

		virtual zs_string toString();

==== ScriptFunction

_ScriptFunction_ it defines a function object that contains function information. 


==== ZetScript


===== ZetScript::eval()
		StackElement	eval(const zs_string & expresion,unsigned short _eval_options, const char * _script_file_by_ref="", const char *__invoke_file__="", int __invoke_line__=-1);

		StackElement	eval(const zs_string & expresion, const char *__invoke_file__="", int __invoke_line__=-1);


===== ZetScript::evalFile()
		StackElement	evalFile(const zs_string & _filename,unsigned short _eval_options=0, EvalData *_eval_data_from=NULL, const char *__invoke_file__="", int __invoke_line__=-1);


===== ZetScript::intToStackElement()

		StackElement   			intToStackElement(zs_int);

===== ZetScript::floatToStackElement()

		StackElement    		floatToStackElement(zs_float);

===== ZetScript::boolToStackElement()

		StackElement    		boolToStackElement(bool);

===== ZetScript::stackElementTo()
		template<typename _C>
		_C stackElementTo(StackElement   _stk);

===== ZetScript::stackElementToString()
		zs_string		stackElementToString(StackElement _stk,const zs_string & _format="");

===== ZetScript::stackElementToStringTypeOf()
		zs_string		stackElementToStringTypeOf(StackElement _stk);

===== ZetScript::toStackElement()
		template<typename _C>
		StackElement	toStackElement( _C _val);

===== newStringScriptObject();

		StringScriptObject * newStringScriptObject(const zs_string & _str="");

===== ZetScript::newObjectScriptObject()

		ObjectScriptObject * newObjectScriptObject();

===== ZetScript::newArrayScriptObject()
		ArrayScriptObject * newArrayScriptObject();

===== ZetScript::newClassScriptObject()

		template<typename _C>
		ClassScriptObject * newClassScriptObject(_C  *_instance=NULL);


===== ZetScript::registerConstant()


		void registerConstant(const zs_string & var_name, int value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, zs_float value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, bool value, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, const zs_string & v, const char *registered_file="", short registered_line=-1);
		void registerConstant(const zs_string & var_name, const char * v, const char *registered_file="", short registered_line=-1);

		// register object
		StackElement * registerStkConstantStringObject(const zs_string & _key,const zs_string & _value);

		StackElement * getStkConstantStringObject(const zs_string & _key);


===== ZetScript::registerType()

		template<typename T>
		ScriptType * registerType(
				const zs_string & str_script_type
				, T  * (*_new_native_instance)(ZetScript *_zs)=NULL
				, void (*_delete_native_instance)(ZetScript *_zs,T *)=NULL
				, const char *_registered_file="",short _registered_line=-1
		)


===== ZetScript::registerFunction()

		template <typename F>
		void registerFunction( const zs_string & _name_script_function,F ptr_function)

*Syntax*

[source,cpp]
----
void registerFunction( const zs_string & _function_name,F _c_function, const char *_registered_file="",short _registered_line=-1);
----

[.underline]#Parameters#

- __function_name_ : The function name to be refered in ZetScript.
- __c_function_ : The C function to register.
- __registered_file_ : Source file where the function was registered
- __registered_line_ : Line file where the function was registered


===== ZetScript::extends()

		template<class T, class B>
		void extends()

===== ZetScript::registerConstructor()        

		template<typename T,typename F>
		void registerConstructor(
				 F function_type
				 , const char *_registered_file=""
				,short _registered_line=-1
		)

===== ZetScript::registerMemberFunction()

		template <typename T,typename F>
		void	registerMemberFunction(
				const zs_string & _name_script_function
				,F function_type
				 , const char *_registered_file=""
				,short _registered_line=-1
		)

===== ZetScript::registerConstMemberProperty()        

		template <typename T,typename F>
		void	registerConstMemberProperty(
				const zs_string & _property_name
				,F ptr_function
				 , const char *_registered_file=""
				,short _registered_line=-1
		)


===== ZetScript::registerMemberPropertyMetamethod()

		template <typename T,typename F>
		void	registerMemberPropertyMetamethod(
				const zs_string & _property_name
				,const zs_string & _metamethod_name
				,F _ptr_function
				 , const char *_registered_file=""
				,short _registered_line=-1
		);

===== ZetScript::registerStaticMemberFunction()

		template <typename T,typename F>
		void registerStaticMemberFunction(const zs_string & _name_script_function,F _fun, const char *_registered_file="",short _registered_line=-1);

===== ZetScript::unrefLifetimeObject()        

		void unrefLifetimeObject(ScriptObject *so);

===== ZetScript::bindScriptFunction()        

		template <  typename F>
		std::function<F> bindScriptFunction(const zs_string & function_access, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(MemberFunctionScriptObject *_sf, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(ScriptFunction *_sf, ScriptObject *_calling_object, const char *_file="", int _line=-1);

		template <  typename F>
		std::function<F> bindScriptFunction(ScriptFunction *_sf, const char *_file="", int _line=-1);


===== ZetScript::clear()
		void clear();

===== ZetScript::saveState()
		void saveState();



