[id=_the_class]
=== Class

A class is a template for create objects with its own variables and functions. A class is defined using keyword _class_ followed by the name. 


[source,javascript]
----
class Test{
	

}
----

==== Class instantiantion

To instantiate an object of a defined class type, it is done using the _new_ operator.

[source,javascript]
----
class Test{
	

}


var t= new Test(); // t instanced as class Test

----

==== Member functions

===== Member function

A function member aims to do operations or management with its class members. It's acceded through field operator ('.') and preceded by _this_ keyword when is acceded within a member function. A  member function can be implemented outside of the class too. 


*Example*

[source,javascript]
----
class Test{

	// a member function
	method1(){
		Console::out("Access method 1")
		
		// call member function within a member function through 'this'
		this.method3();
	}
	
	// another member function
	method2(){
		Console::outln(" and method 3")
	}

};

// Test::method2 implementated outside of class Test 
function Test::method2(){
	Console::outln("Access method 2")
}

var t=new Test()

t.method1(); // prints "Access method 1 and method 3"
t.method2(); // prints "Access method 2"


----

===== Static function

Static function is a kind of helper function of generic purposes about the class type. To declare static function it should be defined with static keyword. To access static function it has to type the name of containing class and '::' operator followed with the name of the function.

*Example*

[source,javascript]
----
class Test{

	// static function
	static staticMethod(){
		Console::outln("Access static method")
	}

};

Test::staticMethod(); // prints "Access static method"

----

==== Member variables

Member variables (also called fields) are data that live within the instanced class. To access a member variable is done through field operator ('.') and preceded by _this_ keyword when is acceded within its member function

[source,javascript]
----
class Test{
	method3(){
		this.a=0;
	}
};


var t=new Test(); // t.a==undefined
t.method(); 	  // t.a==0
t.a=10; 		  // t.a==10

----

In the code it can see that when _t_ is instanced field 'a' is undefined. In the next section it'll shown some ways to initialize data when class is instantatiated.

<<<

===== Variable inicialization

====== Body

A class can initialize its variables defining them at its body with _var_ and assignment operator (=)

[source,javascript]
----
class Test{

	// Declaration and initialization of member variable 'a' as 10
	var a=10;
}

var t=new Test(); // t.a==10
----

====== Constructor

A constructor is a special member function that is called when the class is instanced with the _new_ operator. To create and initialize a variable member within _constructor_ function is done through _this_ keyword and member field operator ('.').  

[source,javascript]
----
class Test{

 	// Constructor function
	constructor(){
		this.a=10; // initialize member variable 'a' as 10
 	}
}

var t=new Test(); // t.a==10
----

==== Inheritance

A class can inherit another class through _extends_ keyword. The new extended class will copy all functions and variable initialization from base class. The extended class can call parent functions through _super_ keyword.

[source,javascript]
----

class A {
	constructor(){
		this.a=10;
	}
}; 


class B extends A{
	constructor(){
		super(); // call A::constructor
		this.b=10 + this.a; 
 	}
 	
}; 

var b=new B(); // b.a==10, b.b=20
----

include::chapter_2_the_language_class_metamethods.adoc[]
include::chapter_2_the_language_class_property.adoc[]

<<<

==== Iterator

An iterator is a type with a set of metamethods defined that allow iteration from a custom container type. The metamethods are the following,

- __get()_: it returns a value according current index
- __end()_: it returns a boolean value telling whether the iterator has finished or not
- __next()_: it increments index iterator

Furthermore, it has to pass as a parameter the instance of the custom container type to reference its data. So, an iterator type should be defined as below,

[source,javascript]
----
class IteratorContainer{
	constructor(_container){
  		this.container=_container;
  		// ...
  	}
	_get(){
		//...
		return value;
	}
    _end(){
    	//...
    	return [true or false]
    }
    _next(){
    	// increments iterator
    }
}

----   

Finally, in order to have a custom container type as iterable it has to implement __iter_ metamethod that returns the defined iterator passing the instance of current object (i.e this).

[source,javascript]
----
class Container{
	_iter(){
		return new IteratorContainer(this);
	}
}

----

*Example*

[source,javascript]
----
include::../examples/the_language/class/class_metamethod_iterator.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/class/class_metamethod_iterator_out.txt[]
----
