=== Data types

ZetScript supports the following builtin data types,

* Undefined
* Null
* Integer
* Number
* Boolean
* String
* Array
* Object
* Function
* Class

==== Undefined

_Undefined_ data type it defines a non initialized variable. A variable is instanced as _Undefined_ once a its assings _undefined_ value,

[source,javascript]
----
var a; // 'a' is undefined as default
var b=undefined; // assigns undefined value
----

==== Null

_Null_ data type it defines an empty or not valid variable. A variable is instanced as _Null_ once a its assings _null_ value,

[source,javascript]
----
var i=null;
----

<<<

==== Integer

_Integer_ data type it defines a integer variable with range from -(2b-1) to 2b-1-1 where b=32 or 64 it depending whether ZetScript is compiled for 32bits or 64bits. A variable is initialized as _Integer_ once it assigns _decimal_, _hexadecimal_, _binary_ or _character_ value.

Example,

[source,javascript]
----
var a=10; // decimal
var b=0x1a; // hexadecimal
var c=01001b; // binary
var d='b'; //  character
----

===== Operators

ZetScript supports the following operators for _Integer_ variables,

[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Result

|Negate
|-variable 
|Negates its value
|
[source,javascript]
 var i=10;
 var j=-i; // j=-10
 
|Bitwise complement
|~variable 
|Invert all bits
|
[source,javascript]
 var i=00000011b;
 var j=~i; // j=11111100b or -4 decimal
|PreIncrement
|++variable 
|Increments FIRST and THEN evaluates
|
[source,javascript]
 var i=0;
 var j=++i; // j=1, i =1
 
|PostIncrement
|variable++ 
|Evaluates FIRST and THEN increments
| 
[source,javascript]
var i=0; 
var j=i++; // j=0; i=1

| Predecrement
| --variable 
|Decrements FIRST and THEN evaluates
| 
[source,javascript]
var i=0; 
var j=--i; // j=-1; i=-1

|Postdecrement
|variable--
|Evaluates FIRST and THEN decrements
|[source,javascript] 
var i=0; 
var j=i--;//j=0;i=-1;
|====

===== Static functions

====== Integer::parse()

Converts a given value to _Integer_

*Syntax*

[source,javascript]
----
parse(_value)
----

[.underline]#Parameters#

- __value_ : value to be converted as _Integer_

[.underline]#Returns#

_Integer_ as a result of converted value

*Example*

[source,javascript]
----
include::../examples/the_language/integer/integer_parse.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/integer/integer_parse_out.txt[]
----

==== Float

_Float_ type it defines a variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits. A variable is initialized as _Float_ once it assigns a decimal or scientific value notation forms.

Example,

[source,javascript]
----
var a=1.2 // decimal form value
var b=2.0e-2 // cientific notation form value
----


===== Operators

ZetScript supports the following operators for _Float_ variables,


[cols="1d,1m,2d,2a"]
|====
|Operator |Expression |Description |Result

|Negate
|-variable 
|Evaluates negated variable
|
[source,javascript]
 var i=10.5;
 var j=-i; // j=-10.5

|PreIncrement 
|++variable 
|Increments FIRST and THEN evaluates
|
[source,javascript]
var i=0.5;
var j=++i; // j=1.5, i =1.5

|PostIncrement 
|variable++ 
|Evaluates FIRST and THEN increments
|
[source,javascript]
var i=0.5;
var j=i++; // j=0.5; i=1.5

|Predecrement 
|--variable 
|Decrements FIRST and THEN evaluates
|
[source,javascript]
var i=0.5;
var j=--i; // j=-0.5; i=-0.5

|Postdecrement 
|variable-- 
|Evaluates FIRST and THEN decrements
|
[source,javascript]
var i=0.5;
var j=i--;//j=0.5;i=-0.5;
|====

===== Static functions

====== Float::parse()

Converts a given value to _Float_.

*Syntax*

[source,javascript]
----
Float::parse(_value)
----

[.underline]#Parameters#

- __value_ : value to be converted as _Float_.

[.underline]#Returns#

_Float_ as a result of converted value.

*Example*

[source,javascript]
----
include::../examples/the_language/float/float_parse.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/float/float_parse_out.txt[]
----

==== Boolean

_Boolean_ type it defines a variable represented as _true_ or _false_ value. A variable is initialized as _Boolean_ once it assigns a boolean value.

Example,

[source,javascript]
----
var b=false;
----

==== String

_String_ type it defines a variable represented as a string value. A variable is initialized as _String_ once it assigns a string or a sequence of chars between double quotes.

*Example*

[source,javascript]
----
var s="this is a string";
----

===== Properties
 
====== String::length

Returns the length of the string.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_length.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_length_out.txt[]
----

===== Member functions

====== String::insertAt()

Inserts string or character value into the string at defined position.

*Syntax*

[source,javascript]
----
String::insertAt(_position,_value)
----

[.underline]#Parameters#

- __position_: Position where to insert. The position ranges within 0 to the length-1 of the string.
- __value_: String or character value.

[.underline]#Returns#

None

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_insert_at.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_insert_at_out.txt[]
----

====== String::eraseAt(_position)

Removes the value at defined position of the string.

[.underline]#Parameters#

- __position_:  The position where there's the value to remove. The position ranges within 0 to the length-1 of the string.

[.underline]#Returns# 

None

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_erase_at.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_erase_at_out.txt[]
----

====== String::toUpperCase()

Returns a copy of the string converted to uppercase.

*Syntax*

[source,javascript]
----
String::toUpperCase()
----

[.underline]#Parameters#

None

[.underline]#Returns#

A copy of the string converted to uppercase.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_to_upper_case.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_to_upper_case_out.txt[]
----

====== String::toLowerCase()

Returns a copy of string converted to lowercase.

*Syntax*

[source,javascript]
----
String::toLowerCase()
----

[.underline]#Parameters#

None

[.underline]#Returns# 

 A copy of string converted to lowercase.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_to_lower_case.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_to_lower_case_out.txt[]
----

====== String::clear()

Erases the contents of the string.

*Syntax*

[source,javascript]
----
String::clear()
----

[.underline]#Parameters#

None

[.underline]#Returns#

None 

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_clear.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/string/string_clear_out.txt[]
----

====== String::replace()

Returns the copy of the string modified with substrings replaced by a matching string and a remplacement string.

*Syntax*

[source,javascript]
----
String::replace(_matching_string, _replacement_string)
----

[.underline]#Parameters#

- __matching_string_: String value as a matching value to be replaced.
- __replacement_string_: The string to be replaced.

[.underline]#Returns# 

Returns the copy of the string replacing __matching_string_ by __remplacement_string_.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_replace.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/string/string_replace_out.txt[]
----

====== String::split()

Breaks the string into and _xref:chapter_2_the_language_data_types#_array[Array]_ of strings by a separator.

*Syntax*

[source,javascript]
----
String::split(_separator)
----

[.underline]#Parameters#

- __separator_ : String or character as separator.

[.underline]#Returns# 

An _xref:chapter_2_the_language_data_types#_array[Array]_ of strings.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_split.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_split_out.txt[]
----

====== String::contains()

Find out if a string contains a sequence of characters.

*Syntax*

[source,javascript]
----
String::contains(_value)
----

[.underline]#Parameters#

- __value_:  A sequence of characters to find.

[.underline]#Returns#

Returns true if the characters exist and false if not.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_contains.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/string/string_contains_out.txt[]
----

====== String::indexOf()

Returns the position of the first occurrence of a sequence of characters in the string.

*Syntax*

[source,javascript]
----
String::indexOf(_search_value)
----

[.underline]#Parameters#

- __search_value_ :  A sequence of characters to search for.

[.underline]#Returns# 

An _Integer_ value, representing the index position of first occurrence found, or -1 if not found

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_index_of.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_index_of_out.txt[]
----

====== String::startsWith()

Find out if the string starts with the specified characters.

*Syntax*

[source,javascript]
----
String::startsWidth(_value)
----

[.underline]#Parameters#

- __value_ :  A _String_, representing the characters to check for.

[.underline]#Returns# 

A _Boolean_ value as _true_ if __value_ matches starting string, otherwise it returns _false_.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_starts_with.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_starts_with_out.txt[]
----

====== String::endsWith()

Find out if the string ends with the specified characters

*Syntax*

[source,javascript]
----
String::endsWidth(_value)
----

[.underline]#Parameters#

- __value_ :  A _String_, representing the characters to check for.

[.underline]#Returns# 

A _Boolean_ value as _true_ if __value_ matches ending string, otherwise it returns _false_.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_ends_with.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_ends_with_out.txt[]
----

====== String::substring()

Returns string defined between a start index and end index.

*Syntax*

[source,javascript]
----
String::substring(_start_index, _end_index)
----

[.underline]#Parameters#

- __start_index_: The index of the first character to include in the returned substring.
- __end_index_ (optional): The index of the first character to exclude from the returned substring.

[.underline]#Returns#

A string specified by start and end index.

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_substring.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/string/string_substring_out.txt[]
----

====== String::append()

Extends the string by appending string at the end.

*Syntax*

[source,javascript]
----
String::append(_value)
----

[.underline]#Parameters#

- __value__ : value to be appended

[.underline]#Returns# 

None

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_append.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_append_out.txt[]
----

===== Static functions
 
====== String::format()

Returns a formatted string.

*Syntax*

[source,javascript]
----
String::format(_string,..._args)
----

[.underline]#Parameters#

- __string_ : _String_ representation with specified arguments and/or its format. Argument format is defined in the __string_ value within curly brackets (i.e between '{' and '}' ) where it specifies argument number and its format. The argument format is described below,

[cols="1m,3d"]
|====
|Format |description
|{n}
|It replaces {_n_} by the argument _n_
|{n:dm}
|It replaces the argument _n_ padding _m_ 0s on its left
|{n,m}
|It replaces argument _n_ padding _m_ spaces on its left
|====

- __args_ : variable args to be replaced in the string representation

[.underline]#Returns#

A formated string

*Example*

[source,javascript]
----
include::../examples/the_language/string/string_format.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/string/string_format_out.txt[]
----


==== Array

_Array_ is a container type that stores variables or values in a unidimensional array. A variable is initialized as _Array_ once it assings a open/closed square brackets, 

[source,javascript]
----
[]; // an array instanced
----

Variable instanced as _Array_ can also have initialized with a sequence of elements separated with coma (i.e ',') within square brackets  (i.e between '[' and ']' ),

[source,javascript]
----
[1,"string",true,2.0]; // A array instanced with elements
----

To access element array is done through _Integer_ value as a index.

[source,javascript]
----
var v=[1,"string",true,2.0]; // variable 'v' has 4 elements where its access exist in [0..3]
v[1]; // It access array's second element (i.e "string")
----

===== Properties

====== Array::length

Returns the number of elements in the array

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_length.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/array/array_length_out.txt[]
----

===== Member functions

====== Array::push()

Adds a new element at the end of the array

*Syntax*

[source,javascript]
----
Array::push(_value)
----

[.underline]#Parameters#

- __value_ : value to be added

[.underline]#Returns# 

None

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_push.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/array/array_push_out.txt[]
----

====== Array::pop()

Removes the last element in the array

[source,javascript]
----
Array::pop()
----

[.underline]#Parameters#

None

[.underline]#Returns# 

Last value of the array before be removed

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_pop.zs[]
----

Output

[source,text]
----
include::../examples/the_language/array/array_pop_out.txt[]
----

====== Array::insertAt(_pos,_value)

Inserts element in the array at defined position

[source,javascript]
----
Array::insertAt(_pos,_value)
----

[.underline]#Parameters#

- __position_: Position where to insert. The position ranges within 0 to the length-1 of the array
- __value_: value to insert

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_insert_at.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/string/string_insert_at_out.txt[]
----

====== Array::eraseAt()

Removes the value at defined position

[source,javascript]
----
Array::eraseAt(_pos)
----

[.underline]#Parameters#

- __position_:  The position where there's the value to remove. The position ranges within 0 to the length-1 of the array

[.underline]#Returns# 

None

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_erase_at.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/array/array_erase_at_out.txt[]
----

====== Array::clear()

Clears all elements in the array

[source,javascript]
----
Array::clear()
----

[.underline]#Parameters#

None

[.underline]#Returns#

None 

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_clear.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/array/array_clear_out.txt[]
----

====== Array::join(_separator)

Concatenates all elements of the array into a string using a separator

[source,javascript]
----
Array::join(_separator)
----

[.underline]#Parameters#

- __separator_ : separator value

[.underline]#Returns# 

A string of all concatenated array's elements 

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_join.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/array/array_join_out.txt[]
----

====== Array::contains(_value)

Tells whether a value is contained in the array or not

[source,javascript]
----
Array::contains(_value)
----

[.underline]#Parameters#

- __value_: a value to find

[.underline]#Returns#

A boolean value telling if the value exist or not in the array 

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_contains.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/array/array_contains_out.txt[]
----

====== Array::extend(_v)

Extends the calling array by appending all elements from a array

[source,javascript]
----
Array::extend(_v)
----

[.underline]#Parameters#

- __v_ : Array type which all elements will appended into the array

[.underline]#Returns# 

None

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_extend.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/array/array_extend_out.txt[]
----

===== Static functions

====== Array::concat()

Creates a new array as a result of merge all elements from two arrays

*Syntax*

[source,javascript]
----
Array::concat(_v1, _v2)
----

[.underline]#Parameters#

- __v1_ : First array to concatenate into the new array
- __v2_ : Second array to concatenate into the new array

[.underline]#Returns# 

A new array as a result of merge all elements from the arrays

*Example*

[source,javascript]
----
include::../examples/the_language/array/array_concat.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/array/array_concat_out.txt[]
----


==== Object

Array type it defines a container type that stores a serie of key-value data. _Object_ is declared as open/closed of curly brackets (i.e '{}'),

[source,javascript]
----
{}; // Object
----

Optionally it be init with series of pair key-value separated by comma.

[source,javascript]
----
{
  i:1
 ,s:"string"
 ,b:true
 ,f:2.0
};
----

The access to its fields is done through the variable object followed by '.' and key name or key name as string within brackets (i.e ["key_name"] ),

[source,javascript]
----

var o={
  i:1
 ,s:"string"
 ,b:true
 ,f:2.0
};

o.i; // access field 'i' by '.'
o["i"]; // access field 'i' by '[]'
----

===== Static functions

====== Object::clear()

Clears all elements of an object

*Syntax*

[source,javascript]
----
Object::clear(_o)
----

[.underline]#Parameters#

- __o_: The object to clear elements

[.underline]#Returns#

None 

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_clear.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/object/object_clear_out.txt[]
----

====== Object::erase(_key_id)

Removes an attribute of an object

*Syntax*

[source,javascript]
----
Object::erase(_key_id)
----

[.underline]#Parameters#

- __o_: The object to erase element
- __key_id_:  The key id of the attribute to remove

[.underline]#Returns# 

None

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_erase.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/object/object_erase_out.txt[]
----

====== Object::contains()

Tells whether a key is contained in an object or not

*Syntax*

[source,javascript]
----
Object::contains(_key_id)
----

[.underline]#Parameters#

- __o_: The object to check
- __key_: a key to find

[.underline]#Returns#

A boolean value telling if the attribute with __key_id_ exist or not in the object 

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_contains.zs[]
----

Console output:

[source,txt]
----
include::../examples/the_language/object/object_contains_out.txt[]
----

====== Object::extend()

Extends an object by the content of other object

*Syntax*

[source,javascript]
----
Object::extend(_o1,_o2)
----

[.underline]#Parameters#

- __o1_ : Object where to be extended
- __o2_ : Object where to copy the extension

[.underline]#Returns# 

None

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_extend.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/object/object_extend_out.txt[]
----

====== Object::concat()

Creates a new object as a result of merge all elements from two objects

*Syntax*

[source,javascript]
----
Object::concat(_o1, _o2)
----

[.underline]#Parameters#

- __o1_ : First object to concatenate into the new object
- __o2_ : Second object to concatenate into the new object

[.underline]#Returns# 

A new object as a result of merge all elements from the two objects

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_concat.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/object/object_concat_out.txt[]
----

====== Object::keys(_o)

Returns a array of string representing its key names

*Syntax*

[source,javascript]
----
Object::keys(_o)
----

[.underline]#Parameters# 

- __o_ : Object from get the keys

[.underline]#Returns# 

A array of strings of its key names

*Example*

[source,javascript]
----
include::../examples/the_language/object/object_keys.zs[]
----

Console output:

[source,text]
----
include::../examples/the_language/object/object_keys_out.txt[]
----


==== Function

Function type is a type that contains function information to be invoqued at some place through paranthesis (). A variable is initialized as _Function_ once it assings an a function or anonymous function

*Example*

Assing normal function to variable

[source,javascript]
----

// function add
function add(_a,_b){
	return _a+_b
}

// function add assigned to fun
var fun=add;

...

Console::outln(fun(5,5)); // it prints "10"

----

Also it assing anonymous function to variable

[source,javascript]
----

// anonymous function assigned to fun
var fun=function(_a,_b){
	return _a+_b
};

...

Console::outln(fun(5,5)); // it prints "10"
----

For more information about Functions go to section X.XX

==== Class

Class type is a custom type that operates with its variables and functions. A class is defined by keyword _class_ followed by name. 

[source,javascript]
----
// Definition class A
class A{

}
----

To instance a object of type class is done through operator _new_ followed by the class name defined with parethesis

[source,javascript]
----
// Instances object class type A
var a=new A();
----

Also a class type can extend from another class with _extends_ keyword


[source,javascript]
----
// Definition class A
class A{

}


// Definition class B that extends from B
class B extends A{

}
----

For more information about class type go to section X.XX

