=== Byte code

=== Byte codes

The following table shows the byte codes and its meaning,

[cols="1m,2d,3d,6a"]
|====
|Instruction |Name |Description

		EQU";  // ==
			INSTANCEOF";  // ==
			NOT_EQU" ;  // !=
			LT";  // <
			LTE";  // <=
			NOT"; // !
			GT";  // >
			GTE"; // >=
			NEG"; // !
			BWC"; // ~
			ADD"; // +
			SUB"; // -
			LOGIC_AND"; // &&
			LOGIC_OR";  // ||
			DIV"; // /
			MUL"; // *
			MOD";  // %
			AND"; // bitwise logic and
			OR"; // bitwise logic or
			XOR"; // logic xor
			SHL"; // shift left
			SHR"; // shift right
			STORE"; // =
			STORE_ADD"; // +=
			STORE_SUB"; // -=
			STORE_MUL"; // *=
			STORE_DIV"; // /=
			STORE_MOD"; // %=
			STORE_AND"; // &=
			STORE_OR"; // |=
			STORE_XOR"; // ^=
			STORE_SHL"; // <<=
			STORE_SHR"; // >>=
			PUSH_STK_GLOBAL_IRGO"; // load type var
			PUSH_STK_GLOBAL"; // push stk global
			PUSH_STK_LOCAL"; // push stk global
			PUSH_STK_REF"; // push stk global
			PUSH_STK_THIS"; // push stk global
			PUSH_STK_VEC@ITEM"; // load element vector
			PUSH_STK_OBJ@ITEM"; // load element object
			PUSH_STK_THIS@VAR"; // load element object

			LOAD_GLOBAL"; // load type var
			LOAD_LOCAL"; // load type var
			LOAD_REF"; // load type var
			LOAD_THIS"; // load type var
			LOAD_CONSTRUCTOR_FUNCT"; // load type var
			LOAD_???"; // load to find global
			// CALL
			CALL; // direct call
			CALL???"; // direct call
			STK_CALL"; // stack call


			MEMBER_CALL"; // this indirect call through dynamic symbol
			LOAD_THIS@VAR"; // load element object
			LOAD_THIS@FUN"; // load element object
			LOAD_VEC@ITEM"; // load element vector
			LOAD_OBJ@ITEM"; // load element object
			LOAD_FUN"; // load function
			LOAD_UNDEFINED"; // load undfined
			LOAD_NULL"; // load null
			LOAD_STK"; // load stack element

			LOAD_STR"; // load string
			LOAD_FLT"; // load float
			LOAD_BOOL"; // load bool
			LOAD_INT"; // load zs_int
			LOAD_TYPE"; // load to find
			JMP"; // Unconditional jump.
			JMP_CASE"; // Last jmp case
			JNT"; // goto if not true ... goes end to conditional.
			JT"; // goto if true ... goes end to conditional.
			JE_CASE"; // je case equal ... goes end to conditional.
			CALL_CONSTRUCTOR"; // calling function after all of arguments are processed...
			NEW_VEC"; // Array object (CREATE)
			PUSH_VITEM"; // Value push for stdvector
			RET"; // Value pop for stdvector
			NEW_OBJECT_BY_TYPE"; // New object (CREATE)
			NEW_OBJECT_BY_VALUE"; // New object (CREATE)
			DELETE";
			POP_SCOPE"; // New object (CREATE)
			PUSH_SCOPE"; // New object (CREATE)
			PUSH_OITEM"; // New object (CREATE)
			NEW_OBJECT"; // New object (CREATE)
			NEW_STR";
			IT_INIT"; // BYTE_CODE_IT_CHK_END
			STORE_CONST"; // BYTE_CODE_STORE_CONST
			PRE_INC"; // ++i
			PRE_DEC"; // --i
			POST_INC"; // i++
			NEG_POST_INC"; // -i++
			BWC_POST_INC"; // ~i++
			POST_DEC"; // i--
			BWC_POST_DEC"; // ~i--
			RESET_STACK"; // POP ONE AND IT MARKS END EXPRESSION
			CLEAR_ZERO_POINTERS";
			TYPEOF"; // POP ONE AND IT MARKS END EXPRESSION
			IN"; // POP ONE AND IT MARKS END EXPRESSION
|====