
=== Call C++ from ZetScript

To call &#43;&#43; code from _ZetScript_ it has to create and register a C function with a particular prototype. That C function acts as interface between ZetScript and &#43;&#43;. 

As parameters, the function must always include `zetscript::ZetScript *` as the first parameter and a maximum of 9 parameters as xref:chapter_3_the_api_types#_built_in_types[built-in type] or other registered type. 

As a return, the function it can return nothing, or a xref:chapter_3_the_api_types#_built_in_types[built-in type] or other registered type.

*Syntax*

[source,c++]
----
ReturnType zetscriptCppInterface(ZetScript *_zs, ParamType _arg1, ParamType _arg2, ..., ParamType _arg9 ){
	....
}
----

Where,

- _ReturnType_: It can be _void_ or some type defined in xref:chapter_3_the_api_types#_built_in_types[built-in types] or other registered type.
- _ParamType_: It can be one defined in  xref:chapter_3_the_api_types#_built_in_types[built-in types] or other registered type.


After the function is created it has be registered with ZetScript::registerFunction in order to be exposed in ZetScript. As a parameters, it passes a string value that will be the symbol name to be refered later in ZetScript and the C function reference.

*Syntax*

[source,c++]
----
template <typename F>
void registerFunction( const zs_string & _name_script_function,F _ptr_function);
----

*Example*

The following example registers a C function and calls it within an evaluated script.

[source,c++]
----
include::../examples/the_api/register_function/register_function.cpp[]
----


Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_out.txt[]
----

==== Return types

This section will explain how to register C functions that return the following types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Registered type

===== Return Boolean

To register a C function that returns a _xref:chapter_2_the_language_data_types#_boolean[Boolean]_ it must specify _bool_ return type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_bool_out.txt[]
----


===== Return Integer

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#_boolean[Integer]_ it must specify _zs_int_ return type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_int_out.txt[]
----

===== Return Float

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#_boolean[Float]_ it must specify _zs_float_ return type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_float_out.txt[]
----

===== Return a String

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#&lowbar;string[String]_ it can be done by specifying the following return types in its prototype,

- _zs_string_
- _StringScriptObject *_


====== Return String as zs_string

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]_ it can specify _zs_string_ return type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_string_out.txt[]
----

====== Return String as StringScriptObject &#42;

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]_ it can specify _StringScriptObject &#42;_ return type on its function prototype. The instantiation of _StringScriptObject &#42;_ it&#39;s done throught _ZetScript::newStringScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_string_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_string_script_object_out.txt[]
----

===== Return Array

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#lowbar;array[Array]_ it must specify _ArrayScriptObject &#42;_ return type on its function prototype. The instantiation of _ArrayScriptObject &#42;_ it's done through _ZetScript::newArrayScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_array_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_array_script_object_out.txt[]
----

===== Return Object

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#lowbar;object[Object]_ it must specify _ObjectScriptObject &#42;_ return type on its function prototype. The instantiation of _ObjectScriptObject &#42;_ it's done through _ZetScript::newObjectScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_object_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_object_script_object_out.txt[]
----


===== Return registered type


To register a C function that returns a _xref:chapter_3_the_api_expose_cpp_types#_register_type[registered type]_ it can be done by specifying the following return types in its prototype,

- Its native pointer type
- ClassScriptObject

 
===== Return registered class as its native pointer type

To register a C function that returns a _xref:chapter_3_the_api_expose_cpp_types#_register_type[registered type]_ it can specify its native pointer type as return in the function prototype.

ZetScript *never* destroy native pointers returned from C function. This is why it cannot allocate and return a type from the function itself because this would become a memory leak . Instead, the pointer should be take from a location that is active during the execution of the script that involves the operation of the returned pointer.

*Example*

In the following example it registers type _Point_ and its properties _x_ and _y_ and it registers native function _returnPoint_ that returns a _Point_ a type pointer. In the main program it creates a _Point_ type and that is acceded globally, so the registered native function can access and return this instanced _Point_ type.


[source,c++]
----
include::../examples/the_api/register_function/register_function_return_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_registered_type_out.txt[]
----

===== Return registered class as ClassScriptObject

To register a C function that returns a _xref:chapter_3_the_api_expose_cpp_types#_register_type[registered type]_ it can specify _ClassScriptObject &#42;_ return type on its function prototype. To instantiate _ClassScriptObject &#42;_  is done through _<<ZetScript::newClassScriptObject>>_ using ZetScript context and the registered class instantiated.

A difference from returning a pointer type of a registered class, when the C function returns a _ClassScriptObject &#42;_ object ZetScript is in charge to deallocate automatically when there's no more references. 

To be have the class wrappable inside _ClassScriptObject &#42;_, it must be registered as instancialbe (see <<Register class as instanciable>>)

*Example*

In the following example it registers a native type _Point_ and its properties _x_ and _y_ and it registers native function _returnPoint_ that instances and returns a _ClassScriptObject_ as _Point_ type. 

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_class_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_class_script_object_out.txt[]
----

==== Parameter types


This section will explain how to register C functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered type

===== Parameter Boolean

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#_boolean[Boolean]_ it must specify _bool_ as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_bool_out.txt[]
----

===== Parameter Integer

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;integer[Integer]_ it must specify _zs_int_ as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_int_out.txt[]
----

===== Parameter Float

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;float[Float]_ it must specify _zs_float_ as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_float_out.txt[]
----

===== Parameter String

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#_boolean[String]_ it can specify the following types as a parameter on its function prototype,

- const char *
- zs_string *
- StringScriptObject *

===== Parameter String as const char *

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]_ it can specify *const char &#42;* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_const_char.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_const_char_out.txt[]
----

===== Parameter String as zs_string *

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]_ it can specify *zs_string &#42;* as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_string_out.txt[]
----

===== Parameter String as StringScriptObject *

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]_ it can specify _StringScriptObject &#42;_ as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_string_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_string_script_object_out.txt[]
----

===== Parameter Array

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;array[Array]_ it must specify _ArrayScriptObject &#42;_ as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_array_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_array_script_object_out.txt[]
----

===== Parameter Object

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;object[Object]_ it must specify _ObjectScriptObject &#42;_ as parameter type on its function prototype.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_object_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_object_script_object_out.txt[]
----

===== Parameter Function

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;function[Function]_ it must specify *ScriptFunction &#42;* as parameter type on its function prototype. To make  _ScriptFunction_ callable from C++ it must to bind that using <<bindScriptFunction>>.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_script_function.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_script_function_out.txt[]
----

===== Parameter Registered Type

To register a C function that accepts a <<Registered type>> as a parameter, it must specify the *Registered type pointer* as parameter type on its function prototype.

*Example*

In the following example it registers the Point type and its properties _x_ and _y_  (see <<Register type>> section to know about how to register class and properties) and it registers function _mul10Point_ that accepts a Point type pointer as parameter. In the script execution it instances a Point type and is passed as argument to _mul10Point_ that multiply its properties by 10.

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_registered_type_out.txt[]
----