
=== Call C++ from ZetScript

To call C&#43;&#43; code from _ZetScript_ it has to create and register a C function with a particular prototype. That C function acts as interface between ZetScript and C&#43;&#43;code. 

The function must always include _zetscript::ZetScript *_ as the FIRST parameter and from SECOND till a maximmum of 9 parameters as a xref:chapter_3_the_api_built_in_types#_built_in_types[built-in type] or a xref:chapter_3_the_api_expose_cpp_types#_register_a_type[registered type]. The function it can return nothing or it can return a xref:chapter_3_the_api_built_in_types#_built_in_types[built-in type] or a xref:chapter_3_the_api_expose_cpp_types#_register_a_type[registered type].

*Syntax*

[source,c++]
----
ReturnType zetscriptCppInterface(ZetScript *_zs, ParamType _arg1, ParamType _arg2, ..., ParamType _arg9 ){
	....
}
----

Where,

- _ReturnType_: It can be _void_ , a xref:chapter_3_the_api_built_in_types#_built_in_types[built-in type] or a xref:chapter_3_the_api_expose_cpp_types#_register_a_type[registered type].
- _ParamType_: It can be a xref:chapter_3_the_api_built_in_types#_built_in_types[built-in type] or a xref:chapter_3_the_api_expose_cpp_types#_register_a_type[registered type].


After the C function is created is registered with _ZetScript::registerFunction_. 

*Syntax*

[source,c++]
----
void registerFunction( const zs_string & _function_name,F _c_function);
----

[.underline]#Parameters#

- __function_name_ : The function name to be refered in ZetScript.
- __c_function_ : The C function to register.

*Example*

The following example registers a C function _sayHelloWorld_ and it is called in ZetScript.

[source,c++]
----
include::../examples/the_api/register_function/register_function.cpp[]
----


Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_out.txt[]
----

==== Return types

This section will explain how to register C functions that return the following ZetScript types,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Registered type

===== Return Boolean

To register a C function that returns a _xref:chapter_2_the_language_data_types#_boolean[Boolean]_ it must specify _bool_ return type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_bool_out.txt[]
----


===== Return Integer

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#_integer[Integer]_ it must specify _zs_int_ return type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_int_out.txt[]
----

===== Return Float

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#_float[Float]_ it must specify _zs_float_ return type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_float_out.txt[]
----

===== Return a String

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#&lowbar;string[String]_ it can be done by specifying the following return types,

- _zs_string_
- _StringScriptObject *_


====== Return String as zs_string

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]_ it can specify _zs_string_ return type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_zs_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_zs_string_out.txt[]
----

====== Return String as StringScriptObject &#42;

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#lowbar;string[String]_ it can specify _StringScriptObject &#42;_ return type. The instantiation of _StringScriptObject &#42;_ it&#39;s done throught _ZetScript::newStringScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_string_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_string_script_object_out.txt[]
----

===== Return Array

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#lowbar;array[Array]_ it must specify _ArrayScriptObject &#42;_ return type. The instantiation of _ArrayScriptObject &#42;_ it's done through _ZetScript::newArrayScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_array_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_array_script_object_out.txt[]
----

===== Return Object

To register a C function that returns a _xref:chapter_2_the_language_data_types.adoc#lowbar;object[Object]_ it must specify _ObjectScriptObject &#42;_ return type. The instantiation of _ObjectScriptObject &#42;_ it's done through _ZetScript::newObjectScriptObject_ using ZetScript context.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_object_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_object_script_object_out.txt[]
----


===== Return registered type


To register a C function that returns a _xref:chapter_3_the_api_expose_cpp_types#_register_type[registered type]_ it can be done by specifying the following return types,

- Return registered type by its reference
- Return registered type by ClassScriptObject 

 
===== Return registered type by its reference

To register a C function that returns a _xref:chapter_3_the_api_expose_cpp_types#_register_type[registered type]_ it must specify its native pointer type as return.

====
ZetScript *NEVERS* destroy a native pointer returned from registered function. This is why it *CANNOT* allocate and return a type from the C function because this becomes a memory leak. Instead, the object  should be instantiated outside of ZetScript and accessible from a location where its lifetime is active during the execution of the script.
====

Because the function it returns a native reference the type can be registered as instantiable or not instantiable (see xref:chapter_3_the_api_expose_cpp_types#&#x5f;register_a_type_as_instantiable[section 3.5.1])

*Example*

In the following example it registers a type _Number_ as non instantiable (see xref:chapter_3_the_api_expose_cpp_types#&#x5f;register_a_type_as_non_instantiable[section 3.5.1] to know how to register a type as NON INSTANTIABLE) and its property _value_ (see xref:chapter_3_the_api_expose_cpp_types#&#x5f;properties[section 3.5.5] to know how to register a property). Finally, it registers C function _returnNumber_ that returns a _Number *_. In the main program instantiates _Number_ object and is acceded globally, so is active during the execution of the script.


[source,c++]
----
include::../examples/the_api/register_function/register_function_return_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_registered_type_out.txt[]
----

===== Return registered type by ClassScriptObject &#42;

To register a C function that returns a _xref:chapter_3_the_api_expose_cpp_types#_register_type[registered type]_ it must specify _ClassScriptObject &#42;_ return type. To instantiate _ClassScriptObject &#42;_  is done through _ZetScript::newClassScriptObject_ using ZetScript context and the registered class instantiated.

A difference from returning a pointer type of a registered type, when the C function returns a _ClassScriptObject &#42;_ ZetScript is in charge to deallocate automatically when it has no more references to it. 

====
To be have the class wrappable inside _ClassScriptObject &#42;_, it must be registered as instancialbe (see xref:chapter_3_the_api_expose_cpp_types#&#x5f;register_a_type_an_instantiable[section 3.5.1] to know how to register a type AS INSTANTIABLE])
====

*Example*

In the following example it registers type _Number_ as instantiable (see xref:chapter_3_the_api_expose_cpp_types#&#x5f;register_a_type_as_instantiable[section 3.5.1] to know how to register a type AS INSTANTIABLE) and its property _value_. Finally, it registers C function _returnNumber_ that instances and returns a _ClassScriptObject_ as _Number_ type. 

[source,c++]
----
include::../examples/the_api/register_function/register_function_return_class_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_return_class_script_object_out.txt[]
----

==== Parameter types


This section will explain how to register C functions that accepts the following types as parameters,

- Boolean
- Integer
- Float
- String
- Array
- Object
- Function
- Registered type

===== Parameter Boolean

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#_boolean[Boolean]_ it must specify _bool_ as parameter type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_bool.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_bool_out.txt[]
----

===== Parameter Integer

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;integer[Integer]_ it must specify _zs_int_ as parameter type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_int.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_int_out.txt[]
----

===== Parameter Float

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;float[Float]_ it must specify _zs_float_ as parameter type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_float.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_float_out.txt[]
----

===== Parameter String

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#_string[String]_ it can specify _const char *_ , _zs_string *_  or _StringScriptObject *_ as a parameter type,

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_zs_string.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_zs_string_out.txt[]
----

===== Parameter Array

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;array[Array]_ it must specify _ArrayScriptObject &#42;_ as parameter type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_array_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_array_script_object_out.txt[]
----

===== Parameter Object

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;object[Object]_ it must specify _ObjectScriptObject &#42;_ as parameter type.

*Example*

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_object_script_object.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_object_script_object_out.txt[]
----

===== Parameter Function

To register a C function that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;function[Function]_ it must specify _ScriptFunction &#42;_ as parameter type. To make  _ScriptFunction_ callable from C++ must use _ZetScript::bindScriptFunction_ (see xref:_chapter_3_the_api_call_zetscript_from_cpp#&#x5f;call_zetscript_from_c[section 3.4] to know more about ZetScript functions binding)

*Example*

The following example it registers function _paramScriptFunction_ that accepts a _xref:chapter_2_the_language_data_types.adoc#lowbar;function[Function]_ as parameter. Later, it evaluates an script that calls _paramScriptFunction_ passing anonymous function. In the calling function _paramScriptFunction_ it binds the anonymous function and it calls.

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_script_function.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_script_function_out.txt[]
----

===== Parameter Registered Type

To register a C function that accepts a _xref:chapter_3_the_api_expose_cpp_types#&#x5f;register_type[registered type]_ as a parameter, it must specify native pointer type as parameter type.

*Example*

In the following example it registers the _Number_ type (see xref:chapter_3_the_api_expose_cpp_types#_register_type[section 3.5.1] to know how to register a type) and its property _value_ (see xref:chapter_3_the_api_expose_cpp_types#&#x5f;properties[section 3.5.5] to know how to register a property) and it registers function _mul10Number_ that accepts a _Number &#x2a;_ type as parameter. In the script execution it instances a _Number_ and it is passed as argument to _mul10Number_ that multiplies its property _value_ by 10.

[source,c++]
----
include::../examples/the_api/register_function/register_function_param_registered_type.cpp[]
----

Console output:

[source,txt]
----
include::../examples/the_api/register_function/register_function_param_registered_type_out.txt[]
----