
=== Built-in types

The built-in types that interfaces from ZetScript to C++ and viceversa are the following,

- zs_int
- zs_float
- zs_string
- StringStringObject
- ArrayStringObject
- ObjectStringObject
- ScriptFunction
- ClassStringObject

==== zs_int

Integer data type it defines a integer variable with range from `-(2^b-1^)` to `2^b-1^-1` where `b=32` or `b=64` it depending whether ZetScript is compiled for 32bits or 64bits. 

*Example*

[source,c++]
----
zetscript::zs_int i=10;
----

==== zs_float

_zs_float_ type it defines a float variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits.

*Example*

[source,c++]
----
zetscript::zs_float f=20.5;
----

==== zs_string

_zs_string_ it defines a string represented a sequence of chars

*Example*

[source,c++]
----
zetscript::zs_string s="Hello World";
----

===== Operators

_zs_string_ has the following operators,

[cols="3m,6a"]
|====
|Operator |Description
|=
|Assigment

|+=
|Concatenates and assings to string

|[]
|Access to element

|+
|Concatenates two zs_strings

|==
|Performs equals operation between two zs_strings

|!=
|Performs not equal operation between two zs_strings
|====


===== Member functions

_zs_string_ has the following member functions,

- *zs_string::at()*:
- *zs_string::clear()*:
- *zs_string::substr()*:
- *zs_string::find()*:
- *zs_string::find_last_of()*:
- *zs_string::replace()*:
- *zs_string::append()*:
- *zs_string::erase()*:
- *zs_string::insert()*:
- *zs_string::empty()*:
- *zs_string::length()*:
- *zs_string::c_str()*:


==== StringScriptObject

_StringScriptObject_ it defines a string script object and encapsules _zs_string_ reference. It uses zetscript context in order to be instanced

*Example*

[source,c++]
----
zetscript::StringScriptObject str=zs.newStringScriptObject();
str.set("Hello World");
----

See <<zetscript::StringScriptObject>> for more information

==== ArrayScriptObject

_ArrayScriptObject_ it defines a array script object that acts as a array container of elements. It uses zetscript context in order to be instanced.

*Example*

[source,c++]
----
zetscript::ArrayScriptObject array=zs.newArrayScriptObject();

// push as integer 10 value
object->push<zs_int>(10)
----


===== Member functions

_ArrayScriptObject_ member functions available for user operations are the following,

- *ArrayScriptObject::push()*:


==== ObjectScriptObject

_ObjectScriptObject_ it defines a object script object that acts as a container of fields. It uses zetscript context in order to be instanced

*Example*

[source,c++]
----
zetscript::ObjectScriptObject *object=zs.newObjectScriptObject();

// add field "a" and 10 int as value
object->set<zetscript::zs_int>("a",10)

----

===== Member functions

_ObjectScriptObject_ member functions available for user operations are the following,

- *ObjectScriptObject::set()*:

==== zetscript::FunctionObject

_FunctionObject_ it defines a function object that contains function information.
