
=== Types

This section wil describe the types used in the library in order to interop data native/script and the ZetScript class, the core the most operations in the library.

==== zs_int

Integer data type it defines a integer variable with range from -(2^b-1^)` to `2^b-1^-1 where `b=32` or `b=64` it depending whether ZetScript is compiled for 32bits or 64bits. 

*Example*

[source,c++]
----
zetscript::zs_int i=10;
----

==== zs_float

_zs_float_ type it defines a float variable represented as IEEE-754 floating point numbers in 32-bit or 64 bit it depending whether ZetScript is compiled for 32bits or 64bits.

*Example*

[source,c++]
----
zetscript::zs_float f=20.5;
----

==== zs_string

_zs_string_ it defines a string represented a sequence of chars

*Example*

[source,c++]
----
zetscript::zs_string s="Hello World";
----

===== Member functions

_zs_string_ has the following member functions,

====== zs_string::operator=()

Assigns a new value to the string, replacing its current contents.

======  zs_string::operator+=()

Appends __string_ at the end of current contents.

====== zs_string::operator[]()

Returns a reference to the character at position __pos_.

====== zs_string::at()

Returns a reference to the character at position __pos_.

====== zs_string::clear()

Erases the contents of the string.

====== zs_string::substr()

Returns a new string with its value initialized to a copy of a substring of this object. The substring is the portion of the object that starts at character position __pos_ and spans _&#x5f;len_ characters.

======  zs_string::find()

Searches the string for the first occurrence of the sequence specified by its arguments. When _&#x5f;pos_ is specified, the search only includes characters at or after position _&#x5f;pos_, ignoring any possible occurrences that include characters before _&#x5f;pos_.

====== zs_string::find_last_of()

Searches the string for the last character that matches any of the characters specified in its arguments. When _&#x5f;pos_ is specified, the search only includes characters at or before position _&#x5f;pos_, ignoring any possible occurrences after _&#x5f;pos_.

====== zs_string::replace()

Replaces the portion of the string that begins at character _&#x5f;pos_ and spans _&#x5f;len_ characters.


====== zs_string::append()

Appends __string_ at the end of current contents.

====== zs_string::erase()

Erases part of the string, reducing its length.

====== zs_string::insert()

Inserts additional characters into the string right before the character indicated by _&#x5f;pos_.


====== zs_string::empty()

Returns whether the string is empty.


====== zs_string::length()

Returns the length of the string, in terms of bytes.

====== zs_string::c_str()

Returns a pointer to an array that contains a null-terminated sequence of characters (i.e., a C-string) representing the current value of the string object.

===== Static functions

_zs_string_ has the following static functions,

====== zs_string::operator+()

Returns a new string object with its value being the concatenation of the characters in left operand followed by those of right operand.

====== zs_string::operator==()

Performs the EQUAL comparison operation between the left operand and right operand.

====== zs_string::operator!=()

Performs the NOT EQUAL comparison operation between the left operand and right operand.


==== StringScriptObject

_StringScriptObject_ it defines a string script object and encapsules _zs_string_ reference. It uses zetscript context in order to be instanced


===== Member functions

_ArrayScriptObject_ member functions available for user operations are the following,

====== StringScriptObject::set()

Replaces current string value.

==== ArrayScriptObject

_ArrayScriptObject_ it defines a array script object that acts as a array container of elements. It uses zetscript context in order to be instanced.

===== Member functions

_ArrayScriptObject_ member functions available for user operations are the following,

====== ArrayScriptObject::push()

Appends _&#x5f;value_  of type _&#x5f;T_ at the end of array.

====== ArrayScriptObject::set()

Replaces current value at position _&#x5f;pos_ by _&#x5f;value_ of type _&#x5f;T_.

====== ArrayScriptObject::get()

Returns a reference element of type _&#x5f;T_ at position __pos_.

==== ObjectScriptObject

_ObjectScriptObject_ it defines a object script object that acts as a container of fields. It uses zetscript context in order to be instanced.


===== Member functions

_ObjectScriptObject_ member functions available for user operations are the following,

====== ObjectScriptObject::set()

Replaces current value at key _&#x5f;key_ by _&#x5f;value_ of type _&#x5f;T_.

====== ObjectScriptObject::get()

Returns element of type _&#x5f;T_ from key __key_.

==== ClassScriptObject

_ClassScriptObject_ it a subclass of _ObjectScriptObject_ that implements the _class_ type defined in ZetScript. Also it is used as a wrapper for instanced of registered C++ types.

==== ScriptFunction

_ScriptFunction_ it defines a function object that contains function information. 
