== Introduction

ZetScript is a script language with a syntax inspired in ECMAScript or Javascript but also it brings a easy way to bind parts of your C{plus}{plus} code. ZetScript provides a virtual machine so the execution is quite fast. Because ZetScript syntax is almost less or more equal to Javascript you can edit the code with any editor that supports Javascript syntax notation. 


=== Compile

To install ZetScript, first download last source code from https://zetscript.org and compile the project with the following steps,

 . First we have to configure the project using cmake application.
+
****
cmake -B build
****
+
. Second we have to compile the project. Using GNU tool chain is
done through this command,
+
****
make -C build
****

After the compilation, the ZetScript library (.a) and command line interpreter utility (_zs_) will be placed at __build__ directory.

Optionally, cmake configuration comes with the following options:

- __-DCMAKE_BUILD_TYPE={Release|Debug}__  : Configures ZetScript project for _Release_ or _Debug_ (by default is _Release_).
- __-DTESTS:BOOL={true|false}__ : Configures ZetScript to build or not tests (by default is _FALSE_).
- __-DSAMPLES:BOOL={true|false}__ : Configures ZetScript to build or not samples (by default is _FALSE_).
- __-DBUILD_SHARED:BOOL={true|false}__ : Configures ZetScript to build as _SHARED_ (by default is _STATIC_).

=== Hello World

Once ZetScript is compiled we present a quick sample of "HelloWorld" application, 

. Create a filename named helloworld.zs and type the following sentence
+
[source,zetscript]
Console::outln("Hello world!");
+	
. Save the file and do the following at command line,
+
 zs helloworld.zs
+
You should see the "Hello world" message at the command line. 


